import { Difficulty } from "./monstats-dict";

export type BossEntry = {
  id: string;
  nameStr: string;
  levels: [number, number, number];
  tcs: [
    string?,
    string?,
    string?,
    string?,
    string?,
    string?,
    string?,
    string?,
    string?
  ];
};

type BossHierarchyType = {
  minor: string[];
  actbosses: string[];
  pandemonium: string[];
};

export function getBossHierarchy(difficulty: Difficulty): BossHierarchyType {
  let bossHierarchy = {
    minor: [
      "bloodraven",
      "griswold",
      "radament",
      "summoner",
      "izual",
      "nihlathakboss",
      "putriddefiler1",
      "putriddefiler2",
      "putriddefiler3",
      "putriddefiler4",
      "putriddefiler5",
    ],
    actbosses: ["andariel", "duriel", "mephisto", "diablo", "baalcrab"],
    pandemonium: [],
    //   "uberandariel",
    //   "uberizual",
    //   "uberduriel",
    //   "ubermephisto",
    //   "uberdiablo",
    //   "uberbaal",
    // ],
  };
  // if (difficulty !== Difficulty.HELL) {
  //   bossHierarchy.pandemonium = [];
  // }
  return bossHierarchy;
}

export const categoriesLocale = {
  minor: "Minor",
  actbosses: "Act Bosses",
};

export const FlatBossDict: { [key: string]: BossEntry } = {
  bloodraven: {
    id: "bloodraven",
    nameStr: "Bloodraven",
    levels: [10, 43, 88],
    tcs: [
      "Blood Raven",
      null,
      "Blood Raven (N)",
      null,
      "Blood Raven (H)",
      null,
      "Blood Raven Desecrated A",
      "Blood Raven (N) Desecrated A",
      "Blood Raven (H) Desecrated A",
    ],
  },
  griswold: {
    id: "griswold",
    nameStr: "Griswold",
    levels: [5, 39, 84],
    tcs: [
      "Griswold",
      null,
      "Griswold (N)",
      null,
      "Griswold (H)",
      null,
      "Griswold Desecrated A",
      "Griswold (N) Desecrated A",
      "Griswold (H) Desecrated A",
    ],
  },
  radament: {
    id: "radament",
    nameStr: "Radament",
    levels: [16, 49, 83],
    tcs: [
      "Radament",
      null,
      "Radament (N)",
      null,
      "Radament (H)",
      null,
      "Radament Desecrated A",
      "Radament (N) Desecrated A",
      "Radament (H) Desecrated A",
    ],
  },
  summoner: {
    id: "summoner",
    nameStr: "Summoner",
    levels: [18, 55, 80],
    tcs: [
      "Summoner",
      null,
      "Summoner (N)",
      null,
      "Summoner (H)",
      null,
      "Summoner Desecrated A",
      "Summoner (N) Desecrated A",
      "Summoner (H) Desecrated A",
    ],
  },
  izual: {
    id: "izual",
    nameStr: "izual",
    levels: [29, 60, 86],
    tcs: [
      "Izual",
      null,
      "Izual (N)",
      null,
      "Izual (H)",
      null,
      "Izual Desecrated A",
      "Izual (N) Desecrated A",
      "Izual (H) Desecrated A",
    ],
  },
  nihlathakboss: {
    id: "nihlathakboss",
    nameStr: "Nihlathak",
    levels: [65, 70, 92],
    tcs: [
      "Nihlathak",
      null,
      "Nihlathak (N)",
      null,
      "Nihlathak (H)",
      null,
      "Nihlathak Desecrated",
      "Nihlathak (N) Desecrated",
      "Nihlathak (H) Desecrated",
    ],
  },
  putriddefiler1: {
    id: "putriddefiler1",
    nameStr: "Putrid Defiler1",
    levels: [35, 61, 80],
    tcs: [
      "Act 5 Cast A",
      null,
      "Act 5 (N) Cast A",
      null,
      "Act 5 (H) Cast A",
      null,
      null,
      null,
      null,
    ],
  },
  putriddefiler2: {
    id: "putriddefiler2",
    nameStr: "Putrid Defiler2",
    levels: [37, 62, 81],
    tcs: [
      "Act 5 Cast A",
      null,
      "Act 5 (N) Cast A",
      null,
      "Act 5 (H) Cast A",
      null,
      null,
      null,
      null,
    ],
  },
  putriddefiler3: {
    id: "putriddefiler3",
    nameStr: "Putrid Defiler3",
    levels: [38, 63, 82],
    tcs: [
      "Act 5 Cast B",
      null,
      "Act 5 (N) Cast B",
      null,
      "Act 5 (H) Cast B",
      null,
      null,
      null,
      null,
    ],
  },
  putriddefiler4: {
    id: "putriddefiler4",
    nameStr: "Putrid Defiler4",
    levels: [39, 64, 83],
    tcs: [
      "Act 5 Cast B",
      null,
      "Act 5 (N) Cast B",
      null,
      "Act 5 (H) Cast B",
      null,
      null,
      null,
      null,
    ],
  },
  putriddefiler5: {
    id: "putriddefiler5",
    nameStr: "Putrid Defiler5",
    levels: [40, 65, 84],
    tcs: [
      "Act 5 Cast B",
      null,
      "Act 5 (N) Cast B",
      null,
      "Act 5 (H) Cast B",
      null,
      null,
      null,
      null,
    ],
  },
  andariel: {
    id: "andariel",
    nameStr: "Andariel",
    levels: [12, 49, 75],
    tcs: [
      "Andarielq",
      "Andarielq",
      "Andarielq (N)",
      "Andarielq (N)",
      "Andarielq (H)",
      "Andarielq (H)",
      "Andarielq Desecrated A",
      "Andarielq (N) Desecrated A",
      "Andarielq (H) Desecrated A",
    ],
  },
  duriel: {
    id: "duriel",
    nameStr: "Duriel",
    levels: [22, 55, 88],
    tcs: [
      "Duriel",
      "Durielq",
      "Duriel (N)",
      "Durielq (N)",
      "Duriel (H)",
      "Durielq (H)",
      "Duriel Desecrated A",
      "Duriel (N) Desecrated A",
      "Duriel (H) Desecrated A",
    ],
  },
  mephisto: {
    id: "mephisto",
    nameStr: "Mephisto",
    levels: [26, 59, 87],
    tcs: [
      "Mephisto",
      "Mephistoq",
      "Mephisto (N)",
      "Mephistoq (N)",
      "Mephisto (H)",
      "Mephistoq (H)",
      "Mephisto Desecrated A",
      "Mephisto (N) Desecrated A",
      "Mephisto (H) Desecrated A",
    ],
  },
  diablo: {
    id: "diablo",
    nameStr: "Diablo",
    levels: [40, 62, 94],
    tcs: [
      "Diablo",
      "Diabloq",
      "Diablo (N)",
      "Diabloq (N)",
      "Diablo (H)",
      "Diabloq (H)",
      "Diablo Desecrated A",
      "Diablo (N) Desecrated A",
      "Diablo (H) Desecrated A",
    ],
  },
  baalcrab: {
    id: "baalcrab",
    nameStr: "Baal Crab",
    levels: [60, 75, 99],
    tcs: [
      "Baal",
      "Baalq",
      "Baal (N)",
      "Baalq (N)",
      "Baal (H)",
      "Baalq (H)",
      "Baal Desecrated",
      "Baal (N) Desecrated",
      "Baal (H) Desecrated",
    ],
  },
  uberandariel: {
    id: "uberandariel",
    nameStr: "Lilith",
    levels: [110, 110, 110],
    tcs: [null, null, null, null, "Uber Andariel", null, null, null, null],
  },
  uberizual: {
    id: "uberizual",
    nameStr: "izual",
    levels: [110, 110, 110],
    tcs: [null, null, null, null, "Uber Izual", null, null, null, null],
  },
  uberduriel: {
    id: "uberduriel",
    nameStr: "Duriel",
    levels: [110, 110, 110],
    tcs: [null, null, null, null, "Uber Duriel", null, null, null, null],
  },
  ubermephisto: {
    id: "ubermephisto",
    nameStr: "Mephisto",
    levels: [110, 110, 110],
    tcs: [null, null, null, null, null, null, null, null, null],
  },
  uberdiablo: {
    id: "uberdiablo",
    nameStr: "Diablo",
    levels: [110, 110, 110],
    tcs: [null, null, null, null, null, null, null, null, null],
  },
  uberbaal: {
    id: "uberbaal",
    nameStr: "Baal Crab",
    levels: [110, 110, 110],
    tcs: [null, null, null, null, null, null, null, null, null],
  },
};
