export type LevelsObj = {
  name: string;
  act: number;
  levels: [number, number, number];
  mon: string[];
  umon: string[];
  nmon: string[];
};

export const levelsDict: { [key: string]: LevelsObj } = {
  "2": {
    name: "Blood Moor",
    act: 1,
    levels: [1, 36, 67],
    mon: ["zombie1", "fallen1", "quillrat1"],
    umon: ["zombie1", "fallen1", "quillrat1"],
    nmon: ["zombie1", "fallen1", "quillrat1"],
  },
  "3": {
    name: "Cold Plains",
    act: 1,
    levels: [2, 36, 68],
    mon: ["brute1", "corruptrogue1", "fallenshaman1", "cr_lancer1"],
    umon: ["brute1", "corruptrogue1", "fallenshaman1", "cr_lancer1"],
    nmon: ["brute1", "corruptrogue1", "fallenshaman1", "cr_lancer1"],
  },
  "4": {
    name: "Stony Field",
    act: 1,
    levels: [4, 37, 68],
    mon: ["skeleton1", "zombie2", "crownest1", "goatman1", "cr_archer1"],
    umon: ["skeleton1", "zombie2", "crownest1", "goatman1", "cr_archer1"],
    nmon: ["skeleton1", "zombie2", "crownest1", "goatman1", "cr_archer1"],
  },
  "5": {
    name: "Dark Wood",
    act: 1,
    levels: [5, 38, 68],
    mon: ["fallen2", "corruptrogue2", "quillrat2", "cr_lancer2", "sk_archer1"],
    umon: ["fallen2", "corruptrogue2", "quillrat2", "cr_lancer2", "sk_archer1"],
    nmon: ["fallen2", "corruptrogue2", "quillrat2", "cr_lancer2", "sk_archer1"],
  },
  "6": {
    name: "Black Marsh",
    act: 1,
    levels: [6, 38, 69],
    mon: [
      "crownest2",
      "skeleton2",
      "brute2",
      "goatman2",
      "fallenshaman2",
      "cr_archer2",
    ],
    umon: [
      "crownest2",
      "skeleton2",
      "brute2",
      "goatman2",
      "fallenshaman2",
      "cr_archer2",
    ],
    nmon: [
      "crownest2",
      "skeleton2",
      "brute2",
      "goatman2",
      "fallenshaman2",
      "cr_archer2",
    ],
  },
  "7": {
    name: "Tamoe Highland",
    act: 1,
    levels: [8, 39, 69],
    mon: [
      "corruptrogue3",
      "quillrat3",
      "cr_lancer3",
      "sk_archer2",
      "skmage_fire1",
    ],
    umon: [
      "corruptrogue3",
      "quillrat3",
      "cr_lancer3",
      "sk_archer2",
      "skmage_fire1",
    ],
    nmon: [
      "corruptrogue3",
      "quillrat3",
      "cr_lancer3",
      "sk_archer2",
      "skmage_fire1",
    ],
  },
  "8": {
    name: "Den of Evil",
    act: 1,
    levels: [1, 36, 79],
    mon: ["zombie1", "brute1", "fallenshaman1"],
    umon: ["zombie1", "brute1", "fallenshaman1"],
    nmon: ["zombie1", "brute1", "fallenshaman1"],
  },
  "9": {
    name: "Cave Level 1",
    act: 1,
    levels: [2, 36, 77],
    mon: ["skeleton1", "zombie2", "cr_archer1"],
    umon: ["skeleton1", "zombie2", "cr_archer1"],
    nmon: ["skeleton1", "zombie2", "cr_archer1"],
  },
  "10": {
    name: "Underground Passage Level 1",
    act: 1,
    levels: [4, 37, 69],
    mon: ["bighead3", "fallen2", "corruptrogue2", "sk_archer1"],
    umon: ["bighead3", "fallen2", "corruptrogue2", "sk_archer1"],
    nmon: ["bighead3", "fallen2", "corruptrogue2", "sk_archer1"],
  },
  "11": {
    name: "Hole Level 1",
    act: 1,
    levels: [5, 38, 80],
    mon: ["bighead3", "fallen2", "brute2", "cr_archer2"],
    umon: ["bighead3", "fallen2", "brute2", "cr_archer2"],
    nmon: ["bighead3", "fallen2", "brute2", "cr_archer2"],
  },
  "12": {
    name: "Pit Level 1",
    act: 1,
    levels: [7, 39, 85],
    mon: ["skeleton3", "fallen3", "corruptrogue3", "cr_archer3"],
    umon: ["skeleton3", "fallen3", "corruptrogue3", "cr_archer3"],
    nmon: ["skeleton3", "fallen3", "corruptrogue3", "cr_archer3"],
  },
  "13": {
    name: "Cave Level 2",
    act: 1,
    levels: [2, 37, 78],
    mon: ["skeleton1", "zombie2", "cr_archer1"],
    umon: ["skeleton1", "zombie2", "cr_archer1"],
    nmon: ["skeleton1", "zombie2", "cr_archer1"],
  },
  "14": {
    name: "Underground Passage Level 2",
    act: 1,
    levels: [4, 38, 85],
    mon: ["bighead3", "fallen2", "corruptrogue2", "sk_archer1"],
    umon: ["bighead3", "fallen2", "corruptrogue2", "sk_archer1"],
    nmon: ["bighead3", "fallen2", "corruptrogue2", "sk_archer1"],
  },
  "15": {
    name: "Hole Level 2",
    act: 1,
    levels: [5, 39, 81],
    mon: ["bighead3", "fallen2", "brute2", "cr_archer2"],
    umon: ["bighead3", "fallen2", "brute2", "cr_archer2"],
    nmon: ["bighead3", "fallen2", "brute2", "cr_archer2"],
  },
  "16": {
    name: "Pit Level 2",
    act: 1,
    levels: [7, 40, 85],
    mon: ["skeleton3", "fallen3", "corruptrogue3", "cr_archer3"],
    umon: ["skeleton3", "fallen3", "corruptrogue3", "cr_archer3"],
    nmon: ["skeleton3", "fallen3", "corruptrogue3", "cr_archer3"],
  },
  "17": {
    name: "Burial Grounds",
    act: 1,
    levels: [3, 36, 80],
    mon: ["skeleton1", "zombie2"],
    umon: ["skeleton1", "zombie2"],
    nmon: ["skeleton1", "zombie2"],
  },
  "18": {
    name: "Crypt",
    act: 1,
    levels: [3, 37, 83],
    mon: ["skeleton1", "zombie2"],
    umon: ["skeleton1", "zombie2"],
    nmon: ["skeleton1", "zombie2"],
  },
  "19": {
    name: "Mausoleum",
    act: 1,
    levels: [3, 37, 85],
    mon: ["skeleton1", "zombie2"],
    umon: ["skeleton1", "zombie2"],
    nmon: ["skeleton1", "zombie2"],
  },
  "21": {
    name: "Tower Cellar Level 1",
    act: 1,
    levels: [7, 38, 75],
    mon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
    umon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
    nmon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
  },
  "22": {
    name: "Tower Cellar Level 2",
    act: 1,
    levels: [7, 39, 76],
    mon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
    umon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
    nmon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
  },
  "23": {
    name: "Tower Cellar Level 3",
    act: 1,
    levels: [7, 40, 77],
    mon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
    umon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
    nmon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
  },
  "24": {
    name: "Tower Cellar Level 4",
    act: 1,
    levels: [7, 41, 78],
    mon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
    umon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
    nmon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
  },
  "25": {
    name: "Tower Cellar Level 5",
    act: 1,
    levels: [7, 42, 79],
    mon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
    umon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
    nmon: ["fallen3", "wraith1", "goatman3", "cr_archer3"],
  },
  "26": {
    name: "Monastery Gate",
    act: 1,
    levels: [8, 40, 70],
    mon: ["bighead4", "corruptrogue3", "sk_archer2", "skmage_ltng1"],
    umon: ["bighead4", "corruptrogue3", "sk_archer2", "skmage_ltng1"],
    nmon: ["bighead4", "corruptrogue3", "sk_archer2", "skmage_ltng1"],
  },
  "27": {
    name: "Outer Cloister",
    act: 1,
    levels: [9, 40, 70],
    mon: ["brute3", "corruptrogue4", "fallenshaman3", "quillrat4"],
    umon: ["brute3", "corruptrogue4", "fallenshaman3", "quillrat4"],
    nmon: ["brute3", "corruptrogue4", "fallenshaman3", "quillrat4"],
  },
  "28": {
    name: "Barracks",
    act: 1,
    levels: [9, 40, 70],
    mon: [
      "corruptrogue4",
      "goatman5",
      "fallenshaman3",
      "sk_archer3",
      "skmage_fire2",
    ],
    umon: [
      "corruptrogue4",
      "goatman5",
      "fallenshaman3",
      "sk_archer3",
      "skmage_fire2",
    ],
    nmon: [
      "corruptrogue4",
      "goatman5",
      "fallenshaman3",
      "sk_archer3",
      "skmage_fire2",
    ],
  },
  "29": {
    name: "Jail Level 1",
    act: 1,
    levels: [10, 41, 71],
    mon: ["fallen4", "wraith2", "goatman5", "sk_archer3", "skmage_fire2"],
    umon: ["fallen4", "wraith2", "goatman5", "sk_archer3", "skmage_fire2"],
    nmon: ["fallen4", "wraith2", "goatman5", "sk_archer3", "skmage_fire2"],
  },
  "30": {
    name: "Jail Level 2",
    act: 1,
    levels: [10, 41, 71],
    mon: ["fallen4", "wraith2", "goatman5", "sk_archer3", "skmage_fire2"],
    umon: ["fallen4", "wraith2", "goatman5", "sk_archer3", "skmage_fire2"],
    nmon: ["fallen4", "wraith2", "goatman5", "sk_archer3", "skmage_fire2"],
  },
  "31": {
    name: "Jail Level 3",
    act: 1,
    levels: [10, 41, 71],
    mon: ["fallen4", "wraith2", "goatman5", "sk_archer3", "skmage_ltng2"],
    umon: ["fallen4", "wraith2", "goatman5", "sk_archer3", "skmage_ltng2"],
    nmon: ["fallen4", "wraith2", "goatman5", "sk_archer3", "skmage_ltng2"],
  },
  "32": {
    name: "Inner Cloister",
    act: 1,
    levels: [10, 41, 72],
    mon: ["fallen4", "cr_archer4", "skmage_ltng2"],
    umon: ["fallen4", "cr_archer4", "skmage_ltng2"],
    nmon: ["fallen4", "cr_archer4", "skmage_ltng2"],
  },
  "33": {
    name: "Cathedral",
    act: 1,
    levels: [11, 42, 72],
    mon: ["bighead2", "wraith2", "fallenshaman4"],
    umon: ["bighead2", "wraith2", "fallenshaman4"],
    nmon: ["bighead2", "wraith2", "fallenshaman4"],
  },
  "34": {
    name: "Catacombs Level 1",
    act: 1,
    levels: [11, 42, 72],
    mon: ["bighead2", "fallenshaman4", "fetish1"],
    umon: ["bighead2", "fallenshaman4", "fetish1"],
    nmon: ["bighead2", "fallenshaman4", "fetish1"],
  },
  "35": {
    name: "Catacombs Level 2",
    act: 1,
    levels: [11, 42, 73],
    mon: ["bighead2", "fallenshaman4", "arach1"],
    umon: ["bighead2", "fallenshaman4", "arach1"],
    nmon: ["bighead2", "fallenshaman4", "arach1"],
  },
  "36": {
    name: "Catacombs Level 3",
    act: 1,
    levels: [12, 43, 73],
    mon: ["zombie3", "bighead1", "vampire5"],
    umon: ["zombie3", "bighead1", "vampire5"],
    nmon: ["zombie3", "bighead1", "vampire5"],
  },
  "37": {
    name: "Catacombs Level 4",
    act: 1,
    levels: [12, 43, 73],
    mon: ["zombie3", "bighead1"],
    umon: ["zombie3", "bighead1"],
    nmon: ["zombie3", "bighead1"],
  },
  "38": {
    name: "Tristram",
    act: 1,
    levels: [6, 39, 76],
    mon: ["skeleton2", "goatman2", "fallenshaman2", "sk_archer1"],
    umon: ["skeleton2", "goatman2", "fallenshaman2", "sk_archer1"],
    nmon: ["skeleton2", "goatman2", "fallenshaman2", "sk_archer1"],
  },
  "39": {
    name: "Moo Moo Farm",
    act: 1,
    levels: [28, 64, 81],
    mon: ["hellbovine", "hellbovine", "hellbovine"],
    umon: ["hellbovine", "hellbovine", "hellbovine"],
    nmon: ["hellbovine", "hellbovine", "hellbovine"],
  },
  "41": {
    name: "Rocky Waste",
    act: 2,
    levels: [14, 43, 75],
    mon: ["sandleaper1", "pantherwoman1", "scarab1", "vulture1", "slinger1"],
    umon: ["sandleaper1", "pantherwoman1", "scarab1", "vulture1", "slinger1"],
    nmon: ["sandleaper1", "pantherwoman1", "scarab1", "vulture1", "slinger1"],
  },
  "42": {
    name: "Dry Hills",
    act: 2,
    levels: [15, 44, 76],
    mon: ["sandleaper2", "pantherwoman2", "vulture2", "slinger5"],
    umon: ["sandleaper2", "pantherwoman2", "vulture2", "slinger5"],
    nmon: ["sandleaper2", "pantherwoman2", "vulture2", "slinger5"],
  },
  "43": {
    name: "Far Oasis",
    act: 2,
    levels: [16, 45, 76],
    mon: ["crownest3", "sandmaggot1", "swarm1", "scarab2", "vulture2"],
    umon: ["crownest3", "sandmaggot1", "swarm1", "scarab2", "vulture2"],
    nmon: ["crownest3", "sandmaggot1", "swarm1", "scarab2", "vulture2"],
  },
  "44": {
    name: "Lost City",
    act: 2,
    levels: [17, 46, 77],
    mon: ["zombie5", "sandraider2", "sandleaper3", "pantherwoman3", "slinger6"],
    umon: [
      "zombie5",
      "sandraider2",
      "sandleaper3",
      "pantherwoman3",
      "slinger6",
    ],
    nmon: [
      "zombie5",
      "sandraider2",
      "sandleaper3",
      "pantherwoman3",
      "slinger6",
    ],
  },
  "45": {
    name: "Valley of Snakes",
    act: 2,
    levels: [18, 46, 77],
    mon: [
      "clawviper2",
      "clawviper2",
      "clawviper3",
      "clawviper3",
      "mummy3",
      "unraveler2",
    ],
    umon: [
      "clawviper2",
      "clawviper2",
      "clawviper3",
      "clawviper3",
      "mummy3",
      "unraveler2",
    ],
    nmon: [
      "clawviper2",
      "clawviper2",
      "clawviper3",
      "clawviper3",
      "mummy3",
      "unraveler2",
    ],
  },
  "46": {
    name: "Canyon of the Magi",
    act: 2,
    levels: [16, 48, 79],
    mon: ["brute4", "sandmaggot3", "pantherwoman4", "scarab4", "slinger4"],
    umon: ["brute4", "sandmaggot3", "pantherwoman4", "scarab4", "slinger4"],
    nmon: ["brute4", "sandmaggot3", "pantherwoman4", "scarab4", "slinger4"],
  },
  "47": {
    name: "Sewers Level 1",
    act: 2,
    levels: [13, 43, 74],
    mon: ["skeleton4", "sandraider1", "mummy1", "sk_archer4"],
    umon: ["skeleton4", "sandraider1", "mummy1", "sk_archer4"],
    nmon: ["skeleton4", "sandraider1", "mummy1", "sk_archer4"],
  },
  "48": {
    name: "Sewers Level 2",
    act: 2,
    levels: [13, 43, 74],
    mon: ["skeleton4", "sandraider1", "mummy1", "sk_archer4"],
    umon: ["skeleton4", "sandraider1", "mummy1", "sk_archer4"],
    nmon: ["skeleton4", "sandraider1", "mummy1", "sk_archer4"],
  },
  "49": {
    name: "Sewers Level 3",
    act: 2,
    levels: [14, 44, 75],
    mon: ["skeleton4", "pantherwoman1", "mummy1", "skmage_fire3"],
    umon: ["skeleton4", "pantherwoman1", "mummy1", "skmage_fire3"],
    nmon: ["skeleton4", "pantherwoman1", "mummy1", "skmage_fire3"],
  },
  "51": {
    name: "Harem Level 2",
    act: 2,
    levels: [13, 47, 78],
    mon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_cold4",
    ],
    umon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_cold4",
    ],
    nmon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_cold4",
    ],
  },
  "52": {
    name: "Palace Cellar Level 1",
    act: 2,
    levels: [13, 47, 78],
    mon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_fire4",
    ],
    umon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_fire4",
    ],
    nmon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_fire4",
    ],
  },
  "53": {
    name: "Palace Cellar Level 2",
    act: 2,
    levels: [13, 47, 78],
    mon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_pois4",
    ],
    umon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_pois4",
    ],
    nmon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_pois4",
    ],
  },
  "54": {
    name: "Palace Cellar Level 3",
    act: 2,
    levels: [13, 48, 78],
    mon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_ltng4",
    ],
    umon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_ltng4",
    ],
    nmon: [
      "sandraider3",
      "baboon1",
      "sk_archer5",
      "blunderbore1",
      "skmage_ltng4",
    ],
  },
  "55": {
    name: "Stony Tomb Level 1",
    act: 2,
    levels: [12, 44, 85],
    mon: ["skeleton5", "scarab1", "skmage_ltng3"],
    umon: ["skeleton5", "scarab1", "skmage_ltng3"],
    nmon: ["skeleton5", "scarab1", "skmage_ltng3"],
  },
  "56": {
    name: "Halls of the Dead Level 1",
    act: 2,
    levels: [12, 44, 79],
    mon: ["mummy2", "unraveler1", "unraveler1", "batdemon1", "slinger2"],
    umon: ["mummy2", "unraveler1", "unraveler1", "batdemon1", "slinger2"],
    nmon: ["mummy2", "unraveler1", "unraveler1", "batdemon1", "slinger2"],
  },
  "57": {
    name: "Halls of the Dead Level 2",
    act: 2,
    levels: [13, 45, 81],
    mon: ["mummy2", "unraveler1", "unraveler1", "batdemon1", "slinger2"],
    umon: ["mummy2", "unraveler1", "unraveler1", "batdemon1", "slinger2"],
    nmon: ["mummy2", "unraveler1", "unraveler1", "batdemon1", "slinger2"],
  },
  "58": {
    name: "Claw Viper Temple Level 1",
    act: 2,
    levels: [14, 47, 82],
    mon: [
      "clawviper2",
      "clawviper2",
      "clawviper3",
      "clawviper3",
      "mummy3",
      "unraveler2",
    ],
    umon: [
      "clawviper2",
      "clawviper2",
      "clawviper3",
      "clawviper3",
      "mummy3",
      "unraveler2",
    ],
    nmon: [
      "clawviper2",
      "clawviper2",
      "clawviper3",
      "clawviper3",
      "mummy3",
      "unraveler2",
    ],
  },
  "59": {
    name: "Stony Tomb Level 2",
    act: 2,
    levels: [12, 44, 85],
    mon: ["skeleton5", "scarab1", "skmage_pois3"],
    umon: ["skeleton5", "scarab1", "skmage_pois3"],
    nmon: ["skeleton5", "scarab1", "skmage_pois3"],
  },
  "60": {
    name: "Halls of the Dead Level 3",
    act: 2,
    levels: [13, 45, 82],
    mon: ["mummy2", "unraveler1", "unraveler1", "batdemon1", "slinger2"],
    umon: ["mummy2", "unraveler1", "unraveler1", "batdemon1", "slinger2"],
    nmon: ["mummy2", "unraveler1", "unraveler1", "batdemon1", "slinger2"],
  },
  "61": {
    name: "Claw Viper Temple Level 2",
    act: 2,
    levels: [14, 47, 83],
    mon: [
      "clawviper2",
      "clawviper2",
      "clawviper3",
      "clawviper3",
      "mummy3",
      "unraveler2",
    ],
    umon: [
      "clawviper2",
      "clawviper2",
      "clawviper3",
      "clawviper3",
      "mummy3",
      "unraveler2",
    ],
    nmon: [
      "clawviper2",
      "clawviper2",
      "clawviper3",
      "clawviper3",
      "mummy3",
      "unraveler2",
    ],
  },
  "62": {
    name: "Maggot Lair Level 1",
    act: 2,
    levels: [17, 45, 84],
    mon: ["sandmaggot1", "sandmaggot2", "swarm2", "scarab2", "scarab3"],
    umon: ["sandmaggot1", "sandmaggot2", "swarm2", "scarab2", "scarab3"],
    nmon: ["sandmaggot1", "sandmaggot2", "swarm2", "scarab2", "scarab3"],
  },
  "63": {
    name: "Maggot Lair Level 2",
    act: 2,
    levels: [17, 45, 84],
    mon: ["sandmaggot1", "sandmaggot2", "swarm2", "scarab2", "scarab3"],
    umon: ["sandmaggot1", "sandmaggot2", "swarm2", "scarab2", "scarab3"],
    nmon: ["sandmaggot1", "sandmaggot2", "swarm2", "scarab2", "scarab3"],
  },
  "64": {
    name: "Maggot Lair Level 3",
    act: 2,
    levels: [17, 46, 85],
    mon: ["sandmaggot1", "sandmaggot2", "swarm2", "scarab2", "scarab3"],
    umon: ["sandmaggot1", "sandmaggot2", "swarm2", "scarab2", "scarab3"],
    nmon: ["sandmaggot1", "sandmaggot2", "swarm2", "scarab2", "scarab3"],
  },
  "65": {
    name: "Ancient Tunnels",
    act: 2,
    levels: [17, 46, 85],
    mon: ["zombie5", "sandraider3", "mummy3", "skmage_ltng4"],
    umon: ["zombie5", "sandraider3", "mummy3", "skmage_ltng4"],
    nmon: ["zombie5", "sandraider3", "mummy3", "skmage_ltng4"],
  },
  "66": {
    name: "Tal Rasha's Tomb",
    act: 2,
    levels: [17, 49, 80],
    mon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    umon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    nmon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
  },
  "67": {
    name: "Tal Rasha's Tomb",
    act: 2,
    levels: [17, 49, 80],
    mon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    umon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    nmon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
  },
  "68": {
    name: "Tal Rasha's Tomb",
    act: 2,
    levels: [17, 49, 80],
    mon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    umon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    nmon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
  },
  "69": {
    name: "Tal Rasha's Tomb",
    act: 2,
    levels: [17, 49, 80],
    mon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    umon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    nmon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
  },
  "70": {
    name: "Tal Rasha's Tomb",
    act: 2,
    levels: [17, 49, 80],
    mon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    umon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    nmon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
  },
  "71": {
    name: "Tal Rasha's Tomb",
    act: 2,
    levels: [17, 49, 80],
    mon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    umon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    nmon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
  },
  "72": {
    name: "Tal Rasha's Tomb",
    act: 2,
    levels: [17, 49, 80],
    mon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    umon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    nmon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
  },
  "73": {
    name: "Duriel's Lair",
    act: 2,
    levels: [17, 49, 80],
    mon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    umon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
    nmon: [
      "wraith4",
      "scarab4",
      "mummy4",
      "unraveler3",
      "unraveler3",
      "vampire1",
      "blunderbore2",
    ],
  },
  "74": {
    name: "Arcane Sanctuary",
    act: 2,
    levels: [14, 48, 79],
    mon: ["wraith3", "goatman4", "vampire1"],
    umon: ["wraith3", "goatman4", "vampire1"],
    nmon: ["wraith3", "goatman4", "vampire1"],
  },
  "76": {
    name: "Spider Forest",
    act: 3,
    levels: [21, 49, 79],
    mon: [
      "baboon3",
      "mosquito1",
      "thornhulk1",
      "fetish2",
      "fetishblow2",
      "foulcrow4",
    ],
    umon: [
      "baboon3",
      "mosquito1",
      "thornhulk1",
      "fetish2",
      "fetishblow2",
      "foulcrow4",
    ],
    nmon: [
      "baboon3",
      "mosquito1",
      "thornhulk1",
      "fetish2",
      "fetishblow2",
      "foulcrow4",
    ],
  },
  "77": {
    name: "Great Marsh",
    act: 3,
    levels: [21, 50, 80],
    mon: [
      "frogdemon1",
      "frogdemon2",
      "thornhulk2",
      "zombie4",
      "fetishshaman2",
      "willowisp1",
    ],
    umon: [
      "frogdemon1",
      "frogdemon2",
      "thornhulk2",
      "zombie4",
      "fetishshaman2",
      "willowisp1",
    ],
    nmon: [
      "frogdemon1",
      "frogdemon2",
      "thornhulk2",
      "zombie4",
      "fetishshaman2",
      "willowisp1",
    ],
  },
  "78": {
    name: "Flayer Jungle",
    act: 3,
    levels: [22, 50, 80],
    mon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "vulture4",
      "frogdemon3",
      "fetishblow3",
    ],
    umon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "vulture4",
      "frogdemon3",
      "fetishblow3",
    ],
    nmon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "vulture4",
      "frogdemon3",
      "fetishblow3",
    ],
  },
  "79": {
    name: "Lower Kurast",
    act: 3,
    levels: [22, 52, 80],
    mon: ["baboon4", "sandleaper4", "vulture3", "zealot1"],
    umon: ["baboon4", "sandleaper4", "vulture3", "zealot1"],
    nmon: ["baboon4", "sandleaper4", "vulture3", "zealot1"],
  },
  "80": {
    name: "Kurast Bazaar",
    act: 3,
    levels: [22, 52, 81],
    mon: ["thornhulk3", "swarm4", "zealot2", "cantor1"],
    umon: ["thornhulk3", "swarm4", "zealot2", "cantor1"],
    nmon: ["thornhulk3", "swarm4", "zealot2", "cantor1"],
  },
  "81": {
    name: "Upper Kurast",
    act: 3,
    levels: [23, 52, 81],
    mon: ["vulture4", "zealot3", "cantor2", "thornhulk3"],
    umon: ["vulture4", "zealot3", "cantor2", "thornhulk3"],
    nmon: ["vulture4", "zealot3", "cantor2", "thornhulk3"],
  },
  "82": {
    name: "Kurast Causeway",
    act: 3,
    levels: [24, 53, 81],
    mon: ["sandraider4", "baboon5", "cantor3"],
    umon: ["sandraider4", "baboon5", "cantor3"],
    nmon: ["sandraider4", "baboon5", "cantor3"],
  },
  "83": {
    name: "Travincal",
    act: 3,
    levels: [24, 54, 82],
    mon: ["cantor3", "cantor3", "vampire2"],
    umon: ["cantor3", "cantor3", "vampire2"],
    nmon: ["cantor3", "cantor3", "vampire2"],
  },
  "84": {
    name: "Arachnid Lair",
    act: 3,
    levels: [21, 50, 85],
    mon: ["arach3", "arach4", "batdemon2", "sandmaggot4", "arach3"],
    umon: ["arach3", "arach4", "batdemon2", "sandmaggot4", "arach3"],
    nmon: ["arach3", "arach4", "batdemon2", "sandmaggot4", "arach3"],
  },
  "85": {
    name: "Spider Cavern",
    act: 3,
    levels: [21, 50, 79],
    mon: ["arach3", "arach4", "batdemon2", "sandmaggot4", "arach3"],
    umon: ["arach3", "arach4", "batdemon2", "sandmaggot4", "arach3"],
    nmon: ["arach3", "arach4", "batdemon2", "sandmaggot4", "arach3"],
  },
  "86": {
    name: "Swampy Pit Level 1",
    act: 3,
    levels: [21, 51, 85],
    mon: ["mummy4", "bonefetish4", "batdemon2", "willowisp1", "bonefetish5"],
    umon: ["mummy4", "bonefetish4", "batdemon2", "willowisp1", "bonefetish5"],
    nmon: ["mummy4", "bonefetish4", "batdemon2", "willowisp1", "bonefetish5"],
  },
  "87": {
    name: "Swampy Pit Level 2",
    act: 3,
    levels: [21, 51, 85],
    mon: ["bonefetish4", "zombie4", "batdemon2", "willowisp1", "bonefetish5"],
    umon: ["bonefetish4", "zombie4", "batdemon2", "willowisp1", "bonefetish5"],
    nmon: ["bonefetish4", "zombie4", "batdemon2", "willowisp1", "bonefetish5"],
  },
  "88": {
    name: "Flayer Dungeon Level 1",
    act: 3,
    levels: [22, 51, 81],
    mon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "batdemon3",
      "wraith5",
      "fetishblow3",
      "bonefetish3",
    ],
    umon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "batdemon3",
      "wraith5",
      "fetishblow3",
      "bonefetish3",
    ],
    nmon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "batdemon3",
      "wraith5",
      "fetishblow3",
      "bonefetish3",
    ],
  },
  "89": {
    name: "Flayer Dungeon Level 2",
    act: 3,
    levels: [22, 51, 82],
    mon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "batdemon3",
      "wraith5",
      "fetishblow3",
      "bonefetish3",
    ],
    umon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "batdemon3",
      "wraith5",
      "fetishblow3",
      "bonefetish3",
    ],
    nmon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "batdemon3",
      "wraith5",
      "fetishblow3",
      "bonefetish3",
    ],
  },
  "90": {
    name: "Swampy Pit Level 3",
    act: 3,
    levels: [21, 51, 85],
    mon: ["bonefetish4", "bonefetish5", "batdemon2", "willowisp1"],
    umon: ["bonefetish4", "bonefetish5", "batdemon2", "willowisp1"],
    nmon: ["bonefetish4", "bonefetish5", "batdemon2", "willowisp1"],
  },
  "91": {
    name: "Flayer Dungeon Level 3",
    act: 3,
    levels: [22, 51, 83],
    mon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "batdemon3",
      "wraith5",
      "fetishblow3",
      "bonefetish3",
    ],
    umon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "batdemon3",
      "wraith5",
      "fetishblow3",
      "bonefetish3",
    ],
    nmon: [
      "fetish3",
      "fetishshaman3",
      "fetish4",
      "fetishshaman4",
      "batdemon3",
      "wraith5",
      "fetishblow3",
      "bonefetish3",
    ],
  },
  "92": {
    name: "Sewers Level 1",
    act: 3,
    levels: [23, 52, 85],
    mon: ["mummy4", "mosquito2", "batdemon3", "unraveler4", "bonefetish4"],
    umon: ["mummy4", "mosquito2", "batdemon3", "unraveler4", "bonefetish4"],
    nmon: ["mummy4", "mosquito2", "batdemon3", "unraveler4", "bonefetish4"],
  },
  "93": {
    name: "Sewers Level 2",
    act: 3,
    levels: [24, 53, 85],
    mon: ["mummy4", "unraveler4", "mosquito4", "frogdemon3", "bonefetish4"],
    umon: ["mummy4", "unraveler4", "mosquito4", "frogdemon3", "bonefetish4"],
    nmon: ["mummy4", "unraveler4", "mosquito4", "frogdemon3", "bonefetish4"],
  },
  "94": {
    name: "Ruined Temple",
    act: 3,
    levels: [23, 53, 85],
    mon: ["brute5", "corruptrogue5", "arach5", "vampire2"],
    umon: ["brute5", "corruptrogue5", "arach5", "vampire2"],
    nmon: ["brute5", "corruptrogue5", "arach5", "vampire2"],
  },
  "95": {
    name: "Disused Fane",
    act: 3,
    levels: [23, 53, 85],
    mon: ["brute5", "corruptrogue5", "arach5", "vampire2"],
    umon: ["brute5", "corruptrogue5", "arach5", "vampire2"],
    nmon: ["brute5", "corruptrogue5", "arach5", "vampire2"],
  },
  "96": {
    name: "Forgotten Reliquary",
    act: 3,
    levels: [23, 53, 85],
    mon: ["brute5", "corruptrogue5", "arach5", "vampire2"],
    umon: ["brute5", "corruptrogue5", "arach5", "vampire2"],
    nmon: ["brute5", "corruptrogue5", "arach5", "vampire2"],
  },
  "97": {
    name: "Forgotten Temple",
    act: 3,
    levels: [24, 54, 85],
    mon: ["clawviper5", "scarab5", "batdemon4", "cr_archer5"],
    umon: ["clawviper5", "scarab5", "batdemon4", "cr_archer5"],
    nmon: ["clawviper5", "scarab5", "batdemon4", "cr_archer5"],
  },
  "98": {
    name: "Ruined Fane",
    act: 3,
    levels: [24, 54, 85],
    mon: ["clawviper5", "scarab5", "batdemon4", "cr_archer5"],
    umon: ["clawviper5", "scarab5", "batdemon4", "cr_archer5"],
    nmon: ["clawviper5", "scarab5", "batdemon4", "cr_archer5"],
  },
  "99": {
    name: "Disused Reliquary",
    act: 3,
    levels: [24, 54, 85],
    mon: ["clawviper5", "scarab5", "batdemon4", "cr_archer5"],
    umon: ["clawviper5", "scarab5", "batdemon4", "cr_archer5"],
    nmon: ["clawviper5", "scarab5", "batdemon4", "cr_archer5"],
  },
  "100": {
    name: "Durance of Hate Level 1",
    act: 3,
    levels: [25, 55, 83],
    mon: ["mummy5", "vampire3", "blunderbore3", "bonefetish5"],
    umon: ["mummy5", "vampire3", "blunderbore3", "bonefetish5"],
    nmon: ["mummy5", "vampire3", "blunderbore3", "bonefetish5"],
  },
  "101": {
    name: "Durance of Hate Level 2",
    act: 3,
    levels: [25, 55, 83],
    mon: ["mummy5", "vampire3", "blunderbore3", "bonefetish5"],
    umon: ["mummy5", "vampire3", "blunderbore3", "bonefetish5"],
    nmon: ["mummy5", "vampire3", "blunderbore3", "bonefetish5"],
  },
  "102": {
    name: "Durance of Hate Level 3",
    act: 3,
    levels: [25, 55, 83],
    mon: ["vampire4", "vampire4"],
    umon: ["vampire4", "vampire4"],
    nmon: ["vampire4", "vampire4"],
  },
  "104": {
    name: "Outer Steppes",
    act: 4,
    levels: [26, 56, 82],
    mon: [
      "sandleaper5",
      "vilemother1",
      "fingermage1",
      "regurgitator1",
      "doomknight1",
      "megademon3",
    ],
    umon: [
      "sandleaper5",
      "vilemother1",
      "fingermage1",
      "regurgitator1",
      "doomknight1",
      "megademon3",
    ],
    nmon: [
      "sandleaper5",
      "vilemother1",
      "fingermage1",
      "regurgitator1",
      "doomknight1",
      "megademon3",
    ],
  },
  "105": {
    name: "Plains of Despair",
    act: 4,
    levels: [26, 56, 83],
    mon: [
      "willowisp3",
      "vilemother1",
      "fingermage1",
      "regurgitator1",
      "doomknight1",
      "megademon3",
    ],
    umon: [
      "willowisp3",
      "vilemother1",
      "fingermage1",
      "regurgitator1",
      "doomknight1",
      "megademon3",
    ],
    nmon: [
      "willowisp3",
      "vilemother1",
      "fingermage1",
      "regurgitator1",
      "doomknight1",
      "megademon3",
    ],
  },
  "106": {
    name: "City of the Damned",
    act: 4,
    levels: [27, 57, 84],
    mon: [
      "bighead5",
      "batdemon5",
      "vilemother2",
      "fingermage2",
      "regurgitator2",
      "doomknight2",
      "megademon2",
    ],
    umon: [
      "bighead5",
      "batdemon5",
      "vilemother2",
      "fingermage2",
      "regurgitator2",
      "doomknight2",
      "megademon2",
    ],
    nmon: [
      "bighead5",
      "batdemon5",
      "vilemother2",
      "fingermage2",
      "regurgitator2",
      "doomknight2",
      "megademon2",
    ],
  },
  "107": {
    name: "River of Flame",
    act: 4,
    levels: [27, 57, 85],
    mon: [
      "sandmaggot5",
      "blunderbore4",
      "vilemother3",
      "fingermage2",
      "regurgitator3",
      "doomknight2",
      "megademon2",
    ],
    umon: [
      "sandmaggot5",
      "blunderbore4",
      "vilemother3",
      "fingermage2",
      "regurgitator3",
      "doomknight2",
      "megademon2",
    ],
    nmon: [
      "sandmaggot5",
      "blunderbore4",
      "vilemother3",
      "fingermage2",
      "regurgitator3",
      "doomknight2",
      "megademon2",
    ],
  },
  "108": {
    name: "The Chaos Sanctuary",
    act: 4,
    levels: [28, 58, 85],
    mon: ["fingermage3", "doomknight3", "megademon3"],
    umon: ["fingermage3", "doomknight3", "megademon3"],
    nmon: ["fingermage3", "doomknight3", "megademon3"],
  },
  "110": {
    name: "Bloody Foothills",
    act: 5,
    levels: [24, 58, 80],
    mon: [
      "minion1",
      "deathmauler1",
      "overseer1",
      "imp1",
      "sk_archer6",
      "quillrat6",
      "bighead6",
    ],
    umon: [
      "minion1",
      "deathmauler1",
      "overseer1",
      "imp1",
      "sk_archer6",
      "quillrat6",
      "bighead6",
    ],
    nmon: [
      "minion1",
      "deathmauler1",
      "overseer1",
      "imp1",
      "sk_archer6",
      "quillrat6",
      "foulcrow5",
      "vulture5",
      "thornhulk5",
      "slinger7",
    ],
  },
  "111": {
    name: "Frigid Highlands",
    act: 5,
    levels: [25, 59, 81],
    mon: ["imp1", "siegebeast2"],
    umon: ["imp1", "siegebeast2"],
    nmon: [
      "imp3",
      "siegebeast1",
      "minion2",
      "deathmauler2",
      "sk_archer6",
      "cr_archer6",
      "cr_lancer6",
      "slinger8",
      "blunderbore5",
      "overseer2",
    ],
  },
  "112": {
    name: "Arreat Plateau",
    act: 5,
    levels: [26, 60, 81],
    mon: ["overseer2", "minion2"],
    umon: ["overseer2", "minion2"],
    nmon: [
      "deathmauler3",
      "minion4",
      "siegebeast3",
      "overseer5",
      "imp3",
      "slinger9",
      "skmage_ltng5",
      "skmage_fire5",
      "goatman7",
      "fallenshaman6",
    ],
  },
  "113": {
    name: "Crystalline Passage",
    act: 5,
    levels: [29, 61, 82],
    mon: ["frozenhorror1", "succubus3", "bloodlord1"],
    umon: ["frozenhorror1", "succubus3", "bloodlord1"],
    nmon: [
      "snowyeti1",
      "frozenhorror1",
      "succubus1",
      "bloodlord3",
      "sandraider7",
      "sandleaper6",
      "skmage_cold5",
      "cr_archer7",
      "wraith6",
      "clawviper6",
    ],
  },
  "114": {
    name: "Frozen River",
    act: 5,
    levels: [29, 61, 83],
    mon: ["snowyeti2", "succubus5", "reanimatedhorde1"],
    umon: ["snowyeti2", "succubus5", "reanimatedhorde1"],
    nmon: [
      "snowyeti1",
      "frozenhorror1",
      "succubus6",
      "reanimatedhorde1",
      "succubuswitch6",
      "willowisp5",
      "skmage_cold5",
      "cr_lancer7",
      "wraith6",
      "clawviper6",
    ],
  },
  "115": {
    name: "Glacial Trail",
    act: 5,
    levels: [29, 61, 83],
    mon: ["deathmauler3", "reanimatedhorde2", "frozenhorror2"],
    umon: ["deathmauler3", "reanimatedhorde2", "frozenhorror2"],
    nmon: [
      "snowyeti1",
      "frozenhorror1",
      "reanimatedhorde1",
      "skeleton6",
      "wraith7",
      "batdemon6",
      "skmage_cold5",
      "bloodlord6",
      "skeleton6",
      "clawviper7",
    ],
  },
  "116": {
    name: "Drifter Cavern",
    act: 5,
    levels: [29, 61, 85],
    mon: ["snowyeti1", "succubus2"],
    umon: ["snowyeti1", "succubus2"],
    nmon: [
      "snowyeti2",
      "succubus6",
      "frozenhorror2",
      "bighead6",
      "goatman7",
      "cr_archer7",
      "skmage_cold5",
      "wraith6",
      "bloodlord6",
      "sandraider7",
    ],
  },
  "117": {
    name: "Frozen Tundra",
    act: 5,
    levels: [27, 60, 81],
    mon: ["siegebeast2", "imp4"],
    umon: ["siegebeast2", "imp4"],
    nmon: [
      "siegebeast2",
      "imp2",
      "deathmauler4",
      "minion5",
      "succubus5",
      "sk_archer7",
      "vulture5",
      "skmage_ltng5",
      "goatman10",
      "pantherwoman6",
    ],
  },
  "118": {
    name: "The Ancients' Way",
    act: 5,
    levels: [29, 62, 82],
    mon: ["frozenhorror3", "deathmauler3", "bloodlord1"],
    umon: ["frozenhorror3", "deathmauler3", "bloodlord1"],
    nmon: [
      "frozenhorror2",
      "snowyeti2",
      "bloodlord7",
      "fallenshaman6",
      "quillrat7",
      "cr_lancer7",
      "skmage_cold5",
      "cr_lancer7",
      "reanimatedhorde2",
      "bighead6",
    ],
  },
  "119": {
    name: "Icy Cellar",
    act: 5,
    levels: [29, 62, 85],
    mon: ["snowyeti4", "succubus3", "reanimatedhorde3"],
    umon: ["snowyeti4", "succubus3", "reanimatedhorde3"],
    nmon: [
      "snowyeti2",
      "succubus4",
      "bloodlord7",
      "frozenhorror2",
      "clawviper7",
      "bonefetish5",
      "willowisp5",
      "batdemon6",
      "wraith6",
      "succubuswitch6",
    ],
  },
  "120": {
    name: "Arreat Summit",
    act: 5,
    levels: [37, 68, 87],
    mon: ["ancientbarb1", "ancientbarb2", "ancientbarb3"],
    umon: ["ancientbarb1", "ancientbarb2", "ancientbarb3"],
    nmon: ["ancientbarb1", "ancientbarb2", "ancientbarb3"],
  },
  "122": {
    name: "Halls of Anguish",
    act: 5,
    levels: [33, 63, 83],
    mon: ["reanimatedhorde3", "bloodlord2"],
    umon: ["reanimatedhorde3", "bloodlord2"],
    nmon: [
      "reanimatedhorde3",
      "bloodlord2",
      "deathmauler5",
      "skeleton7",
      "sandleaper7",
      "fallenshaman7",
      "scarab6",
      "fetish6",
      "skmage_pois5",
      "baboon7",
    ],
  },
  "123": {
    name: "Halls of Pain",
    act: 5,
    levels: [34, 64, 84],
    mon: ["reanimatedhorde4", "deathmauler2", "putriddefiler1"],
    umon: ["reanimatedhorde4", "deathmauler2", "putriddefiler1"],
    nmon: [
      "bloodlord2",
      "sandraider7",
      "baboon8",
      "goatman9",
      "quillrat8",
      "unraveler6",
      "fetishblow6",
      "cantor5",
      "vilemother4",
      "sandmaggot6",
    ],
  },
  "124": {
    name: "Halls of Vaught",
    act: 5,
    levels: [36, 64, 84],
    mon: ["minion6", "succubus4", "putriddefiler2"],
    umon: ["minion6", "succubus4", "putriddefiler2"],
    nmon: [
      "minion9",
      "succubus4",
      "putriddefiler2",
      "reanimatedhorde3",
      "wraith6",
      "arach6",
      "sk_archer9",
      "fetishshaman6",
      "baboon6",
      "clawviper9",
    ],
  },
  "125": {
    name: "Abaddon",
    act: 5,
    levels: [39, 60, 85],
    mon: ["bloodlord3", "imp2"],
    umon: ["bloodlord3", "imp2"],
    nmon: [
      "bloodlord3",
      "imp6",
      "megademon4",
      "succubus7",
      "succubuswitch7",
      "fallenshaman8",
      "sk_archer10",
      "bonefetish6",
      "fingermage4",
      "minion10",
    ],
  },
  "126": {
    name: "Pit of Acheron",
    act: 5,
    levels: [39, 61, 85],
    mon: ["bloodlord2", "overseer3"],
    umon: ["bloodlord2", "overseer3"],
    nmon: [
      "bloodlord3",
      "imp6",
      "megademon4",
      "succubus7",
      "clawviper8",
      "blunderbore6",
      "unraveler7",
      "skmage_fire6",
      "goatman8",
      "regurgitator4",
    ],
  },
  "127": {
    name: "Infernal Pit",
    act: 5,
    levels: [39, 62, 85],
    mon: ["imp4", "overseer4"],
    umon: ["imp4", "overseer4"],
    nmon: [
      "imp7",
      "overseer4",
      "megademon4",
      "clawviper8",
      "bloodlord2",
      "succubuswitch5",
      "vampire6",
      "fetishblow7",
      "reanimatedhorde6",
      "dkmag1",
    ],
  },
  "128": {
    name: "The Worldstone Keep Level 1",
    act: 5,
    levels: [39, 65, 85],
    mon: ["reanimatedhorde5", "succubuswitch2", "putriddefiler3"],
    umon: ["reanimatedhorde5", "succubuswitch2", "putriddefiler3"],
    nmon: [
      "reanimatedhorde6",
      "succubuswitch8",
      "putriddefiler3",
      "sandraider9",
      "bloodlord5",
      "cr_lancer8",
      "vilemother5",
      "cantor6",
      "vampire7",
      "fetishshaman8",
    ],
  },
  "129": {
    name: "The Worldstone Keep Level 2",
    act: 5,
    levels: [40, 65, 85],
    mon: ["suicideminion6", "minion7"],
    umon: ["suicideminion6", "minion7"],
    nmon: [
      "suicideminion6",
      "minion11",
      "fetish8",
      "batdemon7",
      "clawviper10",
      "mummy6",
      "skmage_pois6",
      "unraveler8",
      "scarab7",
      "willowisp6",
    ],
  },
  "130": {
    name: "The Worldstone Keep Level 3",
    act: 5,
    levels: [42, 66, 85],
    mon: ["bloodlord5", "imp5", "putriddefiler4"],
    umon: ["bloodlord5", "imp5", "putriddefiler4"],
    nmon: [
      "bloodlord5",
      "imp5",
      "putriddefiler4",
      "fingermage5",
      "dkmag2",
      "fetishblow8",
      "skmage_ltng6",
      "wraith8",
      "succubus4",
      "overseer4",
    ],
  },
  "131": {
    name: "Throne of Destruction",
    act: 5,
    levels: [43, 66, 85],
    mon: ["bloodlord5", "succubuswitch3"],
    umon: ["bloodlord5", "succubuswitch3"],
    nmon: [
      "bloodlord5",
      "succubuswitch5",
      "bonefetish7",
      "sandraider10",
      "willowisp7",
      "vampire8",
      "megademon5",
      "unraveler9",
      "dkmag2",
      "clawviper10",
    ],
  },
  "133": {
    name: "Matron's Den",
    act: 5,
    levels: [50, 75, 83],
    mon: [
      "succubus8",
      "succubuswitch9",
      "corruptrogue6",
      "cr_archer8",
      "cr_lancer8",
    ],
    umon: [
      "succubus8",
      "succubuswitch9",
      "corruptrogue6",
      "cr_archer8",
      "cr_lancer8",
    ],
    nmon: [
      "succubus8",
      "succubuswitch9",
      "corruptrogue6",
      "cr_archer8",
      "cr_lancer8",
    ],
  },
  "134": {
    name: "Forgotten Sands",
    act: 5,
    levels: [50, 75, 83],
    mon: ["swarm5", "sandmaggot7", "arach7", "scarab8"],
    umon: ["swarm5", "sandmaggot7", "arach7", "scarab8"],
    nmon: ["swarm5", "sandmaggot7", "arach7", "scarab8"],
  },
  "135": {
    name: "Furnace of Pain",
    act: 5,
    levels: [50, 75, 83],
    mon: ["overseer6", "dkmag3", "megademon6", "imp8"],
    umon: ["overseer6", "dkmag3", "megademon6", "imp8"],
    nmon: ["overseer6", "dkmag3", "megademon6", "imp8"],
  },
};
