export type SuperUniqueEntry = {
  id: string;
  tcs: [string, string, string];
  grp: [number, number];
  areaId: number;
};

// Dropped Ancients (no loot)
export const SuperuniqueDict: { [key: string]: SuperUniqueEntry } = {
  "Baal Subject 1": {
    id: "Baal Subject 1",
    tcs: ["Act 5 Champ C", "Act 5 (N) Champ C", "Act 5 (H) Champ C"],
    grp: [5, 5],
    areaId: 131,
  },
  "Baal Subject 2": {
    id: "Baal Subject 2",
    tcs: ["Act 5 Champ C", "Act 5 (N) Champ C", "Act 5 (H) Champ C"],
    grp: [3, 3],
    areaId: 131,
  },
  "Baal Subject 3": {
    id: "Baal Subject 3",
    tcs: ["Act 5 Champ C", "Act 5 (N) Champ C", "Act 5 (H) Champ C"],
    grp: [5, 5],
    areaId: 131,
  },
  "Baal Subject 4": {
    id: "Baal Subject 4",
    tcs: ["Act 5 Champ C", "Act 5 (N) Champ C", "Act 5 (H) Champ C"],
    grp: [8, 8],
    areaId: 131,
  },
  "Baal Subject 5": {
    id: "Baal Subject 5",
    tcs: ["Act 5 Champ C", "Act 5 (N) Champ C", "Act 5 (H) Champ C"],
    grp: [5, 5],
    areaId: 131,
  },
  Beetleburst: {
    id: "Beetleburst",
    tcs: ["Act 2 Super B", "Act 2 (N) Super B", "Act 2 (H) Super B"],
    grp: [3, 3],
    areaId: 43,
  },
  Bishibosh: {
    id: "Bishibosh",
    tcs: ["Act 1 Super A", "Act 1 (N) Super A", "Act 1 (H) Super A"],
    grp: [2, 2],
    areaId: 3,
  },
  "Bloodwitch the Wild": {
    id: "Bloodwitch the Wild",
    tcs: ["Act 2 Super A", "Act 2 (N) Super A", "Act 2 (H) Super A"],
    grp: [5, 5],
    areaId: 60,
  },
  Boneash: {
    id: "Boneash",
    tcs: ["Act 1 Super C", "Act 1 (N) Super C", "Act 1 (H) Super C"],
    grp: [0, 0],
    areaId: 33,
  },
  Bonebreak: {
    id: "Bonebreak",
    tcs: ["Act 1 Super A", "Act 1 (N) Super A", "Act 1 (H) Super A"],
    grp: [5, 5],
    areaId: 18,
  },
  "Bonesaw Breaker": {
    id: "Bonesaw Breaker",
    tcs: ["Act 5 Super A", "Act 5 (N) Super A", "Act 5 (H) Super A"],
    grp: [5, 5],
    areaId: 115,
  },
  "Bremm Sparkfist": {
    id: "Bremm Sparkfist",
    tcs: ["Council", "Council (N)", "Council (H)"],
    grp: [2, 2],
    areaId: 102,
  },
  Coldcrow: {
    id: "Coldcrow",
    tcs: ["Act 1 Super A", "Act 1 (N) Super A", "Act 1 (H) Super A"],
    grp: [4, 4],
    areaId: 9,
  },
  "Coldworm the Burrower": {
    id: "Coldworm the Burrower",
    tcs: ["Act 2 Super B", "Act 2 (N) Super B", "Act 2 (H) Super B"],
    grp: [0, 0],
    areaId: 64,
  },
  Corpsefire: {
    id: "Corpsefire",
    tcs: ["Act 1 Super A", "Act 1 (N) Super A", "Act 1 (H) Super A"],
    grp: [5, 5],
    areaId: 8,
  },
  "Dac Farren": {
    id: "Dac Farren",
    tcs: ["Act 5 Super B", "Act 5 (N) Super B", "Act 5 (H) Super B"],
    grp: [4, 4],
    areaId: 110,
  },
  "Dark Elder": {
    id: "Dark Elder",
    tcs: ["Act 2 Super B", "Act 2 (N) Super B", "Act 2 (H) Super B"],
    grp: [4, 4],
    areaId: 44,
  },
  "Eyeback Unleashed": {
    id: "Eyeback Unleashed",
    tcs: ["Act 5 Super A", "Act 5 (N) Super A", "Act 5 (H) Super A"],
    grp: [2, 2],
    areaId: 111,
  },
  Fangskin: {
    id: "Fangskin",
    tcs: ["Act 2 Super B", "Act 2 (N) Super B", "Act 2 (H) Super B"],
    grp: [4, 4],
    areaId: 61,
  },
  "Fire Eye": {
    id: "Fire Eye",
    tcs: ["Act 2 Super B", "Act 2 (N) Super B", "Act 2 (H) Super B"],
    grp: [3, 3],
    areaId: 54,
  },
  Frozenstein: {
    id: "Frozenstein",
    tcs: ["Act 5 Super C", "Act 5 (N) Super C", "Act 5 (H) Super C"],
    grp: [5, 6],
    areaId: 114,
  },
  "Geleb Flamefinger": {
    id: "Geleb Flamefinger",
    tcs: ["Council", "Council (N)", "Council (H)"],
    grp: [2, 2],
    areaId: 83,
  },
  "Grand Vizier of Chaos": {
    id: "Grand Vizier of Chaos",
    tcs: ["Act 4 Super B", "Act 4 (N) Super B", "Act 4 (H) Super B"],
    grp: [9, 9],
    areaId: 108,
  },
  Griswold: {
    id: "Griswold",
    tcs: ["Griswold", "Griswold (N)", "Griswold (H)"],
    grp: [0, 0],
    areaId: 38,
  },
  "Icehawk Riftwing": {
    id: "Icehawk Riftwing",
    tcs: ["Act 3 Super A", "Act 3 (N) Super A", "Act 3 (H) Super A"],
    grp: [7, 7],
    areaId: 92,
  },
  "Infector of Souls": {
    id: "Infector of Souls",
    tcs: ["Act 4 Super B", "Act 4 (N) Super B", "Act 4 (H) Super B"],
    grp: [9, 9],
    areaId: 108,
  },
  "Ismail Vilehand": {
    id: "Ismail Vilehand",
    tcs: ["Council", "Council (N)", "Council (H)"],
    grp: [2, 2],
    areaId: 83,
  },
  Leatherarm: {
    id: "Leatherarm",
    tcs: ["Act 2 Super A", "Act 2 (N) Super A", "Act 2 (H) Super A"],
    grp: [5, 5],
    areaId: 59,
  },
  "Lord De Seis": {
    id: "Lord De Seis",
    tcs: ["Act 4 Super C", "Act 4 (N) Super C", "Act 4 (H) Super C"],
    grp: [5, 5],
    areaId: 108,
  },
  "Maffer Dragonhand": {
    id: "Maffer Dragonhand",
    tcs: ["Council", "Council (N)", "Council (H)"],
    grp: [0, 0],
    areaId: 102,
  },
  "Megaflow Rectifier": {
    id: "Megaflow Rectifier",
    tcs: ["Act 5 Super A", "Act 5 (N) Super A", "Act 5 (H) Super A"],
    grp: [8, 8],
    areaId: 111,
  },
  "Nihlathak Boss": {
    id: "Nihlathak Boss",
    tcs: ["Nihlathak", "Nihlathak (N)", "Nihlathak (H)"],
    grp: [0, 0],
    areaId: 124,
  },
  Pindleskin: {
    id: "Pindleskin",
    tcs: ["Act 5 Super Cx", "Act 5 (N) Super Cx", "Act 5 (H) Super Cx"],
    grp: [6, 6],
    areaId: 121,
  },
  "Pitspawn Fouldog": {
    id: "Pitspawn Fouldog",
    tcs: ["Act 1 Super B", "Act 1 (N) Super B", "Act 1 (H) Super B"],
    grp: [4, 4],
    areaId: 30,
  },
  Radament: {
    id: "Radament",
    tcs: ["Radament", "Radament (N)", "Radament (H)"],
    grp: [3, 3],
    areaId: 49,
  },
  Rakanishu: {
    id: "Rakanishu",
    tcs: ["Act 1 Super B", "Act 1 (N) Super B", "Act 1 (H) Super B"],
    grp: [8, 8],
    areaId: 4,
  },
  "Sarina the Battlemaid": {
    id: "Sarina the Battlemaid",
    tcs: ["Act 3 Super B", "Act 3 (N) Super B", "Act 3 (H) Super B"],
    grp: [9, 9],
    areaId: 94,
  },
  "Sharp Tooth Sayer": {
    id: "Sharp Tooth Sayer",
    tcs: ["Act 5 Super B", "Act 5 (N) Super B", "Act 5 (H) Super B"],
    grp: [3, 3],
    areaId: 111,
  },
  "Siege Boss": {
    id: "Siege Boss",
    tcs: ["Act 5 Super A", "Act 5 (N) Super A", "Act 5 (H) Super A"],
    grp: [0, 0],
    areaId: 110,
  },
  "Snapchip Shatter": {
    id: "Snapchip Shatter",
    tcs: ["Act 5 Super C", "Act 5 (N) Super C", "Act 5 (H) Super C"],
    grp: [4, 4],
    areaId: 119,
  },
  Stormtree: {
    id: "Stormtree",
    tcs: ["Act 3 Super B", "Act 3 (N) Super B", "Act 3 (H) Super B"],
    grp: [4, 4],
    areaId: 78,
  },
  "The Countess": {
    id: "The Countess",
    tcs: ["Countess", "Countess (N)", "Countess (H)"],
    grp: [6, 6],
    areaId: 25,
  },
  "The Cow King": {
    id: "The Cow King",
    tcs: ["Cow King", "Cow King (N)", "Cow King (H)"],
    grp: [6, 6],
    areaId: 39,
  },
  "The Feature Creep": {
    id: "The Feature Creep",
    tcs: ["Haphesto", "Haphesto (N)", "Haphesto (H)"],
    grp: [0, 0],
    areaId: 107,
  },
  "The Smith": {
    id: "The Smith",
    tcs: ["Smith", "Smith (N)", "Smith (H)"],
    grp: [0, 0],
    areaId: 28,
  },
  "The Summoner": {
    id: "The Summoner",
    tcs: ["Summoner", "Summoner (N)", "Summoner (H)"],
    grp: [0, 0],
    areaId: 74,
  },
  "Threash Socket": {
    id: "Threash Socket",
    tcs: ["Act 5 Super Cx", "Act 5 (N) Super Cx", "Act 5 (H) Super Cx"],
    grp: [0, 0],
    areaId: 112,
  },
  "Toorc Icefist": {
    id: "Toorc Icefist",
    tcs: ["Council", "Council (N)", "Council (H)"],
    grp: [0, 0],
    areaId: 83,
  },
  "Treehead WoodFist": {
    id: "Treehead WoodFist",
    tcs: ["Act 1 Super B", "Act 1 (N) Super B", "Act 1 (H) Super B"],
    grp: [2, 2],
    areaId: 5,
  },
  "Web Mage the Burning": {
    id: "Web Mage the Burning",
    tcs: ["Act 3 Super A", "Act 3 (N) Super A", "Act 3 (H) Super A"],
    grp: [5, 5],
    areaId: 85,
  },
  "Witch Doctor Endugu": {
    id: "Witch Doctor Endugu",
    tcs: ["Act 3 Super B", "Act 3 (N) Super B", "Act 3 (H) Super B"],
    grp: [6, 6],
    areaId: 91,
  },
  "Wyand Voidfinger": {
    id: "Wyand Voidfinger",
    tcs: ["Council", "Council (N)", "Council (H)"],
    grp: [0, 0],
    areaId: 102,
  },
};
