export type UniqueSetDictEntry = {
  index: string;
  rarity: number;
  lvl: number;
  code: string;
};

export type UniqueSetDictType = {
  [key: string]: UniqueSetDictEntry;
};

export type UniqueSetBaseLookupType = {
  [key: string]: UniqueSetDictEntry[];
};

export const UniqueDict: UniqueSetDictType = {
  "The Gnasher": { index: "The Gnasher", rarity: 1, lvl: 7, code: "hax" },
  Deathspade: { index: "Deathspade", rarity: 1, lvl: 12, code: "axe" },
  Bladebone: { index: "Bladebone", rarity: 1, lvl: 20, code: "2ax" },
  Mindrend: { index: "Mindrend", rarity: 1, lvl: 28, code: "mpi" },
  Rakescar: { index: "Rakescar", rarity: 1, lvl: 36, code: "wax" },
  "Fechmars Axe": { index: "Fechmars Axe", rarity: 1, lvl: 11, code: "lax" },
  Goreshovel: { index: "Goreshovel", rarity: 1, lvl: 19, code: "bax" },
  "The Chieftan": { index: "The Chieftan", rarity: 1, lvl: 26, code: "btx" },
  Brainhew: { index: "Brainhew", rarity: 1, lvl: 34, code: "gax" },
  "The Humongous": { index: "The Humongous", rarity: 1, lvl: 39, code: "gix" },
  "Iros Torch": { index: "Iros Torch", rarity: 1, lvl: 7, code: "wnd" },
  Maelstromwrath: { index: "Maelstromwrath", rarity: 1, lvl: 19, code: "ywn" },
  Gravenspine: { index: "Gravenspine", rarity: 1, lvl: 27, code: "bwn" },
  "Umes Lament": { index: "Umes Lament", rarity: 1, lvl: 38, code: "gwn" },
  Felloak: { index: "Felloak", rarity: 1, lvl: 4, code: "clb" },
  "Knell Striker": { index: "Knell Striker", rarity: 1, lvl: 7, code: "scp" },
  Rusthandle: { index: "Rusthandle", rarity: 1, lvl: 23, code: "gsc" },
  Stormeye: { index: "Stormeye", rarity: 1, lvl: 31, code: "wsp" },
  Stoutnail: { index: "Stoutnail", rarity: 1, lvl: 7, code: "spc" },
  Crushflange: { index: "Crushflange", rarity: 1, lvl: 12, code: "mac" },
  Bloodrise: { index: "Bloodrise", rarity: 1, lvl: 20, code: "mst" },
  "The Generals Tan Do Li Ga": {
    index: "The Generals Tan Do Li Ga",
    rarity: 1,
    lvl: 28,
    code: "fla",
  },
  Ironstone: { index: "Ironstone", rarity: 1, lvl: 36, code: "whm" },
  Bonesob: { index: "Bonesob", rarity: 1, lvl: 32, code: "mau" },
  Steeldriver: { index: "Steeldriver", rarity: 1, lvl: 39, code: "gma" },
  "Rixots Keen": { index: "Rixots Keen", rarity: 1, lvl: 3, code: "ssd" },
  "Blood Crescent": {
    index: "Blood Crescent",
    rarity: 1,
    lvl: 10,
    code: "scm",
  },
  "Krintizs Skewer": {
    index: "Krintizs Skewer",
    rarity: 1,
    lvl: 14,
    code: "sbr",
  },
  Gleamscythe: { index: "Gleamscythe", rarity: 1, lvl: 18, code: "flc" },
  "Griswolds Edge": {
    index: "Griswolds Edge",
    rarity: 1,
    lvl: 23,
    code: "bsd",
  },
  Hellplague: { index: "Hellplague", rarity: 1, lvl: 30, code: "lsd" },
  "Culwens Point": { index: "Culwens Point", rarity: 1, lvl: 39, code: "wsd" },
  Shadowfang: { index: "Shadowfang", rarity: 1, lvl: 16, code: "2hs" },
  Soulflay: { index: "Soulflay", rarity: 1, lvl: 26, code: "clm" },
  "Kinemils Awl": { index: "Kinemils Awl", rarity: 1, lvl: 31, code: "gis" },
  Blacktongue: { index: "Blacktongue", rarity: 1, lvl: 35, code: "bsw" },
  Ripsaw: { index: "Ripsaw", rarity: 1, lvl: 35, code: "flb" },
  "The Patriarch": { index: "The Patriarch", rarity: 1, lvl: 39, code: "gsd" },
  Gull: { index: "Gull", rarity: 1, lvl: 6, code: "dgr" },
  "The Diggler": { index: "The Diggler", rarity: 1, lvl: 15, code: "dir" },
  "The Jade Tan Do": {
    index: "The Jade Tan Do",
    rarity: 1,
    lvl: 26,
    code: "kri",
  },
  "Irices Shard": { index: "Irices Shard", rarity: 1, lvl: 34, code: "bld" },
  "The Dragon Chang": {
    index: "The Dragon Chang",
    rarity: 1,
    lvl: 11,
    code: "spr",
  },
  Razortine: { index: "Razortine", rarity: 1, lvl: 16, code: "tri" },
  Bloodthief: { index: "Bloodthief", rarity: 1, lvl: 23, code: "brn" },
  "Lance of Yaggai": {
    index: "Lance of Yaggai",
    rarity: 1,
    lvl: 30,
    code: "spt",
  },
  "The Tannr Gorerod": {
    index: "The Tannr Gorerod",
    rarity: 1,
    lvl: 36,
    code: "pik",
  },
  "Dimoaks Hew": { index: "Dimoaks Hew", rarity: 1, lvl: 11, code: "bar" },
  Steelgoad: { index: "Steelgoad", rarity: 1, lvl: 19, code: "vou" },
  "Soul Harvest": { index: "Soul Harvest", rarity: 1, lvl: 26, code: "scy" },
  "The Battlebranch": {
    index: "The Battlebranch",
    rarity: 1,
    lvl: 34,
    code: "pax",
  },
  Woestave: { index: "Woestave", rarity: 1, lvl: 38, code: "hal" },
  "The Grim Reaper": {
    index: "The Grim Reaper",
    rarity: 1,
    lvl: 39,
    code: "wsc",
  },
  "Bane Ash": { index: "Bane Ash", rarity: 1, lvl: 7, code: "sst" },
  "Serpent Lord": { index: "Serpent Lord", rarity: 1, lvl: 12, code: "lst" },
  "Lazarus Spire": { index: "Lazarus Spire", rarity: 1, lvl: 24, code: "cst" },
  "The Salamander": {
    index: "The Salamander",
    rarity: 1,
    lvl: 28,
    code: "bst",
  },
  "The Iron Jang Bong": {
    index: "The Iron Jang Bong",
    rarity: 1,
    lvl: 38,
    code: "wst",
  },
  Pluckeye: { index: "Pluckeye", rarity: 1, lvl: 10, code: "sbw" },
  Witherstring: { index: "Witherstring", rarity: 1, lvl: 18, code: "hbw" },
  Rimeraven: { index: "Rimeraven", rarity: 1, lvl: 20, code: "lbw" },
  Piercerib: { index: "Piercerib", rarity: 1, lvl: 27, code: "cbw" },
  Pullspite: { index: "Pullspite", rarity: 1, lvl: 34, code: "sbb" },
  Wizendraw: { index: "Wizendraw", rarity: 1, lvl: 35, code: "lbb" },
  Hellclap: { index: "Hellclap", rarity: 1, lvl: 36, code: "swb" },
  Blastbark: { index: "Blastbark", rarity: 1, lvl: 38, code: "lwb" },
  Leadcrow: { index: "Leadcrow", rarity: 1, lvl: 12, code: "lxb" },
  Ichorsting: { index: "Ichorsting", rarity: 1, lvl: 24, code: "mxb" },
  Hellcast: { index: "Hellcast", rarity: 1, lvl: 36, code: "hxb" },
  Doomspittle: { index: "Doomspittle", rarity: 1, lvl: 38, code: "rxb" },
  "War Bonnet": { index: "War Bonnet", rarity: 1, lvl: 4, code: "cap" },
  Tarnhelm: { index: "Tarnhelm", rarity: 1, lvl: 20, code: "skp" },
  "Coif of Glory": { index: "Coif of Glory", rarity: 1, lvl: 19, code: "hlm" },
  Duskdeep: { index: "Duskdeep", rarity: 1, lvl: 23, code: "fhl" },
  Wormskull: { index: "Wormskull", rarity: 1, lvl: 28, code: "bhm" },
  Howltusk: { index: "Howltusk", rarity: 1, lvl: 34, code: "ghm" },
  "Undead Crown": { index: "Undead Crown", rarity: 1, lvl: 39, code: "crn" },
  "The Face of Horror": {
    index: "The Face of Horror",
    rarity: 1,
    lvl: 27,
    code: "msk",
  },
  Greyform: { index: "Greyform", rarity: 1, lvl: 10, code: "qui" },
  "Blinkbats Form": {
    index: "Blinkbats Form",
    rarity: 1,
    lvl: 16,
    code: "lea",
  },
  "The Centurion": { index: "The Centurion", rarity: 1, lvl: 19, code: "hla" },
  Twitchthroe: { index: "Twitchthroe", rarity: 1, lvl: 22, code: "stu" },
  Darkglow: { index: "Darkglow", rarity: 1, lvl: 19, code: "rng" },
  Hawkmail: { index: "Hawkmail", rarity: 1, lvl: 20, code: "scl" },
  "Sparking Mail": { index: "Sparking Mail", rarity: 1, lvl: 23, code: "chn" },
  Venomsward: { index: "Venomsward", rarity: 1, lvl: 27, code: "brs" },
  Iceblink: { index: "Iceblink", rarity: 1, lvl: 30, code: "spl" },
  Boneflesh: { index: "Boneflesh", rarity: 1, lvl: 35, code: "plt" },
  Rockfleece: { index: "Rockfleece", rarity: 1, lvl: 38, code: "fld" },
  Rattlecage: { index: "Rattlecage", rarity: 1, lvl: 39, code: "gth" },
  Goldskin: { index: "Goldskin", rarity: 1, lvl: 38, code: "ful" },
  "Victors Silk": { index: "Victors Silk", rarity: 1, lvl: 38, code: "aar" },
  "Heavenly Garb": { index: "Heavenly Garb", rarity: 1, lvl: 39, code: "ltp" },
  "Pelta Lunata": { index: "Pelta Lunata", rarity: 1, lvl: 3, code: "buc" },
  "Umbral Disk": { index: "Umbral Disk", rarity: 1, lvl: 12, code: "sml" },
  Stormguild: { index: "Stormguild", rarity: 1, lvl: 18, code: "lrg" },
  "Wall of the Eyeless": {
    index: "Wall of the Eyeless",
    rarity: 1,
    lvl: 27,
    code: "bsh",
  },
  "Swordback Hold": {
    index: "Swordback Hold",
    rarity: 1,
    lvl: 20,
    code: "spk",
  },
  Steelclash: { index: "Steelclash", rarity: 1, lvl: 23, code: "kit" },
  "Bverrit Keep": { index: "Bverrit Keep", rarity: 1, lvl: 26, code: "tow" },
  "The Ward": { index: "The Ward", rarity: 1, lvl: 35, code: "gts" },
  "The Hand of Broc": {
    index: "The Hand of Broc",
    rarity: 1,
    lvl: 7,
    code: "lgl",
  },
  Bloodfist: { index: "Bloodfist", rarity: 1, lvl: 12, code: "vgl" },
  "Chance Guards": { index: "Chance Guards", rarity: 1, lvl: 20, code: "mgl" },
  Magefist: { index: "Magefist", rarity: 1, lvl: 31, code: "tgl" },
  Frostburn: { index: "Frostburn", rarity: 1, lvl: 39, code: "hgl" },
  Hotspur: { index: "Hotspur", rarity: 1, lvl: 7, code: "lbt" },
  Gorefoot: { index: "Gorefoot", rarity: 1, lvl: 12, code: "vbt" },
  "Treads of Cthon": {
    index: "Treads of Cthon",
    rarity: 1,
    lvl: 20,
    code: "mbt",
  },
  "Goblin Toe": { index: "Goblin Toe", rarity: 1, lvl: 30, code: "tbt" },
  Tearhaunch: { index: "Tearhaunch", rarity: 1, lvl: 39, code: "hbt" },
  "Lenyms Cord": { index: "Lenyms Cord", rarity: 1, lvl: 10, code: "lbl" },
  Snakecord: { index: "Snakecord", rarity: 1, lvl: 16, code: "vbl" },
  Nightsmoke: { index: "Nightsmoke", rarity: 1, lvl: 27, code: "mbl" },
  Goldwrap: { index: "Goldwrap", rarity: 1, lvl: 36, code: "tbl" },
  Bladebuckle: { index: "Bladebuckle", rarity: 1, lvl: 39, code: "hbl" },
  "Nokozan Relic": { index: "Nokozan Relic", rarity: 20, lvl: 14, code: "amu" },
  "The Eye of Etlich": {
    index: "The Eye of Etlich",
    rarity: 5,
    lvl: 20,
    code: "amu",
  },
  "The Mahim-Oak Curio": {
    index: "The Mahim-Oak Curio",
    rarity: 10,
    lvl: 34,
    code: "amu",
  },
  Nagelring: { index: "Nagelring", rarity: 15, lvl: 10, code: "rin" },
  "Manald Heal": { index: "Manald Heal", rarity: 15, lvl: 20, code: "rin" },
  "The Stone of Jordan": {
    index: "The Stone of Jordan",
    rarity: 1,
    lvl: 39,
    code: "rin",
  },
  "Amulet of the Viper": {
    index: "Amulet of the Viper",
    rarity: 1,
    lvl: 0,
    code: "vip",
  },
  "Staff of Kings": { index: "Staff of Kings", rarity: 1, lvl: 0, code: "msf" },
  "Horadric Staff": { index: "Horadric Staff", rarity: 1, lvl: 0, code: "hst" },
  "Hell Forge Hammer": {
    index: "Hell Forge Hammer",
    rarity: 1,
    lvl: 0,
    code: "hfh",
  },
  KhalimFlail: { index: "KhalimFlail", rarity: 1, lvl: 0, code: "qf1" },
  SuperKhalimFlail: {
    index: "SuperKhalimFlail",
    rarity: 1,
    lvl: 0,
    code: "qf2",
  },
  Coldkill: { index: "Coldkill", rarity: 1, lvl: 44, code: "9ha" },
  "Butcher's Pupil": {
    index: "Butcher's Pupil",
    rarity: 1,
    lvl: 47,
    code: "9ax",
  },
  Islestrike: { index: "Islestrike", rarity: 1, lvl: 51, code: "92a" },
  "Pompe's Wrath": { index: "Pompe's Wrath", rarity: 1, lvl: 53, code: "9mp" },
  "Guardian Naga": { index: "Guardian Naga", rarity: 1, lvl: 56, code: "9wa" },
  "Warlord's Trust": {
    index: "Warlord's Trust",
    rarity: 1,
    lvl: 43,
    code: "9la",
  },
  Spellsteel: { index: "Spellsteel", rarity: 1, lvl: 47, code: "9ba" },
  Stormrider: { index: "Stormrider", rarity: 1, lvl: 49, code: "9bt" },
  "Boneslayer Blade": {
    index: "Boneslayer Blade",
    rarity: 1,
    lvl: 50,
    code: "9ga",
  },
  "The Minataur": { index: "The Minataur", rarity: 1, lvl: 53, code: "9gi" },
  "Suicide Branch": {
    index: "Suicide Branch",
    rarity: 1,
    lvl: 41,
    code: "9wn",
  },
  "Carin Shard": { index: "Carin Shard", rarity: 1, lvl: 43, code: "9yw" },
  "Arm of King Leoric": {
    index: "Arm of King Leoric",
    rarity: 1,
    lvl: 44,
    code: "9bw",
  },
  "Blackhand Key": { index: "Blackhand Key", rarity: 1, lvl: 49, code: "9gw" },
  "Dark Clan Crusher": {
    index: "Dark Clan Crusher",
    rarity: 1,
    lvl: 42,
    code: "9cl",
  },
  "Zakarum's Hand": {
    index: "Zakarum's Hand",
    rarity: 1,
    lvl: 45,
    code: "9sc",
  },
  "The Fetid Sprinkler": {
    index: "The Fetid Sprinkler",
    rarity: 1,
    lvl: 46,
    code: "9qs",
  },
  "Hand of Blessed Light": {
    index: "Hand of Blessed Light",
    rarity: 1,
    lvl: 50,
    code: "9ws",
  },
  Fleshrender: { index: "Fleshrender", rarity: 1, lvl: 46, code: "9sp" },
  "Sureshrill Frost": {
    index: "Sureshrill Frost",
    rarity: 1,
    lvl: 47,
    code: "9ma",
  },
  Moonfall: { index: "Moonfall", rarity: 1, lvl: 50, code: "9mt" },
  "Baezil's Vortex": {
    index: "Baezil's Vortex",
    rarity: 1,
    lvl: 53,
    code: "9fl",
  },
  Earthshaker: { index: "Earthshaker", rarity: 1, lvl: 51, code: "9wh" },
  "Bloodtree Stump": {
    index: "Bloodtree Stump",
    rarity: 1,
    lvl: 56,
    code: "9m9",
  },
  "The Gavel of Pain": {
    index: "The Gavel of Pain",
    rarity: 1,
    lvl: 53,
    code: "9gm",
  },
  Bloodletter: { index: "Bloodletter", rarity: 1, lvl: 38, code: "9ss" },
  "Coldsteel Eye": { index: "Coldsteel Eye", rarity: 1, lvl: 39, code: "9sm" },
  Hexfire: { index: "Hexfire", rarity: 1, lvl: 41, code: "9sb" },
  "Blade of Ali Baba": {
    index: "Blade of Ali Baba",
    rarity: 1,
    lvl: 43,
    code: "9fc",
  },
  "Ginther's Rift": {
    index: "Ginther's Rift",
    rarity: 1,
    lvl: 45,
    code: "9cr",
  },
  Headstriker: { index: "Headstriker", rarity: 1, lvl: 47, code: "9bs" },
  "Plague Bearer": { index: "Plague Bearer", rarity: 1, lvl: 49, code: "9ls" },
  "The Atlantian": { index: "The Atlantian", rarity: 1, lvl: 50, code: "9wd" },
  "Crainte Vomir": { index: "Crainte Vomir", rarity: 1, lvl: 50, code: "92h" },
  "Bing Sz Wang": { index: "Bing Sz Wang", rarity: 1, lvl: 51, code: "9cm" },
  "The Vile Husk": { index: "The Vile Husk", rarity: 1, lvl: 52, code: "9gs" },
  Cloudcrack: { index: "Cloudcrack", rarity: 1, lvl: 53, code: "9b9" },
  "Todesfaelle Flamme": {
    index: "Todesfaelle Flamme",
    rarity: 1,
    lvl: 54,
    code: "9fb",
  },
  Swordguard: { index: "Swordguard", rarity: 1, lvl: 55, code: "9gd" },
  Spineripper: { index: "Spineripper", rarity: 1, lvl: 40, code: "9dg" },
  "Heart Carver": { index: "Heart Carver", rarity: 1, lvl: 44, code: "9di" },
  "Blackbog's Sharp": {
    index: "Blackbog's Sharp",
    rarity: 1,
    lvl: 46,
    code: "9kr",
  },
  Stormspike: { index: "Stormspike", rarity: 1, lvl: 49, code: "9bl" },
  "The Impaler": { index: "The Impaler", rarity: 1, lvl: 39, code: "9sr" },
  "Kelpie Snare": { index: "Kelpie Snare", rarity: 1, lvl: 41, code: "9tr" },
  "Soulfeast Tine": {
    index: "Soulfeast Tine",
    rarity: 1,
    lvl: 43,
    code: "9br",
  },
  "Hone Sundan": { index: "Hone Sundan", rarity: 1, lvl: 45, code: "9st" },
  "Spire of Honor": {
    index: "Spire of Honor",
    rarity: 1,
    lvl: 47,
    code: "9p9",
  },
  "The Meat Scraper": {
    index: "The Meat Scraper",
    rarity: 1,
    lvl: 49,
    code: "9b7",
  },
  "Blackleach Blade": {
    index: "Blackleach Blade",
    rarity: 1,
    lvl: 50,
    code: "9vo",
  },
  "Athena's Wrath": {
    index: "Athena's Wrath",
    rarity: 1,
    lvl: 50,
    code: "9s8",
  },
  "Pierre Tombale Couant": {
    index: "Pierre Tombale Couant",
    rarity: 1,
    lvl: 51,
    code: "9pa",
  },
  "Husoldal Evo": { index: "Husoldal Evo", rarity: 1, lvl: 52, code: "9h9" },
  "Grim's Burning Dead": {
    index: "Grim's Burning Dead",
    rarity: 1,
    lvl: 52,
    code: "9wc",
  },
  Razorswitch: { index: "Razorswitch", rarity: 1, lvl: 36, code: "8ss" },
  Ribcracker: { index: "Ribcracker", rarity: 1, lvl: 39, code: "8ls" },
  "Chromatic Ire": { index: "Chromatic Ire", rarity: 1, lvl: 43, code: "8cs" },
  Warpspear: { index: "Warpspear", rarity: 1, lvl: 47, code: "8bs" },
  Skullcollector: { index: "Skullcollector", rarity: 1, lvl: 49, code: "8ws" },
  Skystrike: { index: "Skystrike", rarity: 1, lvl: 36, code: "8sb" },
  Riphook: { index: "Riphook", rarity: 1, lvl: 39, code: "8hb" },
  "Kuko Shakaku": { index: "Kuko Shakaku", rarity: 1, lvl: 41, code: "8lb" },
  Endlesshail: { index: "Endlesshail", rarity: 1, lvl: 44, code: "8cb" },
  "Whichwild String": {
    index: "Whichwild String",
    rarity: 1,
    lvl: 47,
    code: "8s8",
  },
  Cliffkiller: { index: "Cliffkiller", rarity: 1, lvl: 49, code: "8l8" },
  Magewrath: { index: "Magewrath", rarity: 1, lvl: 51, code: "8sw" },
  "Godstrike Arch": {
    index: "Godstrike Arch",
    rarity: 1,
    lvl: 54,
    code: "8lw",
  },
  "Langer Briser": { index: "Langer Briser", rarity: 1, lvl: 40, code: "8lx" },
  "Pus Spiter": { index: "Pus Spiter", rarity: 1, lvl: 44, code: "8mx" },
  "Buriza-Do Kyanon": {
    index: "Buriza-Do Kyanon",
    rarity: 1,
    lvl: 59,
    code: "8hx",
  },
  "Demon Machine": { index: "Demon Machine", rarity: 1, lvl: 57, code: "8rx" },
  "Peasent Crown": { index: "Peasent Crown", rarity: 1, lvl: 36, code: "xap" },
  Rockstopper: { index: "Rockstopper", rarity: 1, lvl: 39, code: "xkp" },
  Stealskull: { index: "Stealskull", rarity: 1, lvl: 43, code: "xlm" },
  "Darksight Helm": {
    index: "Darksight Helm",
    rarity: 1,
    lvl: 46,
    code: "xhl",
  },
  "Valkiry Wing": { index: "Valkiry Wing", rarity: 1, lvl: 52, code: "xhm" },
  "Crown of Thieves": {
    index: "Crown of Thieves",
    rarity: 1,
    lvl: 57,
    code: "xrn",
  },
  "Blackhorn's Face": {
    index: "Blackhorn's Face",
    rarity: 1,
    lvl: 49,
    code: "xsk",
  },
  Vampiregaze: { index: "Vampiregaze", rarity: 1, lvl: 49, code: "xh9" },
  "The Spirit Shroud": {
    index: "The Spirit Shroud",
    rarity: 1,
    lvl: 36,
    code: "xui",
  },
  "Skin of the Vipermagi": {
    index: "Skin of the Vipermagi",
    rarity: 1,
    lvl: 37,
    code: "xea",
  },
  "Skin of the Flayerd One": {
    index: "Skin of the Flayerd One",
    rarity: 1,
    lvl: 39,
    code: "xla",
  },
  Ironpelt: { index: "Ironpelt", rarity: 1, lvl: 41, code: "xtu" },
  Spiritforge: { index: "Spiritforge", rarity: 1, lvl: 43, code: "xng" },
  "Crow Caw": { index: "Crow Caw", rarity: 1, lvl: 45, code: "xcl" },
  Shaftstop: { index: "Shaftstop", rarity: 1, lvl: 46, code: "xhn" },
  "Duriel's Shell": {
    index: "Duriel's Shell",
    rarity: 1,
    lvl: 49,
    code: "xrs",
  },
  "Skullder's Ire": {
    index: "Skullder's Ire",
    rarity: 1,
    lvl: 50,
    code: "xpl",
  },
  "Guardian Angel": {
    index: "Guardian Angel",
    rarity: 1,
    lvl: 53,
    code: "xlt",
  },
  Toothrow: { index: "Toothrow", rarity: 1, lvl: 56, code: "xld" },
  "Atma's Wail": { index: "Atma's Wail", rarity: 1, lvl: 59, code: "xth" },
  "Black Hades": { index: "Black Hades", rarity: 1, lvl: 61, code: "xul" },
  Corpsemourn: { index: "Corpsemourn", rarity: 1, lvl: 63, code: "xar" },
  "Que-Hegan's Wisdon": {
    index: "Que-Hegan's Wisdon",
    rarity: 1,
    lvl: 59,
    code: "xtp",
  },
  Visceratuant: { index: "Visceratuant", rarity: 1, lvl: 36, code: "xuc" },
  "Mosers Blessed Circle": {
    index: "Mosers Blessed Circle",
    rarity: 1,
    lvl: 39,
    code: "xml",
  },
  Stormchaser: { index: "Stormchaser", rarity: 1, lvl: 43, code: "xrg" },
  "Tiamat's Rebuke": {
    index: "Tiamat's Rebuke",
    rarity: 1,
    lvl: 46,
    code: "xit",
  },
  "Kerke's Sanctuary": {
    index: "Kerke's Sanctuary",
    rarity: 1,
    lvl: 52,
    code: "xow",
  },
  "Radimant's Sphere": {
    index: "Radimant's Sphere",
    rarity: 1,
    lvl: 58,
    code: "xts",
  },
  "Lidless Wall": { index: "Lidless Wall", rarity: 1, lvl: 49, code: "xsh" },
  "Lance Guard": { index: "Lance Guard", rarity: 1, lvl: 43, code: "xpk" },
  "Venom Grip": { index: "Venom Grip", rarity: 1, lvl: 37, code: "xlg" },
  Gravepalm: { index: "Gravepalm", rarity: 1, lvl: 39, code: "xvg" },
  Ghoulhide: { index: "Ghoulhide", rarity: 1, lvl: 44, code: "xmg" },
  Lavagout: { index: "Lavagout", rarity: 1, lvl: 50, code: "xtg" },
  Hellmouth: { index: "Hellmouth", rarity: 1, lvl: 55, code: "xhg" },
  Infernostride: { index: "Infernostride", rarity: 1, lvl: 37, code: "xlb" },
  Waterwalk: { index: "Waterwalk", rarity: 1, lvl: 40, code: "xvb" },
  Silkweave: { index: "Silkweave", rarity: 1, lvl: 44, code: "xmb" },
  Wartraveler: { index: "Wartraveler", rarity: 1, lvl: 50, code: "xtb" },
  Gorerider: { index: "Gorerider", rarity: 1, lvl: 55, code: "xhb" },
  "String of Ears": {
    index: "String of Ears",
    rarity: 1,
    lvl: 37,
    code: "zlb",
  },
  Razortail: { index: "Razortail", rarity: 1, lvl: 39, code: "zvb" },
  Gloomstrap: { index: "Gloomstrap", rarity: 1, lvl: 45, code: "zmb" },
  Snowclash: { index: "Snowclash", rarity: 1, lvl: 49, code: "ztb" },
  "Thudergod's Vigor": {
    index: "Thudergod's Vigor",
    rarity: 1,
    lvl: 55,
    code: "zhb",
  },
  "Harlequin Crest": {
    index: "Harlequin Crest",
    rarity: 1,
    lvl: 69,
    code: "uap",
  },
  "Veil of Steel": { index: "Veil of Steel", rarity: 1, lvl: 77, code: "uhm" },
  "The Gladiator's Bane": {
    index: "The Gladiator's Bane",
    rarity: 1,
    lvl: 85,
    code: "utu",
  },
  "Arkaine's Valor": {
    index: "Arkaine's Valor",
    rarity: 1,
    lvl: 85,
    code: "upl",
  },
  "Blackoak Shield": {
    index: "Blackoak Shield",
    rarity: 1,
    lvl: 67,
    code: "uml",
  },
  Stormshield: { index: "Stormshield", rarity: 1, lvl: 77, code: "uit" },
  Hellslayer: { index: "Hellslayer", rarity: 1, lvl: 71, code: "7bt" },
  "Messerschmidt's Reaver": {
    index: "Messerschmidt's Reaver",
    rarity: 1,
    lvl: 75,
    code: "7ga",
  },
  "Baranar's Star": {
    index: "Baranar's Star",
    rarity: 1,
    lvl: 70,
    code: "7mt",
  },
  "Schaefer's Hammer": {
    index: "Schaefer's Hammer",
    rarity: 1,
    lvl: 83,
    code: "7wh",
  },
  "The Cranium Basher": {
    index: "The Cranium Basher",
    rarity: 1,
    lvl: 85,
    code: "7gm",
  },
  Lightsabre: { index: "Lightsabre", rarity: 5, lvl: 66, code: "7cr" },
  Doombringer: { index: "Doombringer", rarity: 1, lvl: 75, code: "7b7" },
  "The Grandfather": {
    index: "The Grandfather",
    rarity: 1,
    lvl: 85,
    code: "7gd",
  },
  Wizardspike: { index: "Wizardspike", rarity: 1, lvl: 69, code: "7dg" },
  Stormspire: { index: "Stormspire", rarity: 1, lvl: 78, code: "7wc" },
  Eaglehorn: { index: "Eaglehorn", rarity: 1, lvl: 77, code: "6l7" },
  Windforce: { index: "Windforce", rarity: 1, lvl: 80, code: "6lw" },
  "Bul Katho's Wedding Band": {
    index: "Bul Katho's Wedding Band",
    rarity: 1,
    lvl: 66,
    code: "rin",
  },
  "The Cat's Eye": { index: "The Cat's Eye", rarity: 5, lvl: 58, code: "amu" },
  "The Rising Sun": {
    index: "The Rising Sun",
    rarity: 5,
    lvl: 73,
    code: "amu",
  },
  "Crescent Moon": { index: "Crescent Moon", rarity: 5, lvl: 58, code: "amu" },
  "Mara's Kaleidoscope": {
    index: "Mara's Kaleidoscope",
    rarity: 5,
    lvl: 80,
    code: "amu",
  },
  "Atma's Scarab": { index: "Atma's Scarab", rarity: 5, lvl: 60, code: "amu" },
  "Dwarf Star": { index: "Dwarf Star", rarity: 10, lvl: 53, code: "rin" },
  "Raven Frost": { index: "Raven Frost", rarity: 10, lvl: 53, code: "rin" },
  "Highlord's Wrath": {
    index: "Highlord's Wrath",
    rarity: 5,
    lvl: 73,
    code: "amu",
  },
  "Saracen's Chance": {
    index: "Saracen's Chance",
    rarity: 5,
    lvl: 55,
    code: "amu",
  },
  "Arreat's Face": { index: "Arreat's Face", rarity: 1, lvl: 50, code: "baa" },
  Homunculus: { index: "Homunculus", rarity: 1, lvl: 50, code: "nea" },
  "Titan's Revenge": {
    index: "Titan's Revenge",
    rarity: 1,
    lvl: 50,
    code: "ama",
  },
  "Lycander's Aim": {
    index: "Lycander's Aim",
    rarity: 1,
    lvl: 50,
    code: "am7",
  },
  "Lycander's Flank": {
    index: "Lycander's Flank",
    rarity: 1,
    lvl: 50,
    code: "am9",
  },
  "The Oculus": { index: "The Oculus", rarity: 1, lvl: 50, code: "oba" },
  "Herald of Zakarum": {
    index: "Herald of Zakarum",
    rarity: 1,
    lvl: 50,
    code: "pa9",
  },
  Cutthroat1: { index: "Cutthroat1", rarity: 1, lvl: 50, code: "9tw" },
  "Jalal's Mane": { index: "Jalal's Mane", rarity: 1, lvl: 50, code: "dra" },
  "The Scalper": { index: "The Scalper", rarity: 1, lvl: 65, code: "9ta" },
  Bloodmoon: { index: "Bloodmoon", rarity: 1, lvl: 69, code: "7sb" },
  Djinnslayer: { index: "Djinnslayer", rarity: 1, lvl: 73, code: "7sm" },
  Deathbit: { index: "Deathbit", rarity: 1, lvl: 52, code: "9tk" },
  Warshrike: { index: "Warshrike", rarity: 1, lvl: 83, code: "7bk" },
  Gutsiphon: { index: "Gutsiphon", rarity: 1, lvl: 79, code: "6rx" },
  Razoredge: { index: "Razoredge", rarity: 1, lvl: 75, code: "7ha" },
  Demonlimb: { index: "Demonlimb", rarity: 1, lvl: 71, code: "7sp" },
  Steelshade: { index: "Steelshade", rarity: 1, lvl: 70, code: "ulm" },
  "Tomb Reaver": { index: "Tomb Reaver", rarity: 1, lvl: 86, code: "7pa" },
  "Deaths's Web": { index: "Deaths's Web", rarity: 1, lvl: 74, code: "7gw" },
  "Nature's Peace": {
    index: "Nature's Peace",
    rarity: 3,
    lvl: 77,
    code: "rin",
  },
  Azurewrath: { index: "Azurewrath", rarity: 1, lvl: 87, code: "7cr" },
  "Seraph's Hymn": { index: "Seraph's Hymn", rarity: 3, lvl: 73, code: "amu" },
  Fleshripper: { index: "Fleshripper", rarity: 1, lvl: 76, code: "7kr" },
  "Horizon's Tornado": {
    index: "Horizon's Tornado",
    rarity: 5,
    lvl: 72,
    code: "7fl",
  },
  "Stone Crusher": { index: "Stone Crusher", rarity: 4, lvl: 76, code: "7wh" },
  Jadetalon: { index: "Jadetalon", rarity: 1, lvl: 74, code: "7wb" },
  Shadowdancer: { index: "Shadowdancer", rarity: 1, lvl: 79, code: "uhb" },
  Cerebus: { index: "Cerebus", rarity: 1, lvl: 71, code: "drb" },
  "Tyrael's Might": {
    index: "Tyrael's Might",
    rarity: 1,
    lvl: 87,
    code: "uar",
  },
  Souldrain: { index: "Souldrain", rarity: 1, lvl: 82, code: "umg" },
  Runemaster: { index: "Runemaster", rarity: 1, lvl: 80, code: "72a" },
  Deathcleaver: { index: "Deathcleaver", rarity: 1, lvl: 78, code: "7wa" },
  "Executioner's Justice": {
    index: "Executioner's Justice",
    rarity: 1,
    lvl: 83,
    code: "7gi",
  },
  Stoneraven: { index: "Stoneraven", rarity: 1, lvl: 72, code: "amd" },
  Leviathan: { index: "Leviathan", rarity: 1, lvl: 73, code: "uld" },
  Wisp: { index: "Wisp", rarity: 1, lvl: 84, code: "rin" },
  "Gargoyle's Bite": {
    index: "Gargoyle's Bite",
    rarity: 1,
    lvl: 78,
    code: "7ts",
  },
  Lacerator: { index: "Lacerator", rarity: 1, lvl: 76, code: "7b8" },
  "Mang Song's Lesson": {
    index: "Mang Song's Lesson",
    rarity: 1,
    lvl: 86,
    code: "6ws",
  },
  Viperfork: { index: "Viperfork", rarity: 1, lvl: 79, code: "7br" },
  "Ethereal Edge": { index: "Ethereal Edge", rarity: 1, lvl: 82, code: "7ba" },
  "Demonhorn's Edge": {
    index: "Demonhorn's Edge",
    rarity: 1,
    lvl: 69,
    code: "bad",
  },
  "The Reaper's Toll": {
    index: "The Reaper's Toll",
    rarity: 1,
    lvl: 83,
    code: "7s8",
  },
  Spiritkeeper: { index: "Spiritkeeper", rarity: 1, lvl: 75, code: "drd" },
  Hellrack: { index: "Hellrack", rarity: 1, lvl: 84, code: "6hx" },
  "Alma Negra": { index: "AlmaNegra", rarity: 1, lvl: 85, code: "pac" },
  "Darkforge Spawn": {
    index: "Darkforge Spawn",
    rarity: 1,
    lvl: 72,
    code: "nef",
  },
  Widowmaker: { index: "Widowmaker", rarity: 1, lvl: 73, code: "6sw" },
  "Bloodraven's Charge": {
    index: "Bloodraven's Charge",
    rarity: 1,
    lvl: 79,
    code: "amb",
  },
  Ghostflame: { index: "Ghostflame", rarity: 1, lvl: 70, code: "7bl" },
  Shadowkiller: { index: "Shadowkiller", rarity: 1, lvl: 85, code: "7cs" },
  Gimmershred: { index: "Gimmershred", rarity: 1, lvl: 78, code: "7ta" },
  "Griffon's Eye": { index: "Griffon's Eye", rarity: 1, lvl: 84, code: "ci3" },
  Windhammer: { index: "Windhammer", rarity: 1, lvl: 76, code: "7m7" },
  Thunderstroke: { index: "Thunderstroke", rarity: 1, lvl: 77, code: "amf" },
  "Demon's Arch": { index: "Demon's Arch", rarity: 1, lvl: 76, code: "7s7" },
  Boneflame: { index: "Boneflame", rarity: 1, lvl: 80, code: "nee" },
  Steelpillar: { index: "Steelpillar", rarity: 1, lvl: 77, code: "7p7" },
  "Nightwing's Veil": {
    index: "Nightwing's Veil",
    rarity: 1,
    lvl: 75,
    code: "uhm",
  },
  "Crown of Ages": { index: "Crown of Ages", rarity: 1, lvl: 86, code: "urn" },
  "Andariel's Visage": {
    index: "Andariel's Visage",
    rarity: 1,
    lvl: 85,
    code: "usk",
  },
  Dragonscale: { index: "Dragonscale", rarity: 1, lvl: 84, code: "pae" },
  "Steel Carapice": {
    index: "Steel Carapice",
    rarity: 1,
    lvl: 74,
    code: "uul",
  },
  "Medusa's Gaze": { index: "Medusa's Gaze", rarity: 1, lvl: 84, code: "uow" },
  Ravenlore: { index: "Ravenlore", rarity: 1, lvl: 82, code: "dre" },
  Boneshade: { index: "Boneshade", rarity: 1, lvl: 84, code: "7bw" },
  Flamebellow: { index: "Flamebellow", rarity: 1, lvl: 79, code: "7gs" },
  Fathom: { index: "Fathom", rarity: 1, lvl: 81, code: "obf" },
  Wolfhowl: { index: "Wolfhowl", rarity: 1, lvl: 85, code: "bac" },
  "Spirit Ward": { index: "Spirit Ward", rarity: 1, lvl: 76, code: "uts" },
  "Kira's Guardian": {
    index: "Kira's Guardian",
    rarity: 1,
    lvl: 85,
    code: "ci2",
  },
  "Ormus' Robes": { index: "Ormus' Robes", rarity: 1, lvl: 83, code: "uui" },
  "Gheed's Fortune": {
    index: "Gheed's Fortune",
    rarity: 1,
    lvl: 70,
    code: "cm3",
  },
  "The Black Cleft": {
    index: "The Black Cleft",
    rarity: 1,
    lvl: 75,
    code: "cm3",
  },
  "The Bone Break": {
    index: "The Bone Break",
    rarity: 1,
    lvl: 75,
    code: "cm3",
  },
  "The Cold Rupture": {
    index: "The Cold Rupture",
    rarity: 1,
    lvl: 75,
    code: "cm3",
  },
  "The Crack of the Heavens": {
    index: "The Crack of the Heavens",
    rarity: 1,
    lvl: 75,
    code: "cm3",
  },
  "The Flame Rift": {
    index: "The Flame Rift",
    rarity: 1,
    lvl: 75,
    code: "cm3",
  },
  "The Rotting Fissure": {
    index: "The Rotting Fissure",
    rarity: 1,
    lvl: 75,
    code: "cm3",
  },
  Stormlash: { index: "Stormlash", rarity: 1, lvl: 86, code: "7fl" },
  "Halaberd's Reign": {
    index: "Halaberd's Reign",
    rarity: 1,
    lvl: 85,
    code: "bae",
  },
  "Spike Thorn": { index: "Spike Thorn", rarity: 1, lvl: 78, code: "upk" },
  "Dracul's Grasp": {
    index: "Dracul's Grasp",
    rarity: 1,
    lvl: 84,
    code: "uvg",
  },
  Frostwind: { index: "Frostwind", rarity: 1, lvl: 78, code: "7ls" },
  "Templar's Might": {
    index: "Templar's Might",
    rarity: 8,
    lvl: 82,
    code: "uar",
  },
  "Eschuta's temper": {
    index: "Eschuta's temper",
    rarity: 1,
    lvl: 80,
    code: "obc",
  },
  "Firelizard's Talons": {
    index: "Firelizard's Talons",
    rarity: 1,
    lvl: 75,
    code: "7lw",
  },
  "Sandstorm Trek": {
    index: "Sandstorm Trek",
    rarity: 1,
    lvl: 72,
    code: "uvb",
  },
  Marrowwalk: { index: "Marrowwalk", rarity: 1, lvl: 74, code: "umb" },
  "Heaven's Light": {
    index: "Heaven's Light",
    rarity: 1,
    lvl: 69,
    code: "7sc",
  },
  "Arachnid Mesh": { index: "Arachnid Mesh", rarity: 1, lvl: 87, code: "ulc" },
  "Nosferatu's Coil": {
    index: "Nosferatu's Coil",
    rarity: 1,
    lvl: 68,
    code: "uvc",
  },
  Metalgrid: { index: "Metalgrid", rarity: 2, lvl: 85, code: "amu" },
  "Verdugo's Hearty Cord": {
    index: "Verdugo's Hearty Cord",
    rarity: 1,
    lvl: 71,
    code: "umc",
  },
  "Carrion Wind": { index: "Carrion Wind", rarity: 3, lvl: 68, code: "rin" },
  Giantskull: { index: "Giantskull", rarity: 1, lvl: 73, code: "uh9" },
  Ironward: { index: "Ironward", rarity: 1, lvl: 68, code: "7ws" },
  Annihilus: { index: "Annihilus", rarity: 1, lvl: 110, code: "cm1" },
  "Arioc's Needle": {
    index: "Arioc's Needle",
    rarity: 1,
    lvl: 85,
    code: "7sr",
  },
  Cranebeak: { index: "Cranebeak", rarity: 1, lvl: 71, code: "7mp" },
  "Nord's Tenderizer": {
    index: "Nord's Tenderizer",
    rarity: 1,
    lvl: 76,
    code: "7cl",
  },
  Earthshifter: { index: "Earthshifter", rarity: 1, lvl: 77, code: "7gm" },
  Wraithflight: { index: "Wraithflight", rarity: 1, lvl: 84, code: "7gl" },
  Bonehew: { index: "Bonehew", rarity: 1, lvl: 72, code: "7o7" },
  "Ondal's Wisdom": {
    index: "Ondal's Wisdom",
    rarity: 1,
    lvl: 74,
    code: "6cs",
  },
  "The Reedeemer": { index: "The Reedeemer", rarity: 1, lvl: 80, code: "7sc" },
  "Headhunter's Glory": {
    index: "Headhunter's Glory",
    rarity: 1,
    lvl: 83,
    code: "ush",
  },
  Steelrend: { index: "Steelrend", rarity: 1, lvl: 78, code: "uhg" },
  "Rainbow Facet 1": {
    index: "Rainbow Facet 1",
    rarity: 1,
    lvl: 85,
    code: "jew",
  },
  "Rainbow Facet 2": {
    index: "Rainbow Facet 2",
    rarity: 1,
    lvl: 85,
    code: "jew",
  },
  "Rainbow Facet 3": {
    index: "Rainbow Facet 3",
    rarity: 1,
    lvl: 85,
    code: "jew",
  },
  "Rainbow Facet 4": {
    index: "Rainbow Facet 4",
    rarity: 1,
    lvl: 85,
    code: "jew",
  },
  "Rainbow Facet 5": {
    index: "Rainbow Facet 5",
    rarity: 1,
    lvl: 85,
    code: "jew",
  },
  "Rainbow Facet 6": {
    index: "Rainbow Facet 6",
    rarity: 1,
    lvl: 85,
    code: "jew",
  },
  "Rainbow Facet 7": {
    index: "Rainbow Facet 7",
    rarity: 1,
    lvl: 85,
    code: "jew",
  },
  "Rainbow Facet 8": {
    index: "Rainbow Facet 8",
    rarity: 1,
    lvl: 85,
    code: "jew",
  },
  "Hellfire Torch": {
    index: "Hellfire Torch",
    rarity: 1,
    lvl: 110,
    code: "cm2",
  },
};

export const SetDict: UniqueSetDictType = {
  "Aldur's Advance": {
    index: "Aldur's Advance",
    rarity: 7,
    lvl: 29,
    code: "xtb",
  },
  "Aldur's Deception": {
    index: "Aldur's Deception",
    rarity: 7,
    lvl: 29,
    code: "uul",
  },
  "Aldur's Gauntlet": {
    index: "Aldur's Gauntlet",
    rarity: 7,
    lvl: 29,
    code: "9mt",
  },
  "Aldur's Stony Gaze": {
    index: "Aldur's Stony Gaze",
    rarity: 7,
    lvl: 29,
    code: "dr8",
  },
  "Angelic Halo": { index: "Angelic Halo", rarity: 3, lvl: 17, code: "rin" },
  "Angelic Mantle": {
    index: "Angelic Mantle",
    rarity: 7,
    lvl: 17,
    code: "rng",
  },
  "Angelic Sickle": {
    index: "Angelic Sickle",
    rarity: 7,
    lvl: 17,
    code: "sbr",
  },
  "Angelic Wings": { index: "Angelic Wings", rarity: 7, lvl: 17, code: "amu" },
  "Arcanna's Deathwand": {
    index: "Arcanna's Deathwand",
    rarity: 7,
    lvl: 20,
    code: "wst",
  },
  "Arcanna's Flesh": {
    index: "Arcanna's Flesh",
    rarity: 7,
    lvl: 20,
    code: "ltp",
  },
  "Arcanna's Head": {
    index: "Arcanna's Head",
    rarity: 7,
    lvl: 20,
    code: "skp",
  },
  "Arcanna's Sign": {
    index: "Arcanna's Sign",
    rarity: 1,
    lvl: 20,
    code: "amu",
  },
  "Arctic Binding": { index: "Arctic Binding", rarity: 7, lvl: 3, code: "vbl" },
  "Arctic Furs": { index: "Arctic Furs", rarity: 7, lvl: 3, code: "qui" },
  "Arctic Horn": { index: "Arctic Horn", rarity: 7, lvl: 3, code: "swb" },
  "Arctic Mitts": { index: "Arctic Mitts", rarity: 7, lvl: 3, code: "tgl" },
  "Berserker's Hatchet": {
    index: "Berserker's Hatchet",
    rarity: 7,
    lvl: 5,
    code: "2ax",
  },
  "Berserker's Hauberk": {
    index: "Berserker's Hauberk",
    rarity: 7,
    lvl: 5,
    code: "spl",
  },
  "Berserker's Headgear": {
    index: "Berserker's Headgear",
    rarity: 7,
    lvl: 5,
    code: "hlm",
  },
  "Bul-Kathos' Sacred Charge": {
    index: "Bul-Kathos' Sacred Charge",
    rarity: 7,
    lvl: 50,
    code: "7gd",
  },
  "Bul-Kathos' Tribal Guardian": {
    index: "Bul-Kathos' Tribal Guardian",
    rarity: 7,
    lvl: 50,
    code: "7wd",
  },
  "Cathan's Mesh": { index: "Cathan's Mesh", rarity: 7, lvl: 15, code: "chn" },
  "Cathan's Rule": { index: "Cathan's Rule", rarity: 7, lvl: 15, code: "bst" },
  "Cathan's Seal": { index: "Cathan's Seal", rarity: 7, lvl: 15, code: "rin" },
  "Cathan's Sigil": {
    index: "Cathan's Sigil",
    rarity: 7,
    lvl: 15,
    code: "amu",
  },
  "Cathan's Visage": {
    index: "Cathan's Visage",
    rarity: 7,
    lvl: 15,
    code: "msk",
  },
  "Civerb's Cudgel": {
    index: "Civerb's Cudgel",
    rarity: 7,
    lvl: 13,
    code: "gsc",
  },
  "Civerb's Icon": { index: "Civerb's Icon", rarity: 7, lvl: 13, code: "amu" },
  "Civerb's Ward": { index: "Civerb's Ward", rarity: 7, lvl: 13, code: "lrg" },
  "Cleglaw's Claw": { index: "Cleglaw's Claw", rarity: 7, lvl: 6, code: "sml" },
  "Cleglaw's Pincers": {
    index: "Cleglaw's Pincers",
    rarity: 7,
    lvl: 6,
    code: "mgl",
  },
  "Cleglaw's Tooth": {
    index: "Cleglaw's Tooth",
    rarity: 7,
    lvl: 6,
    code: "lsd",
  },
  "Cow King's Hide": {
    index: "Cow King's Hide",
    rarity: 7,
    lvl: 20,
    code: "stu",
  },
  "Cow King's Hoofs": {
    index: "Cow King's Hoofs",
    rarity: 7,
    lvl: 20,
    code: "vbt",
  },
  "Cow King's Horns": {
    index: "Cow King's Horns",
    rarity: 7,
    lvl: 20,
    code: "xap",
  },
  Credendum: { index: "Credendum", rarity: 7, lvl: 39, code: "umc" },
  "Dangoon's Teaching": {
    index: "Dangoon's Teaching",
    rarity: 7,
    lvl: 55,
    code: "7ma",
  },
  "Death's Guard": { index: "Death's Guard", rarity: 7, lvl: 8, code: "lbl" },
  "Death's Hand": { index: "Death's Hand", rarity: 7, lvl: 8, code: "lgl" },
  "Death's Touch": { index: "Death's Touch", rarity: 7, lvl: 8, code: "wsd" },
  "Griswold's Heart": {
    index: "Griswold's Heart",
    rarity: 7,
    lvl: 44,
    code: "xar",
  },
  "Griswold's Honor": {
    index: "Griswold's Honor",
    rarity: 7,
    lvl: 44,
    code: "paf",
  },
  "Griswold's Valor": {
    index: "Griswold's Valor",
    rarity: 7,
    lvl: 44,
    code: "urn",
  },
  "Griswolds's Redemption": {
    index: "Griswolds's Redemption",
    rarity: 7,
    lvl: 44,
    code: "7ws",
  },
  "Guillaume's Face": {
    index: "Guillaume's Face",
    rarity: 7,
    lvl: 41,
    code: "xhm",
  },
  "Haemosu's Adament": {
    index: "Haemosu's Adament",
    rarity: 7,
    lvl: 55,
    code: "xrs",
  },
  "Heaven's Taebaek": {
    index: "Heaven's Taebaek",
    rarity: 7,
    lvl: 55,
    code: "uts",
  },
  "Hsarus' Iron Fist": {
    index: "Hsarus' Iron Fist",
    rarity: 7,
    lvl: 4,
    code: "buc",
  },
  "Hsarus' Iron Heel": {
    index: "Hsarus' Iron Heel",
    rarity: 7,
    lvl: 4,
    code: "mbt",
  },
  "Hsarus' Iron Stay": {
    index: "Hsarus' Iron Stay",
    rarity: 7,
    lvl: 4,
    code: "mbl",
  },
  "Hwanin's Justice": {
    index: "Hwanin's Justice",
    rarity: 7,
    lvl: 28,
    code: "9vo",
  },
  "Hwanin's Refuge": {
    index: "Hwanin's Refuge",
    rarity: 7,
    lvl: 28,
    code: "xcl",
  },
  "Hwanin's Seal": { index: "Hwanin's Seal", rarity: 7, lvl: 28, code: "mbl" },
  "Hwanin's Splendor": {
    index: "Hwanin's Splendor",
    rarity: 7,
    lvl: 28,
    code: "xrn",
  },
  "Immortal King's Detail": {
    index: "Immortal King's Detail",
    rarity: 7,
    lvl: 37,
    code: "zhb",
  },
  "Immortal King's Forge": {
    index: "Immortal King's Forge",
    rarity: 7,
    lvl: 37,
    code: "xhg",
  },
  "Immortal King's Pillar": {
    index: "Immortal King's Pillar",
    rarity: 7,
    lvl: 37,
    code: "xhb",
  },
  "Immortal King's Soul Cage": {
    index: "Immortal King's Soul Cage",
    rarity: 7,
    lvl: 37,
    code: "uar",
  },
  "Immortal King's Stone Crusher": {
    index: "Immortal King's Stone Crusher",
    rarity: 7,
    lvl: 37,
    code: "7m7",
  },
  "Immortal King's Will": {
    index: "Immortal King's Will",
    rarity: 7,
    lvl: 37,
    code: "ba5",
  },
  "Infernal Cranium": {
    index: "Infernal Cranium",
    rarity: 7,
    lvl: 7,
    code: "cap",
  },
  "Infernal Sign": { index: "Infernal Sign", rarity: 7, lvl: 7, code: "tbl" },
  "Infernal Torch": { index: "Infernal Torch", rarity: 7, lvl: 7, code: "gwn" },
  "Iratha's Coil": { index: "Iratha's Coil", rarity: 7, lvl: 21, code: "crn" },
  "Iratha's Collar": {
    index: "Iratha's Collar",
    rarity: 7,
    lvl: 21,
    code: "amu",
  },
  "Iratha's Cord": { index: "Iratha's Cord", rarity: 7, lvl: 21, code: "tbl" },
  "Iratha's Cuff": { index: "Iratha's Cuff", rarity: 7, lvl: 21, code: "tgl" },
  "Isenhart's Case": {
    index: "Isenhart's Case",
    rarity: 7,
    lvl: 11,
    code: "brs",
  },
  "Isenhart's Horns": {
    index: "Isenhart's Horns",
    rarity: 7,
    lvl: 11,
    code: "fhl",
  },
  "Isenhart's Lightbrand": {
    index: "Isenhart's Lightbrand",
    rarity: 7,
    lvl: 11,
    code: "bsd",
  },
  "Isenhart's Parry": {
    index: "Isenhart's Parry",
    rarity: 7,
    lvl: 11,
    code: "gts",
  },
  "Laying of Hands": {
    index: "Laying of Hands",
    rarity: 7,
    lvl: 39,
    code: "ulg",
  },
  "M'avina's Caster": {
    index: "M'avina's Caster",
    rarity: 7,
    lvl: 21,
    code: "amc",
  },
  "M'avina's Embrace": {
    index: "M'avina's Embrace",
    rarity: 7,
    lvl: 21,
    code: "uld",
  },
  "M'avina's Icy Clutch": {
    index: "M'avina's Icy Clutch",
    rarity: 7,
    lvl: 21,
    code: "xtg",
  },
  "M'avina's Tenet": {
    index: "M'avina's Tenet",
    rarity: 7,
    lvl: 21,
    code: "zvb",
  },
  "M'avina's True Sight": {
    index: "M'avina's True Sight",
    rarity: 7,
    lvl: 21,
    code: "ci3",
  },
  "Magnus' Skin": { index: "Magnus' Skin", rarity: 7, lvl: 41, code: "xvg" },
  "McAuley's Paragon": {
    index: "McAuley's Paragon",
    rarity: 3,
    lvl: 20,
    code: "cap",
  },
  "McAuley's Riprap": {
    index: "McAuley's Riprap",
    rarity: 7,
    lvl: 20,
    code: "vbt",
  },
  "McAuley's Superstition": {
    index: "McAuley's Superstition",
    rarity: 7,
    lvl: 20,
    code: "bwn",
  },
  "McAuley's Taboo": {
    index: "McAuley's Taboo",
    rarity: 7,
    lvl: 20,
    code: "vgl",
  },
  "Milabrega's Diadem": {
    index: "Milabrega's Diadem",
    rarity: 7,
    lvl: 23,
    code: "crn",
  },
  "Milabrega's Orb": {
    index: "Milabrega's Orb",
    rarity: 7,
    lvl: 23,
    code: "kit",
  },
  "Milabrega's Robe": {
    index: "Milabrega's Robe",
    rarity: 7,
    lvl: 23,
    code: "aar",
  },
  "Milabrega's Rod": {
    index: "Milabrega's Rod",
    rarity: 7,
    lvl: 23,
    code: "wsp",
  },
  "Naj's Circlet": { index: "Naj's Circlet", rarity: 7, lvl: 43, code: "ci0" },
  "Naj's Light Plate": {
    index: "Naj's Light Plate",
    rarity: 7,
    lvl: 43,
    code: "ult",
  },
  "Naj's Puzzler": { index: "Naj's Puzzler", rarity: 7, lvl: 43, code: "6cs" },
  "Natalya's Mark": {
    index: "Natalya's Mark",
    rarity: 7,
    lvl: 22,
    code: "7qr",
  },
  "Natalya's Shadow": {
    index: "Natalya's Shadow",
    rarity: 7,
    lvl: 22,
    code: "ucl",
  },
  "Natalya's Soul": {
    index: "Natalya's Soul",
    rarity: 7,
    lvl: 22,
    code: "xmb",
  },
  "Natalya's Totem": {
    index: "Natalya's Totem",
    rarity: 7,
    lvl: 22,
    code: "xh9",
  },
  "Ondal's Almighty": {
    index: "Ondal's Almighty",
    rarity: 7,
    lvl: 55,
    code: "uhm",
  },
  "Rite of Passage": {
    index: "Rite of Passage",
    rarity: 7,
    lvl: 39,
    code: "xlb",
  },
  "Sazabi's Cobalt Redeemer": {
    index: "Sazabi's Cobalt Redeemer",
    rarity: 7,
    lvl: 34,
    code: "7ls",
  },
  "Sazabi's Ghost Liberator": {
    index: "Sazabi's Ghost Liberator",
    rarity: 7,
    lvl: 34,
    code: "upl",
  },
  "Sazabi's Mental Sheath": {
    index: "Sazabi's Mental Sheath",
    rarity: 7,
    lvl: 34,
    code: "xhl",
  },
  "Sigon's Gage": { index: "Sigon's Gage", rarity: 7, lvl: 9, code: "hgl" },
  "Sigon's Guard": { index: "Sigon's Guard", rarity: 7, lvl: 9, code: "tow" },
  "Sigon's Sabot": { index: "Sigon's Sabot", rarity: 7, lvl: 9, code: "hbt" },
  "Sigon's Shelter": {
    index: "Sigon's Shelter",
    rarity: 7,
    lvl: 9,
    code: "gth",
  },
  "Sigon's Visor": { index: "Sigon's Visor", rarity: 7, lvl: 9, code: "ghm" },
  "Sigon's Wrap": { index: "Sigon's Wrap", rarity: 7, lvl: 9, code: "hbl" },
  "Spiritual Custodian": {
    index: "Spiritual Custodian",
    rarity: 7,
    lvl: 39,
    code: "uui",
  },
  "Tal Rasha's Adjudication": {
    index: "Tal Rasha's Adjudication",
    rarity: 1,
    lvl: 26,
    code: "amu",
  },
  "Tal Rasha's Fire-Spun Cloth": {
    index: "Tal Rasha's Fire-Spun Cloth",
    rarity: 7,
    lvl: 26,
    code: "zmb",
  },
  "Tal Rasha's Horadric Crest": {
    index: "Tal Rasha's Horadric Crest",
    rarity: 7,
    lvl: 26,
    code: "xsk",
  },
  "Tal Rasha's Howling Wind": {
    index: "Tal Rasha'sHowling Wind",
    rarity: 7,
    lvl: 26,
    code: "uth",
  },
  "Tal Rasha's Lidless Eye": {
    index: "Tal Rasha's Lidless Eye",
    rarity: 7,
    lvl: 26,
    code: "oba",
  },
  "Tancred's Crowbill": {
    index: "Tancred's Crowbill",
    rarity: 7,
    lvl: 27,
    code: "mpi",
  },
  "Tancred's Hobnails": {
    index: "Tancred's Hobnails",
    rarity: 7,
    lvl: 27,
    code: "lbt",
  },
  "Tancred's Skull": {
    index: "Tancred's Skull",
    rarity: 7,
    lvl: 27,
    code: "bhm",
  },
  "Tancred's Spine": {
    index: "Tancred's Spine",
    rarity: 7,
    lvl: 27,
    code: "ful",
  },
  "Tancred's Weird": {
    index: "Tancred's Weird",
    rarity: 7,
    lvl: 27,
    code: "amu",
  },
  "Telling of Beads": {
    index: "Telling of Beads",
    rarity: 1,
    lvl: 39,
    code: "amu",
  },
  "Trang-Oul's Claws": {
    index: "Trang-Oul's Claws",
    rarity: 7,
    lvl: 32,
    code: "xmg",
  },
  "Trang-Oul's Girth": {
    index: "Trang-Oul's Girth",
    rarity: 7,
    lvl: 32,
    code: "utc",
  },
  "Trang-Oul's Guise": {
    index: "Trang-Oul's Guise",
    rarity: 7,
    lvl: 32,
    code: "uh9",
  },
  "Trang-Oul's Scales": {
    index: "Trang-Oul's Scales",
    rarity: 7,
    lvl: 32,
    code: "xul",
  },
  "Trang-Oul's Wing": {
    index: "Trang-Oul's Wing",
    rarity: 7,
    lvl: 32,
    code: "ne9",
  },
  "Vidala's Ambush": {
    index: "Vidala's Ambush",
    rarity: 7,
    lvl: 19,
    code: "lea",
  },
  "Vidala's Barb": { index: "Vidala's Barb", rarity: 7, lvl: 19, code: "lbb" },
  "Vidala's Fetlock": {
    index: "Vidala's Fetlock",
    rarity: 7,
    lvl: 19,
    code: "tbt",
  },
  "Vidala's Snare": {
    index: "Vidala's Snare",
    rarity: 7,
    lvl: 19,
    code: "amu",
  },
  "Wihtstan's Guard": {
    index: "Wihtstan's Guard",
    rarity: 7,
    lvl: 41,
    code: "xml",
  },
  "Wilhelm's Pride": {
    index: "Wilhelm's Pride",
    rarity: 7,
    lvl: 41,
    code: "ztb",
  },
};

export const UniqueBaseLookup: UniqueSetBaseLookupType = {
  hax: [{ index: "The Gnasher", rarity: 1, lvl: 7, code: "hax" }],
  axe: [{ index: "Deathspade", rarity: 1, lvl: 12, code: "axe" }],
  "2ax": [{ index: "Bladebone", rarity: 1, lvl: 20, code: "2ax" }],
  mpi: [{ index: "Mindrend", rarity: 1, lvl: 28, code: "mpi" }],
  wax: [{ index: "Rakescar", rarity: 1, lvl: 36, code: "wax" }],
  lax: [{ index: "Fechmars Axe", rarity: 1, lvl: 11, code: "lax" }],
  bax: [{ index: "Goreshovel", rarity: 1, lvl: 19, code: "bax" }],
  btx: [{ index: "The Chieftan", rarity: 1, lvl: 26, code: "btx" }],
  gax: [{ index: "Brainhew", rarity: 1, lvl: 34, code: "gax" }],
  gix: [{ index: "The Humongous", rarity: 1, lvl: 39, code: "gix" }],
  wnd: [{ index: "Iros Torch", rarity: 1, lvl: 7, code: "wnd" }],
  ywn: [{ index: "Maelstromwrath", rarity: 1, lvl: 19, code: "ywn" }],
  bwn: [{ index: "Gravenspine", rarity: 1, lvl: 27, code: "bwn" }],
  gwn: [{ index: "Umes Lament", rarity: 1, lvl: 38, code: "gwn" }],
  clb: [{ index: "Felloak", rarity: 1, lvl: 4, code: "clb" }],
  scp: [{ index: "Knell Striker", rarity: 1, lvl: 7, code: "scp" }],
  gsc: [{ index: "Rusthandle", rarity: 1, lvl: 23, code: "gsc" }],
  wsp: [{ index: "Stormeye", rarity: 1, lvl: 31, code: "wsp" }],
  spc: [{ index: "Stoutnail", rarity: 1, lvl: 7, code: "spc" }],
  mac: [{ index: "Crushflange", rarity: 1, lvl: 12, code: "mac" }],
  mst: [{ index: "Bloodrise", rarity: 1, lvl: 20, code: "mst" }],
  fla: [
    { index: "The Generals Tan Do Li Ga", rarity: 1, lvl: 28, code: "fla" },
  ],
  whm: [{ index: "Ironstone", rarity: 1, lvl: 36, code: "whm" }],
  mau: [{ index: "Bonesob", rarity: 1, lvl: 32, code: "mau" }],
  gma: [{ index: "Steeldriver", rarity: 1, lvl: 39, code: "gma" }],
  ssd: [{ index: "Rixots Keen", rarity: 1, lvl: 3, code: "ssd" }],
  scm: [{ index: "Blood Crescent", rarity: 1, lvl: 10, code: "scm" }],
  sbr: [{ index: "Krintizs Skewer", rarity: 1, lvl: 14, code: "sbr" }],
  flc: [{ index: "Gleamscythe", rarity: 1, lvl: 18, code: "flc" }],
  bsd: [{ index: "Griswolds Edge", rarity: 1, lvl: 23, code: "bsd" }],
  lsd: [{ index: "Hellplague", rarity: 1, lvl: 30, code: "lsd" }],
  wsd: [{ index: "Culwens Point", rarity: 1, lvl: 39, code: "wsd" }],
  "2hs": [{ index: "Shadowfang", rarity: 1, lvl: 16, code: "2hs" }],
  clm: [{ index: "Soulflay", rarity: 1, lvl: 26, code: "clm" }],
  gis: [{ index: "Kinemils Awl", rarity: 1, lvl: 31, code: "gis" }],
  bsw: [{ index: "Blacktongue", rarity: 1, lvl: 35, code: "bsw" }],
  flb: [{ index: "Ripsaw", rarity: 1, lvl: 35, code: "flb" }],
  gsd: [{ index: "The Patriarch", rarity: 1, lvl: 39, code: "gsd" }],
  dgr: [{ index: "Gull", rarity: 1, lvl: 6, code: "dgr" }],
  dir: [{ index: "The Diggler", rarity: 1, lvl: 15, code: "dir" }],
  kri: [{ index: "The Jade Tan Do", rarity: 1, lvl: 26, code: "kri" }],
  bld: [{ index: "Irices Shard", rarity: 1, lvl: 34, code: "bld" }],
  spr: [{ index: "The Dragon Chang", rarity: 1, lvl: 11, code: "spr" }],
  tri: [{ index: "Razortine", rarity: 1, lvl: 16, code: "tri" }],
  brn: [{ index: "Bloodthief", rarity: 1, lvl: 23, code: "brn" }],
  spt: [{ index: "Lance of Yaggai", rarity: 1, lvl: 30, code: "spt" }],
  pik: [{ index: "The Tannr Gorerod", rarity: 1, lvl: 36, code: "pik" }],
  bar: [{ index: "Dimoaks Hew", rarity: 1, lvl: 11, code: "bar" }],
  vou: [{ index: "Steelgoad", rarity: 1, lvl: 19, code: "vou" }],
  scy: [{ index: "Soul Harvest", rarity: 1, lvl: 26, code: "scy" }],
  pax: [{ index: "The Battlebranch", rarity: 1, lvl: 34, code: "pax" }],
  hal: [{ index: "Woestave", rarity: 1, lvl: 38, code: "hal" }],
  wsc: [{ index: "The Grim Reaper", rarity: 1, lvl: 39, code: "wsc" }],
  sst: [{ index: "Bane Ash", rarity: 1, lvl: 7, code: "sst" }],
  lst: [{ index: "Serpent Lord", rarity: 1, lvl: 12, code: "lst" }],
  cst: [{ index: "Lazarus Spire", rarity: 1, lvl: 24, code: "cst" }],
  bst: [{ index: "The Salamander", rarity: 1, lvl: 28, code: "bst" }],
  wst: [{ index: "The Iron Jang Bong", rarity: 1, lvl: 38, code: "wst" }],
  sbw: [{ index: "Pluckeye", rarity: 1, lvl: 10, code: "sbw" }],
  hbw: [{ index: "Witherstring", rarity: 1, lvl: 18, code: "hbw" }],
  lbw: [{ index: "Rimeraven", rarity: 1, lvl: 20, code: "lbw" }],
  cbw: [{ index: "Piercerib", rarity: 1, lvl: 27, code: "cbw" }],
  sbb: [{ index: "Pullspite", rarity: 1, lvl: 34, code: "sbb" }],
  lbb: [{ index: "Wizendraw", rarity: 1, lvl: 35, code: "lbb" }],
  swb: [{ index: "Hellclap", rarity: 1, lvl: 36, code: "swb" }],
  lwb: [{ index: "Blastbark", rarity: 1, lvl: 38, code: "lwb" }],
  lxb: [{ index: "Leadcrow", rarity: 1, lvl: 12, code: "lxb" }],
  mxb: [{ index: "Ichorsting", rarity: 1, lvl: 24, code: "mxb" }],
  hxb: [{ index: "Hellcast", rarity: 1, lvl: 36, code: "hxb" }],
  rxb: [{ index: "Doomspittle", rarity: 1, lvl: 38, code: "rxb" }],
  cap: [{ index: "War Bonnet", rarity: 1, lvl: 4, code: "cap" }],
  skp: [{ index: "Tarnhelm", rarity: 1, lvl: 20, code: "skp" }],
  hlm: [{ index: "Coif of Glory", rarity: 1, lvl: 19, code: "hlm" }],
  fhl: [{ index: "Duskdeep", rarity: 1, lvl: 23, code: "fhl" }],
  bhm: [{ index: "Wormskull", rarity: 1, lvl: 28, code: "bhm" }],
  ghm: [{ index: "Howltusk", rarity: 1, lvl: 34, code: "ghm" }],
  crn: [{ index: "Undead Crown", rarity: 1, lvl: 39, code: "crn" }],
  msk: [{ index: "The Face of Horror", rarity: 1, lvl: 27, code: "msk" }],
  qui: [{ index: "Greyform", rarity: 1, lvl: 10, code: "qui" }],
  lea: [{ index: "Blinkbats Form", rarity: 1, lvl: 16, code: "lea" }],
  hla: [{ index: "The Centurion", rarity: 1, lvl: 19, code: "hla" }],
  stu: [{ index: "Twitchthroe", rarity: 1, lvl: 22, code: "stu" }],
  rng: [{ index: "Darkglow", rarity: 1, lvl: 19, code: "rng" }],
  scl: [{ index: "Hawkmail", rarity: 1, lvl: 20, code: "scl" }],
  chn: [{ index: "Sparking Mail", rarity: 1, lvl: 23, code: "chn" }],
  brs: [{ index: "Venomsward", rarity: 1, lvl: 27, code: "brs" }],
  spl: [{ index: "Iceblink", rarity: 1, lvl: 30, code: "spl" }],
  plt: [{ index: "Boneflesh", rarity: 1, lvl: 35, code: "plt" }],
  fld: [{ index: "Rockfleece", rarity: 1, lvl: 38, code: "fld" }],
  gth: [{ index: "Rattlecage", rarity: 1, lvl: 39, code: "gth" }],
  ful: [{ index: "Goldskin", rarity: 1, lvl: 38, code: "ful" }],
  aar: [{ index: "Victors Silk", rarity: 1, lvl: 38, code: "aar" }],
  ltp: [{ index: "Heavenly Garb", rarity: 1, lvl: 39, code: "ltp" }],
  buc: [{ index: "Pelta Lunata", rarity: 1, lvl: 3, code: "buc" }],
  sml: [{ index: "Umbral Disk", rarity: 1, lvl: 12, code: "sml" }],
  lrg: [{ index: "Stormguild", rarity: 1, lvl: 18, code: "lrg" }],
  bsh: [{ index: "Wall of the Eyeless", rarity: 1, lvl: 27, code: "bsh" }],
  spk: [{ index: "Swordback Hold", rarity: 1, lvl: 20, code: "spk" }],
  kit: [{ index: "Steelclash", rarity: 1, lvl: 23, code: "kit" }],
  tow: [{ index: "Bverrit Keep", rarity: 1, lvl: 26, code: "tow" }],
  gts: [{ index: "The Ward", rarity: 1, lvl: 35, code: "gts" }],
  lgl: [{ index: "The Hand of Broc", rarity: 1, lvl: 7, code: "lgl" }],
  vgl: [{ index: "Bloodfist", rarity: 1, lvl: 12, code: "vgl" }],
  mgl: [{ index: "Chance Guards", rarity: 1, lvl: 20, code: "mgl" }],
  tgl: [{ index: "Magefist", rarity: 1, lvl: 31, code: "tgl" }],
  hgl: [{ index: "Frostburn", rarity: 1, lvl: 39, code: "hgl" }],
  lbt: [{ index: "Hotspur", rarity: 1, lvl: 7, code: "lbt" }],
  vbt: [{ index: "Gorefoot", rarity: 1, lvl: 12, code: "vbt" }],
  mbt: [{ index: "Treads of Cthon", rarity: 1, lvl: 20, code: "mbt" }],
  tbt: [{ index: "Goblin Toe", rarity: 1, lvl: 30, code: "tbt" }],
  hbt: [{ index: "Tearhaunch", rarity: 1, lvl: 39, code: "hbt" }],
  lbl: [{ index: "Lenyms Cord", rarity: 1, lvl: 10, code: "lbl" }],
  vbl: [{ index: "Snakecord", rarity: 1, lvl: 16, code: "vbl" }],
  mbl: [{ index: "Nightsmoke", rarity: 1, lvl: 27, code: "mbl" }],
  tbl: [{ index: "Goldwrap", rarity: 1, lvl: 36, code: "tbl" }],
  hbl: [{ index: "Bladebuckle", rarity: 1, lvl: 39, code: "hbl" }],
  amu: [
    { index: "Nokozan Relic", rarity: 20, lvl: 14, code: "amu" },
    { index: "The Eye of Etlich", rarity: 5, lvl: 20, code: "amu" },
    { index: "The Mahim-Oak Curio", rarity: 10, lvl: 34, code: "amu" },
    { index: "The Cat's Eye", rarity: 5, lvl: 58, code: "amu" },
    { index: "The Rising Sun", rarity: 5, lvl: 73, code: "amu" },
    { index: "Crescent Moon", rarity: 5, lvl: 58, code: "amu" },
    { index: "Mara's Kaleidoscope", rarity: 5, lvl: 80, code: "amu" },
    { index: "Atma's Scarab", rarity: 5, lvl: 60, code: "amu" },
    { index: "Highlord's Wrath", rarity: 5, lvl: 73, code: "amu" },
    { index: "Saracen's Chance", rarity: 5, lvl: 55, code: "amu" },
    { index: "Seraph's Hymn", rarity: 3, lvl: 73, code: "amu" },
    { index: "Metalgrid", rarity: 2, lvl: 85, code: "amu" },
  ],
  rin: [
    { index: "Nagelring", rarity: 15, lvl: 10, code: "rin" },
    { index: "Manald Heal", rarity: 15, lvl: 20, code: "rin" },
    { index: "The Stone of Jordan", rarity: 1, lvl: 39, code: "rin" },
    { index: "Bul Katho's Wedding Band", rarity: 1, lvl: 66, code: "rin" },
    { index: "Dwarf Star", rarity: 10, lvl: 53, code: "rin" },
    { index: "Raven Frost", rarity: 10, lvl: 53, code: "rin" },
    { index: "Nature's Peace", rarity: 3, lvl: 77, code: "rin" },
    { index: "Wisp", rarity: 1, lvl: 84, code: "rin" },
    { index: "Carrion Wind", rarity: 3, lvl: 68, code: "rin" },
  ],
  vip: [{ index: "Amulet of the Viper", rarity: 1, lvl: 0, code: "vip" }],
  msf: [{ index: "Staff of Kings", rarity: 1, lvl: 0, code: "msf" }],
  hst: [{ index: "Horadric Staff", rarity: 1, lvl: 0, code: "hst" }],
  hfh: [{ index: "HellForge Hammer", rarity: 1, lvl: 0, code: "hfh" }],
  qf1: [{ index: "KhalimFlail", rarity: 1, lvl: 0, code: "qf1" }],
  qf2: [{ index: "SuperKhalimFlail", rarity: 1, lvl: 0, code: "qf2" }],
  "9ha": [{ index: "Coldkill", rarity: 1, lvl: 44, code: "9ha" }],
  "9ax": [{ index: "Butcher's Pupil", rarity: 1, lvl: 47, code: "9ax" }],
  "92a": [{ index: "Islestrike", rarity: 1, lvl: 51, code: "92a" }],
  "9mp": [{ index: "Pompe's Wrath", rarity: 1, lvl: 53, code: "9mp" }],
  "9wa": [{ index: "Guardian Naga", rarity: 1, lvl: 56, code: "9wa" }],
  "9la": [{ index: "Warlord's Trust", rarity: 1, lvl: 43, code: "9la" }],
  "9ba": [{ index: "Spellsteel", rarity: 1, lvl: 47, code: "9ba" }],
  "9bt": [{ index: "Stormrider", rarity: 1, lvl: 49, code: "9bt" }],
  "9ga": [{ index: "Boneslayer Blade", rarity: 1, lvl: 50, code: "9ga" }],
  "9gi": [{ index: "The Minataur", rarity: 1, lvl: 53, code: "9gi" }],
  "9wn": [{ index: "Suicide Branch", rarity: 1, lvl: 41, code: "9wn" }],
  "9yw": [{ index: "Carin Shard", rarity: 1, lvl: 43, code: "9yw" }],
  "9bw": [{ index: "Arm of King Leoric", rarity: 1, lvl: 44, code: "9bw" }],
  "9gw": [{ index: "Blackhand Key", rarity: 1, lvl: 49, code: "9gw" }],
  "9cl": [{ index: "Dark Clan Crusher", rarity: 1, lvl: 42, code: "9cl" }],
  "9sc": [{ index: "Zakarum's Hand", rarity: 1, lvl: 45, code: "9sc" }],
  "9qs": [{ index: "The Fetid Sprinkler", rarity: 1, lvl: 46, code: "9qs" }],
  "9ws": [{ index: "Hand of Blessed Light", rarity: 1, lvl: 50, code: "9ws" }],
  "9sp": [{ index: "Fleshrender", rarity: 1, lvl: 46, code: "9sp" }],
  "9ma": [{ index: "Sureshrill Frost", rarity: 1, lvl: 47, code: "9ma" }],
  "9mt": [{ index: "Moonfall", rarity: 1, lvl: 50, code: "9mt" }],
  "9fl": [{ index: "Baezil's Vortex", rarity: 1, lvl: 53, code: "9fl" }],
  "9wh": [{ index: "Earthshaker", rarity: 1, lvl: 51, code: "9wh" }],
  "9m9": [{ index: "Bloodtree Stump", rarity: 1, lvl: 56, code: "9m9" }],
  "9gm": [{ index: "The Gavel of Pain", rarity: 1, lvl: 53, code: "9gm" }],
  "9ss": [{ index: "Bloodletter", rarity: 1, lvl: 38, code: "9ss" }],
  "9sm": [{ index: "Coldsteel Eye", rarity: 1, lvl: 39, code: "9sm" }],
  "9sb": [{ index: "Hexfire", rarity: 1, lvl: 41, code: "9sb" }],
  "9fc": [{ index: "Blade of Ali Baba", rarity: 1, lvl: 43, code: "9fc" }],
  "9cr": [{ index: "Ginther's Rift", rarity: 1, lvl: 45, code: "9cr" }],
  "9bs": [{ index: "Headstriker", rarity: 1, lvl: 47, code: "9bs" }],
  "9ls": [{ index: "Plague Bearer", rarity: 1, lvl: 49, code: "9ls" }],
  "9wd": [{ index: "The Atlantian", rarity: 1, lvl: 50, code: "9wd" }],
  "92h": [{ index: "Crainte Vomir", rarity: 1, lvl: 50, code: "92h" }],
  "9cm": [{ index: "Bing Sz Wang", rarity: 1, lvl: 51, code: "9cm" }],
  "9gs": [{ index: "The Vile Husk", rarity: 1, lvl: 52, code: "9gs" }],
  "9b9": [{ index: "Cloudcrack", rarity: 1, lvl: 53, code: "9b9" }],
  "9fb": [{ index: "Todesfaelle Flamme", rarity: 1, lvl: 54, code: "9fb" }],
  "9gd": [{ index: "Swordguard", rarity: 1, lvl: 55, code: "9gd" }],
  "9dg": [{ index: "Spineripper", rarity: 1, lvl: 40, code: "9dg" }],
  "9di": [{ index: "Heart Carver", rarity: 1, lvl: 44, code: "9di" }],
  "9kr": [{ index: "Blackbog's Sharp", rarity: 1, lvl: 46, code: "9kr" }],
  "9bl": [{ index: "Stormspike", rarity: 1, lvl: 49, code: "9bl" }],
  "9sr": [{ index: "The Impaler", rarity: 1, lvl: 39, code: "9sr" }],
  "9tr": [{ index: "Kelpie Snare", rarity: 1, lvl: 41, code: "9tr" }],
  "9br": [{ index: "Soulfeast Tine", rarity: 1, lvl: 43, code: "9br" }],
  "9st": [{ index: "Hone Sundan", rarity: 1, lvl: 45, code: "9st" }],
  "9p9": [{ index: "Spire of Honor", rarity: 1, lvl: 47, code: "9p9" }],
  "9b7": [{ index: "The Meat Scraper", rarity: 1, lvl: 49, code: "9b7" }],
  "9vo": [{ index: "Blackleach Blade", rarity: 1, lvl: 50, code: "9vo" }],
  "9s8": [{ index: "Athena's Wrath", rarity: 1, lvl: 50, code: "9s8" }],
  "9pa": [{ index: "Pierre Tombale Couant", rarity: 1, lvl: 51, code: "9pa" }],
  "9h9": [{ index: "Husoldal Evo", rarity: 1, lvl: 52, code: "9h9" }],
  "9wc": [{ index: "Grim's Burning Dead", rarity: 1, lvl: 52, code: "9wc" }],
  "8ss": [{ index: "Razorswitch", rarity: 1, lvl: 36, code: "8ss" }],
  "8ls": [{ index: "Ribcracker", rarity: 1, lvl: 39, code: "8ls" }],
  "8cs": [{ index: "Chromatic Ire", rarity: 1, lvl: 43, code: "8cs" }],
  "8bs": [{ index: "Warpspear", rarity: 1, lvl: 47, code: "8bs" }],
  "8ws": [{ index: "Skullcollector", rarity: 1, lvl: 49, code: "8ws" }],
  "8sb": [{ index: "Skystrike", rarity: 1, lvl: 36, code: "8sb" }],
  "8hb": [{ index: "Riphook", rarity: 1, lvl: 39, code: "8hb" }],
  "8lb": [{ index: "Kuko Shakaku", rarity: 1, lvl: 41, code: "8lb" }],
  "8cb": [{ index: "Endlesshail", rarity: 1, lvl: 44, code: "8cb" }],
  "8s8": [{ index: "Whichwild String", rarity: 1, lvl: 47, code: "8s8" }],
  "8l8": [{ index: "Cliffkiller", rarity: 1, lvl: 49, code: "8l8" }],
  "8sw": [{ index: "Magewrath", rarity: 1, lvl: 51, code: "8sw" }],
  "8lw": [{ index: "Godstrike Arch", rarity: 1, lvl: 54, code: "8lw" }],
  "8lx": [{ index: "Langer Briser", rarity: 1, lvl: 40, code: "8lx" }],
  "8mx": [{ index: "Pus Spiter", rarity: 1, lvl: 44, code: "8mx" }],
  "8hx": [{ index: "Buriza-Do Kyanon", rarity: 1, lvl: 59, code: "8hx" }],
  "8rx": [{ index: "Demon Machine", rarity: 1, lvl: 57, code: "8rx" }],
  xap: [{ index: "Peasent Crown", rarity: 1, lvl: 36, code: "xap" }],
  xkp: [{ index: "Rockstopper", rarity: 1, lvl: 39, code: "xkp" }],
  xlm: [{ index: "Stealskull", rarity: 1, lvl: 43, code: "xlm" }],
  xhl: [{ index: "Darksight Helm", rarity: 1, lvl: 46, code: "xhl" }],
  xhm: [{ index: "Valkiry Wing", rarity: 1, lvl: 52, code: "xhm" }],
  xrn: [{ index: "Crown of Thieves", rarity: 1, lvl: 57, code: "xrn" }],
  xsk: [{ index: "Blackhorn's Face", rarity: 1, lvl: 49, code: "xsk" }],
  xh9: [{ index: "Vampiregaze", rarity: 1, lvl: 49, code: "xh9" }],
  xui: [{ index: "The Spirit Shroud", rarity: 1, lvl: 36, code: "xui" }],
  xea: [{ index: "Skin of the Vipermagi", rarity: 1, lvl: 37, code: "xea" }],
  xla: [{ index: "Skin of the Flayerd One", rarity: 1, lvl: 39, code: "xla" }],
  xtu: [{ index: "Ironpelt", rarity: 1, lvl: 41, code: "xtu" }],
  xng: [{ index: "Spiritforge", rarity: 1, lvl: 43, code: "xng" }],
  xcl: [{ index: "Crow Caw", rarity: 1, lvl: 45, code: "xcl" }],
  xhn: [{ index: "Shaftstop", rarity: 1, lvl: 46, code: "xhn" }],
  xrs: [{ index: "Duriel's Shell", rarity: 1, lvl: 49, code: "xrs" }],
  xpl: [{ index: "Skullder's Ire", rarity: 1, lvl: 50, code: "xpl" }],
  xlt: [{ index: "Guardian Angel", rarity: 1, lvl: 53, code: "xlt" }],
  xld: [{ index: "Toothrow", rarity: 1, lvl: 56, code: "xld" }],
  xth: [{ index: "Atma's Wail", rarity: 1, lvl: 59, code: "xth" }],
  xul: [{ index: "Black Hades", rarity: 1, lvl: 61, code: "xul" }],
  xar: [{ index: "Corpsemourn", rarity: 1, lvl: 63, code: "xar" }],
  xtp: [{ index: "Que-Hegan's Wisdon", rarity: 1, lvl: 59, code: "xtp" }],
  xuc: [{ index: "Visceratuant", rarity: 1, lvl: 36, code: "xuc" }],
  xml: [{ index: "Mosers Blessed Circle", rarity: 1, lvl: 39, code: "xml" }],
  xrg: [{ index: "Stormchaser", rarity: 1, lvl: 43, code: "xrg" }],
  xit: [{ index: "Tiamat's Rebuke", rarity: 1, lvl: 46, code: "xit" }],
  xow: [{ index: "Kerke's Sanctuary", rarity: 1, lvl: 52, code: "xow" }],
  xts: [{ index: "Radimant's Sphere", rarity: 1, lvl: 58, code: "xts" }],
  xsh: [{ index: "Lidless Wall", rarity: 1, lvl: 49, code: "xsh" }],
  xpk: [{ index: "Lance Guard", rarity: 1, lvl: 43, code: "xpk" }],
  xlg: [{ index: "Venom Grip", rarity: 1, lvl: 37, code: "xlg" }],
  xvg: [{ index: "Gravepalm", rarity: 1, lvl: 39, code: "xvg" }],
  xmg: [{ index: "Ghoulhide", rarity: 1, lvl: 44, code: "xmg" }],
  xtg: [{ index: "Lavagout", rarity: 1, lvl: 50, code: "xtg" }],
  xhg: [{ index: "Hellmouth", rarity: 1, lvl: 55, code: "xhg" }],
  xlb: [{ index: "Infernostride", rarity: 1, lvl: 37, code: "xlb" }],
  xvb: [{ index: "Waterwalk", rarity: 1, lvl: 40, code: "xvb" }],
  xmb: [{ index: "Silkweave", rarity: 1, lvl: 44, code: "xmb" }],
  xtb: [{ index: "Wartraveler", rarity: 1, lvl: 50, code: "xtb" }],
  xhb: [{ index: "Gorerider", rarity: 1, lvl: 55, code: "xhb" }],
  zlb: [{ index: "String of Ears", rarity: 1, lvl: 37, code: "zlb" }],
  zvb: [{ index: "Razortail", rarity: 1, lvl: 39, code: "zvb" }],
  zmb: [{ index: "Gloomstrap", rarity: 1, lvl: 45, code: "zmb" }],
  ztb: [{ index: "Snowclash", rarity: 1, lvl: 49, code: "ztb" }],
  zhb: [{ index: "Thudergod's Vigor", rarity: 1, lvl: 55, code: "zhb" }],
  uap: [{ index: "Harlequin Crest", rarity: 1, lvl: 69, code: "uap" }],
  uhm: [
    { index: "Veil of Steel", rarity: 1, lvl: 77, code: "uhm" },
    { index: "Nightwing's Veil", rarity: 1, lvl: 75, code: "uhm" },
  ],
  utu: [{ index: "The Gladiator's Bane", rarity: 1, lvl: 85, code: "utu" }],
  upl: [{ index: "Arkaine's Valor", rarity: 1, lvl: 85, code: "upl" }],
  uml: [{ index: "Blackoak Shield", rarity: 1, lvl: 67, code: "uml" }],
  uit: [{ index: "Stormshield", rarity: 1, lvl: 77, code: "uit" }],
  "7bt": [{ index: "Hellslayer", rarity: 1, lvl: 71, code: "7bt" }],
  "7ga": [{ index: "Messerschmidt's Reaver", rarity: 1, lvl: 75, code: "7ga" }],
  "7mt": [{ index: "Baranar's Star", rarity: 1, lvl: 70, code: "7mt" }],
  "7wh": [
    { index: "Schaefer's Hammer", rarity: 1, lvl: 83, code: "7wh" },
    { index: "Stone Crusher", rarity: 4, lvl: 76, code: "7wh" },
  ],
  "7gm": [
    { index: "The Cranium Basher", rarity: 1, lvl: 85, code: "7gm" },
    { index: "Earthshifter", rarity: 1, lvl: 77, code: "7gm" },
  ],
  "7cr": [
    { index: "Lightsabre", rarity: 5, lvl: 66, code: "7cr" },
    { index: "Azurewrath", rarity: 1, lvl: 87, code: "7cr" },
  ],
  "7b7": [{ index: "Doombringer", rarity: 1, lvl: 75, code: "7b7" }],
  "7gd": [{ index: "The Grandfather", rarity: 1, lvl: 85, code: "7gd" }],
  "7dg": [{ index: "Wizardspike", rarity: 1, lvl: 69, code: "7dg" }],
  "7wc": [{ index: "Stormspire", rarity: 1, lvl: 78, code: "7wc" }],
  "6l7": [{ index: "Eaglehorn", rarity: 1, lvl: 77, code: "6l7" }],
  "6lw": [{ index: "Windforce", rarity: 1, lvl: 80, code: "6lw" }],
  baa: [{ index: "Arreat's Face", rarity: 1, lvl: 50, code: "baa" }],
  nea: [{ index: "Homunculus", rarity: 1, lvl: 50, code: "nea" }],
  ama: [{ index: "Titan's Revenge", rarity: 1, lvl: 50, code: "ama" }],
  am7: [{ index: "Lycander's Aim", rarity: 1, lvl: 50, code: "am7" }],
  am9: [{ index: "Lycander's Flank", rarity: 1, lvl: 50, code: "am9" }],
  oba: [{ index: "The Oculus", rarity: 1, lvl: 50, code: "oba" }],
  pa9: [{ index: "Herald of Zakarum", rarity: 1, lvl: 50, code: "pa9" }],
  "9tw": [{ index: "Cutthroat1", rarity: 1, lvl: 50, code: "9tw" }],
  dra: [{ index: "Jalal's Mane", rarity: 1, lvl: 50, code: "dra" }],
  "9ta": [{ index: "The Scalper", rarity: 1, lvl: 65, code: "9ta" }],
  "7sb": [{ index: "Bloodmoon", rarity: 1, lvl: 69, code: "7sb" }],
  "7sm": [{ index: "Djinnslayer", rarity: 1, lvl: 73, code: "7sm" }],
  "9tk": [{ index: "Deathbit", rarity: 1, lvl: 52, code: "9tk" }],
  "7bk": [{ index: "Warshrike", rarity: 1, lvl: 83, code: "7bk" }],
  "6rx": [{ index: "Gutsiphon", rarity: 1, lvl: 79, code: "6rx" }],
  "7ha": [{ index: "Razoredge", rarity: 1, lvl: 75, code: "7ha" }],
  "7sp": [{ index: "Demonlimb", rarity: 1, lvl: 71, code: "7sp" }],
  ulm: [{ index: "Steelshade", rarity: 1, lvl: 70, code: "ulm" }],
  "7pa": [{ index: "Tomb Reaver", rarity: 1, lvl: 86, code: "7pa" }],
  "7gw": [{ index: "Deaths's Web", rarity: 1, lvl: 74, code: "7gw" }],
  "7kr": [{ index: "Fleshripper", rarity: 1, lvl: 76, code: "7kr" }],
  "7fl": [
    { index: "Horizon's Tornado", rarity: 5, lvl: 72, code: "7fl" },
    { index: "Stormlash", rarity: 1, lvl: 86, code: "7fl" },
  ],
  "7wb": [{ index: "Jadetalon", rarity: 1, lvl: 74, code: "7wb" }],
  uhb: [{ index: "Shadowdancer", rarity: 1, lvl: 79, code: "uhb" }],
  drb: [{ index: "Cerebus", rarity: 1, lvl: 71, code: "drb" }],
  uar: [
    { index: "Tyrael's Might", rarity: 1, lvl: 87, code: "uar" },
    { index: "Templar's Might", rarity: 8, lvl: 82, code: "uar" },
  ],
  umg: [{ index: "Souldrain", rarity: 1, lvl: 82, code: "umg" }],
  "72a": [{ index: "Runemaster", rarity: 1, lvl: 80, code: "72a" }],
  "7wa": [{ index: "Deathcleaver", rarity: 1, lvl: 78, code: "7wa" }],
  "7gi": [{ index: "Executioner's Justice", rarity: 1, lvl: 83, code: "7gi" }],
  amd: [{ index: "Stoneraven", rarity: 1, lvl: 72, code: "amd" }],
  uld: [{ index: "Leviathan", rarity: 1, lvl: 73, code: "uld" }],
  "7ts": [{ index: "Gargoyle's Bite", rarity: 1, lvl: 78, code: "7ts" }],
  "7b8": [{ index: "Lacerator", rarity: 1, lvl: 76, code: "7b8" }],
  "6ws": [{ index: "Mang Song's Lesson", rarity: 1, lvl: 86, code: "6ws" }],
  "7br": [{ index: "Viperfork", rarity: 1, lvl: 79, code: "7br" }],
  "7ba": [{ index: "Ethereal Edge", rarity: 1, lvl: 82, code: "7ba" }],
  bad: [{ index: "Demonhorn's Edge", rarity: 1, lvl: 69, code: "bad" }],
  "7s8": [{ index: "The Reaper's Toll", rarity: 1, lvl: 83, code: "7s8" }],
  drd: [{ index: "Spiritkeeper", rarity: 1, lvl: 75, code: "drd" }],
  "6hx": [{ index: "Hellrack", rarity: 1, lvl: 84, code: "6hx" }],
  pac: [{ index: "Alma Negra", rarity: 1, lvl: 85, code: "pac" }],
  nef: [{ index: "Darkforge Spawn", rarity: 1, lvl: 72, code: "nef" }],
  "6sw": [{ index: "Widowmaker", rarity: 1, lvl: 73, code: "6sw" }],
  amb: [{ index: "Bloodraven's Charge", rarity: 1, lvl: 79, code: "amb" }],
  "7bl": [{ index: "Ghostflame", rarity: 1, lvl: 70, code: "7bl" }],
  "7cs": [{ index: "Shadowkiller", rarity: 1, lvl: 85, code: "7cs" }],
  "7ta": [{ index: "Gimmershred", rarity: 1, lvl: 78, code: "7ta" }],
  ci3: [{ index: "Griffon's Eye", rarity: 1, lvl: 84, code: "ci3" }],
  "7m7": [{ index: "Windhammer", rarity: 1, lvl: 76, code: "7m7" }],
  amf: [{ index: "Thunderstroke", rarity: 1, lvl: 77, code: "amf" }],
  "7s7": [{ index: "Demon's Arch", rarity: 1, lvl: 76, code: "7s7" }],
  nee: [{ index: "Boneflame", rarity: 1, lvl: 80, code: "nee" }],
  "7p7": [{ index: "Steelpillar", rarity: 1, lvl: 77, code: "7p7" }],
  urn: [{ index: "Crown of Ages", rarity: 1, lvl: 86, code: "urn" }],
  usk: [{ index: "Andariel's Visage", rarity: 1, lvl: 85, code: "usk" }],
  pae: [{ index: "Dragonscale", rarity: 1, lvl: 84, code: "pae" }],
  uul: [{ index: "Steel Carapice", rarity: 1, lvl: 74, code: "uul" }],
  uow: [{ index: "Medusa's Gaze", rarity: 1, lvl: 84, code: "uow" }],
  dre: [{ index: "Ravenlore", rarity: 1, lvl: 82, code: "dre" }],
  "7bw": [{ index: "Boneshade", rarity: 1, lvl: 84, code: "7bw" }],
  "7gs": [{ index: "Flamebellow", rarity: 1, lvl: 79, code: "7gs" }],
  obf: [{ index: "Fathom", rarity: 1, lvl: 81, code: "obf" }],
  bac: [{ index: "Wolfhowl", rarity: 1, lvl: 85, code: "bac" }],
  uts: [{ index: "Spirit Ward", rarity: 1, lvl: 76, code: "uts" }],
  ci2: [{ index: "Kira's Guardian", rarity: 1, lvl: 85, code: "ci2" }],
  uui: [{ index: "Ormus' Robes", rarity: 1, lvl: 83, code: "uui" }],
  cm3: [
    { index: "Gheed's Fortune", rarity: 1, lvl: 70, code: "cm3" },
    {
      index: "The Black Cleft",
      rarity: 1,
      lvl: 75,
      code: "cm3",
    },
    {
      index: "The Bone Break",
      rarity: 1,
      lvl: 75,
      code: "cm3",
    },
    {
      index: "The Cold Rupture",
      rarity: 1,
      lvl: 75,
      code: "cm3",
    },
    {
      index: "The Crack of the Heavens",
      rarity: 1,
      lvl: 75,
      code: "cm3",
    },
    {
      index: "The Flame Rift",
      rarity: 1,
      lvl: 75,
      code: "cm3",
    },
    {
      index: "The Rotting Fissure",
      rarity: 1,
      lvl: 75,
      code: "cm3",
    },
  ],
  bae: [{ index: "Halaberd's Reign", rarity: 1, lvl: 85, code: "bae" }],
  upk: [{ index: "Spike Thorn", rarity: 1, lvl: 78, code: "upk" }],
  uvg: [{ index: "Dracul's Grasp", rarity: 1, lvl: 84, code: "uvg" }],
  "7ls": [{ index: "Frostwind", rarity: 1, lvl: 78, code: "7ls" }],
  obc: [{ index: "Eschuta's temper", rarity: 1, lvl: 80, code: "obc" }],
  "7lw": [{ index: "Firelizard's Talons", rarity: 1, lvl: 75, code: "7lw" }],
  uvb: [{ index: "Sandstorm Trek", rarity: 1, lvl: 72, code: "uvb" }],
  umb: [{ index: "Marrowwalk", rarity: 1, lvl: 74, code: "umb" }],
  "7sc": [
    { index: "Heaven's Light", rarity: 1, lvl: 69, code: "7sc" },
    { index: "The Reedeemer", rarity: 1, lvl: 80, code: "7sc" },
  ],
  ulc: [{ index: "Arachnid Mesh", rarity: 1, lvl: 87, code: "ulc" }],
  uvc: [{ index: "Nosferatu's Coil", rarity: 1, lvl: 68, code: "uvc" }],
  umc: [{ index: "Verdugo's Hearty Cord", rarity: 1, lvl: 71, code: "umc" }],
  uh9: [{ index: "Giantskull", rarity: 1, lvl: 73, code: "uh9" }],
  "7ws": [{ index: "Ironward", rarity: 1, lvl: 68, code: "7ws" }],
  cm1: [{ index: "Annihilus", rarity: 1, lvl: 110, code: "cm1" }],
  "7sr": [{ index: "Arioc's Needle", rarity: 1, lvl: 85, code: "7sr" }],
  "7mp": [{ index: "Cranebeak", rarity: 1, lvl: 71, code: "7mp" }],
  "7cl": [{ index: "Nord's Tenderizer", rarity: 1, lvl: 76, code: "7cl" }],
  "7gl": [{ index: "Wraithflight", rarity: 1, lvl: 84, code: "7gl" }],
  "7o7": [{ index: "Bonehew", rarity: 1, lvl: 72, code: "7o7" }],
  "6cs": [{ index: "Ondal's Wisdom", rarity: 1, lvl: 74, code: "6cs" }],
  ush: [{ index: "Headhunter's Glory", rarity: 1, lvl: 83, code: "ush" }],
  uhg: [{ index: "Steelrend", rarity: 1, lvl: 78, code: "uhg" }],
  jew: [
    { index: "Rainbow Facet 1", rarity: 1, lvl: 85, code: "jew" },
    { index: "Rainbow Facet 2", rarity: 1, lvl: 85, code: "jew" },
    { index: "Rainbow Facet 3", rarity: 1, lvl: 85, code: "jew" },
    { index: "Rainbow Facet 4", rarity: 1, lvl: 85, code: "jew" },
    { index: "Rainbow Facet 5", rarity: 1, lvl: 85, code: "jew" },
    { index: "Rainbow Facet 6", rarity: 1, lvl: 85, code: "jew" },
    { index: "Rainbow Facet 7", rarity: 1, lvl: 85, code: "jew" },
    { index: "Rainbow Facet 8", rarity: 1, lvl: 85, code: "jew" },
  ],
  cm2: [{ index: "Hellfire Torch", rarity: 1, lvl: 110, code: "cm2" }],
};

export const SetBaseLookup: UniqueSetBaseLookupType = {
  xtb: [{ index: "Aldur's Advance", rarity: 7, lvl: 29, code: "xtb" }],
  uul: [{ index: "Aldur's Deception", rarity: 7, lvl: 29, code: "uul" }],
  "9mt": [{ index: "Aldur's Gauntlet", rarity: 7, lvl: 29, code: "9mt" }],
  dr8: [{ index: "Aldur's Stony Gaze", rarity: 7, lvl: 29, code: "dr8" }],
  rin: [
    { index: "Angelic Halo", rarity: 3, lvl: 17, code: "rin" },
    { index: "Cathan's Seal", rarity: 7, lvl: 15, code: "rin" },
  ],
  rng: [{ index: "Angelic Mantle", rarity: 7, lvl: 17, code: "rng" }],
  sbr: [{ index: "Angelic Sickle", rarity: 7, lvl: 17, code: "sbr" }],
  amu: [
    { index: "Angelic Wings", rarity: 7, lvl: 17, code: "amu" },
    { index: "Arcanna's Sign", rarity: 1, lvl: 20, code: "amu" },
    { index: "Cathan's Sigil", rarity: 7, lvl: 15, code: "amu" },
    { index: "Civerb's Icon", rarity: 7, lvl: 13, code: "amu" },
    { index: "Iratha's Collar", rarity: 7, lvl: 21, code: "amu" },
    { index: "Tal Rasha's Adjudication", rarity: 1, lvl: 26, code: "amu" },
    { index: "Tancred's Weird", rarity: 7, lvl: 27, code: "amu" },
    { index: "Telling of Beads", rarity: 1, lvl: 39, code: "amu" },
    { index: "Vidala's Snare", rarity: 7, lvl: 19, code: "amu" },
  ],
  wst: [{ index: "Arcanna's Deathwand", rarity: 7, lvl: 20, code: "wst" }],
  ltp: [{ index: "Arcanna's Flesh", rarity: 7, lvl: 20, code: "ltp" }],
  skp: [{ index: "Arcanna's Head", rarity: 7, lvl: 20, code: "skp" }],
  vbl: [{ index: "Arctic Binding", rarity: 7, lvl: 3, code: "vbl" }],
  qui: [{ index: "Arctic Furs", rarity: 7, lvl: 3, code: "qui" }],
  swb: [{ index: "Arctic Horn", rarity: 7, lvl: 3, code: "swb" }],
  tgl: [
    { index: "Arctic Mitts", rarity: 7, lvl: 3, code: "tgl" },
    { index: "Iratha's Cuff", rarity: 7, lvl: 21, code: "tgl" },
  ],
  "2ax": [{ index: "Berserker's Hatchet", rarity: 7, lvl: 5, code: "2ax" }],
  spl: [{ index: "Berserker's Hauberk", rarity: 7, lvl: 5, code: "spl" }],
  hlm: [{ index: "Berserker's Headgear", rarity: 7, lvl: 5, code: "hlm" }],
  "7gd": [
    { index: "Bul-Kathos' Sacred Charge", rarity: 7, lvl: 50, code: "7gd" },
  ],
  "7wd": [
    { index: "Bul-Kathos' Tribal Guardian", rarity: 7, lvl: 50, code: "7wd" },
  ],
  chn: [{ index: "Cathan's Mesh", rarity: 7, lvl: 15, code: "chn" }],
  bst: [{ index: "Cathan's Rule", rarity: 7, lvl: 15, code: "bst" }],
  msk: [{ index: "Cathan's Visage", rarity: 7, lvl: 15, code: "msk" }],
  gsc: [{ index: "Civerb's Cudgel", rarity: 7, lvl: 13, code: "gsc" }],
  lrg: [{ index: "Civerb's Ward", rarity: 7, lvl: 13, code: "lrg" }],
  sml: [{ index: "Cleglaw's Claw", rarity: 7, lvl: 6, code: "sml" }],
  mgl: [{ index: "Cleglaw's Pincers", rarity: 7, lvl: 6, code: "mgl" }],
  lsd: [{ index: "Cleglaw's Tooth", rarity: 7, lvl: 6, code: "lsd" }],
  stu: [{ index: "Cow King's Hide", rarity: 7, lvl: 20, code: "stu" }],
  vbt: [
    { index: "Cow King's Hoofs", rarity: 7, lvl: 20, code: "vbt" },
    { index: "McAuley's Riprap", rarity: 7, lvl: 20, code: "vbt" },
  ],
  xap: [{ index: "Cow King's Horns", rarity: 7, lvl: 20, code: "xap" }],
  umc: [{ index: "Credendum", rarity: 7, lvl: 39, code: "umc" }],
  "7ma": [{ index: "Dangoon's Teaching", rarity: 7, lvl: 55, code: "7ma" }],
  lbl: [{ index: "Death's Guard", rarity: 7, lvl: 8, code: "lbl" }],
  lgl: [{ index: "Death's Hand", rarity: 7, lvl: 8, code: "lgl" }],
  wsd: [{ index: "Death's Touch", rarity: 7, lvl: 8, code: "wsd" }],
  xar: [{ index: "Griswold's Heart", rarity: 7, lvl: 44, code: "xar" }],
  paf: [{ index: "Griswold's Honor", rarity: 7, lvl: 44, code: "paf" }],
  urn: [{ index: "Griswold's Valor", rarity: 7, lvl: 44, code: "urn" }],
  "7ws": [{ index: "Griswolds's Redemption", rarity: 7, lvl: 44, code: "7ws" }],
  xhm: [{ index: "Guillaume's Face", rarity: 7, lvl: 41, code: "xhm" }],
  xrs: [{ index: "Haemosu's Adament", rarity: 7, lvl: 55, code: "xrs" }],
  uts: [{ index: "Heaven's Taebaek", rarity: 7, lvl: 55, code: "uts" }],
  buc: [{ index: "Hsarus' Iron Fist", rarity: 7, lvl: 4, code: "buc" }],
  mbt: [{ index: "Hsarus' Iron Heel", rarity: 7, lvl: 4, code: "mbt" }],
  mbl: [
    { index: "Hsarus' Iron Stay", rarity: 7, lvl: 4, code: "mbl" },
    { index: "Hwanin's Seal", rarity: 7, lvl: 28, code: "mbl" },
  ],
  "9vo": [{ index: "Hwanin's Justice", rarity: 7, lvl: 28, code: "9vo" }],
  xcl: [{ index: "Hwanin's Refuge", rarity: 7, lvl: 28, code: "xcl" }],
  xrn: [{ index: "Hwanin's Splendor", rarity: 7, lvl: 28, code: "xrn" }],
  zhb: [{ index: "Immortal King's Detail", rarity: 7, lvl: 37, code: "zhb" }],
  xhg: [{ index: "Immortal King's Forge", rarity: 7, lvl: 37, code: "xhg" }],
  xhb: [{ index: "Immortal King's Pillar", rarity: 7, lvl: 37, code: "xhb" }],
  uar: [
    { index: "Immortal King's Soul Cage", rarity: 7, lvl: 37, code: "uar" },
  ],
  "7m7": [
    { index: "Immortal King's Stone Crusher", rarity: 7, lvl: 37, code: "7m7" },
  ],
  ba5: [{ index: "Immortal King's Will", rarity: 7, lvl: 37, code: "ba5" }],
  cap: [
    { index: "Infernal Cranium", rarity: 7, lvl: 7, code: "cap" },
    { index: "McAuley's Paragon", rarity: 3, lvl: 20, code: "cap" },
  ],
  tbl: [
    { index: "Infernal Sign", rarity: 7, lvl: 7, code: "tbl" },
    { index: "Iratha's Cord", rarity: 7, lvl: 21, code: "tbl" },
  ],
  gwn: [{ index: "Infernal Torch", rarity: 7, lvl: 7, code: "gwn" }],
  crn: [
    { index: "Iratha's Coil", rarity: 7, lvl: 21, code: "crn" },
    { index: "Milabrega's Diadem", rarity: 7, lvl: 23, code: "crn" },
  ],
  brs: [{ index: "Isenhart's Case", rarity: 7, lvl: 11, code: "brs" }],
  fhl: [{ index: "Isenhart's Horns", rarity: 7, lvl: 11, code: "fhl" }],
  bsd: [{ index: "Isenhart's Lightbrand", rarity: 7, lvl: 11, code: "bsd" }],
  gts: [{ index: "Isenhart's Parry", rarity: 7, lvl: 11, code: "gts" }],
  ulg: [{ index: "Laying of Hands", rarity: 7, lvl: 39, code: "ulg" }],
  amc: [{ index: "M'avina's Caster", rarity: 7, lvl: 21, code: "amc" }],
  uld: [{ index: "M'avina's Embrace", rarity: 7, lvl: 21, code: "uld" }],
  xtg: [{ index: "M'avina's Icy Clutch", rarity: 7, lvl: 21, code: "xtg" }],
  zvb: [{ index: "M'avina's Tenet", rarity: 7, lvl: 21, code: "zvb" }],
  ci3: [{ index: "M'avina's True Sight", rarity: 7, lvl: 21, code: "ci3" }],
  xvg: [{ index: "Magnus' Skin", rarity: 7, lvl: 41, code: "xvg" }],
  bwn: [{ index: "McAuley's Superstition", rarity: 7, lvl: 20, code: "bwn" }],
  vgl: [{ index: "McAuley's Taboo", rarity: 7, lvl: 20, code: "vgl" }],
  kit: [{ index: "Milabrega's Orb", rarity: 7, lvl: 23, code: "kit" }],
  aar: [{ index: "Milabrega's Robe", rarity: 7, lvl: 23, code: "aar" }],
  wsp: [{ index: "Milabrega's Rod", rarity: 7, lvl: 23, code: "wsp" }],
  ci0: [{ index: "Naj's Circlet", rarity: 7, lvl: 43, code: "ci0" }],
  ult: [{ index: "Naj's Light Plate", rarity: 7, lvl: 43, code: "ult" }],
  "6cs": [{ index: "Naj's Puzzler", rarity: 7, lvl: 43, code: "6cs" }],
  "7qr": [{ index: "Natalya's Mark", rarity: 7, lvl: 22, code: "7qr" }],
  ucl: [{ index: "Natalya's Shadow", rarity: 7, lvl: 22, code: "ucl" }],
  xmb: [{ index: "Natalya's Soul", rarity: 7, lvl: 22, code: "xmb" }],
  xh9: [{ index: "Natalya's Totem", rarity: 7, lvl: 22, code: "xh9" }],
  uhm: [{ index: "Ondal's Almighty", rarity: 7, lvl: 55, code: "uhm" }],
  xlb: [{ index: "Rite of Passage", rarity: 7, lvl: 39, code: "xlb" }],
  "7ls": [
    { index: "Sazabi's Cobalt Redeemer", rarity: 7, lvl: 34, code: "7ls" },
  ],
  upl: [{ index: "Sazabi's Ghost Liberator", rarity: 7, lvl: 34, code: "upl" }],
  xhl: [{ index: "Sazabi's Mental Sheath", rarity: 7, lvl: 34, code: "xhl" }],
  hgl: [{ index: "Sigon's Gage", rarity: 7, lvl: 9, code: "hgl" }],
  tow: [{ index: "Sigon's Guard", rarity: 7, lvl: 9, code: "tow" }],
  hbt: [{ index: "Sigon's Sabot", rarity: 7, lvl: 9, code: "hbt" }],
  gth: [{ index: "Sigon's Shelter", rarity: 7, lvl: 9, code: "gth" }],
  ghm: [{ index: "Sigon's Visor", rarity: 7, lvl: 9, code: "ghm" }],
  hbl: [{ index: "Sigon's Wrap", rarity: 7, lvl: 9, code: "hbl" }],
  uui: [{ index: "Spiritual Custodian", rarity: 7, lvl: 39, code: "uui" }],
  zmb: [
    { index: "Tal Rasha's Fire-Spun Cloth", rarity: 7, lvl: 26, code: "zmb" },
  ],
  xsk: [
    { index: "Tal Rasha's Horadric Crest", rarity: 7, lvl: 26, code: "xsk" },
  ],
  uth: [{ index: "Tal Rasha's Howling Wind", rarity: 7, lvl: 26, code: "uth" }],
  oba: [{ index: "Tal Rasha's Lidless Eye", rarity: 7, lvl: 26, code: "oba" }],
  mpi: [{ index: "Tancred's Crowbill", rarity: 7, lvl: 27, code: "mpi" }],
  lbt: [{ index: "Tancred's Hobnails", rarity: 7, lvl: 27, code: "lbt" }],
  bhm: [{ index: "Tancred's Skull", rarity: 7, lvl: 27, code: "bhm" }],
  ful: [{ index: "Tancred's Spine", rarity: 7, lvl: 27, code: "ful" }],
  xmg: [{ index: "Trang-Oul's Claws", rarity: 7, lvl: 32, code: "xmg" }],
  utc: [{ index: "Trang-Oul's Girth", rarity: 7, lvl: 32, code: "utc" }],
  uh9: [{ index: "Trang-Oul's Guise", rarity: 7, lvl: 32, code: "uh9" }],
  xul: [{ index: "Trang-Oul's Scales", rarity: 7, lvl: 32, code: "xul" }],
  ne9: [{ index: "Trang-Oul's Wing", rarity: 7, lvl: 32, code: "ne9" }],
  lea: [{ index: "Vidala's Ambush", rarity: 7, lvl: 19, code: "lea" }],
  lbb: [{ index: "Vidala's Barb", rarity: 7, lvl: 19, code: "lbb" }],
  tbt: [{ index: "Vidala's Fetlock", rarity: 7, lvl: 19, code: "tbt" }],
  xml: [{ index: "Wihtstan's Guard", rarity: 7, lvl: 41, code: "xml" }],
  ztb: [{ index: "Wilhelm's Pride", rarity: 7, lvl: 41, code: "ztb" }],
};

export const isSunderCharm = (item: UniqueSetDictEntry) => {
  return item.code === "cm3" && item.index !== "Gheed's Fortune";
};
