import { TCDictType } from "./tc-dict.js";

export const AtomicDict: TCDictType = {
  abow18: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["am1", 1]],
  },
  abow27: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["am2", 1]],
  },
  abow39: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["am6", 1]],
  },
  abow48: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["am7", 1]],
  },
  abow54: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["amb", 1]],
  },
  abow78: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["amc", 1]],
  },
  armo12: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["hlm", 1],
      ["rng", 1],
      ["lrg", 1],
      ["mgl", 1],
      ["mbt", 1],
      ["mbl", 1],
      ["spk", 1],
    ],
  },
  armo15: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["fhl", 1],
      ["scl", 1],
      ["chn", 1],
      ["kit", 1],
    ],
  },
  armo18: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["brs", 3],
      ["dr3", 1],
      ["ba3", 1],
      ["pa3", 1],
      ["ne3", 1],
    ],
  },
  armo21: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["msk", 3],
      ["spl", 3],
      ["tgl", 3],
      ["tbt", 3],
      ["tbl", 3],
      ["bsh", 3],
      ["dr4", 1],
      ["ba4", 1],
      ["pa4", 1],
      ["ne4", 1],
    ],
  },
  armo24: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["ghm", 3],
      ["plt", 3],
      ["tow", 3],
      ["bhm", 3],
      ["dr5", 1],
      ["ba5", 1],
      ["pa5", 1],
      ["ne5", 1],
      ["ci0", 3],
    ],
  },
  armo27: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["hgl", 1],
      ["hbt", 1],
      ["hbl", 1],
    ],
  },
  armo3: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["cap", 1],
      ["qui", 1],
      ["lea", 1],
      ["buc", 1],
      ["lgl", 1],
      ["lbt", 1],
      ["lbl", 1],
    ],
  },
  armo30: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["crn", 1],
      ["fld", 1],
      ["gts", 1],
    ],
  },
  armo33: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["gth", 3],
      ["xlg", 3],
      ["ba6", 1],
      ["ne6", 1],
    ],
  },
  armo36: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["ltp", 3],
      ["xap", 3],
      ["xui", 3],
      ["xea", 3],
      ["xuc", 3],
      ["xlb", 3],
      ["zlb", 3],
      ["dr6", 1],
      ["pa6", 1],
    ],
  },
  armo39: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["ful", 3],
      ["xkp", 3],
      ["xla", 3],
      ["xml", 3],
      ["xvg", 3],
      ["xvb", 3],
      ["zvb", 3],
      ["ba7", 1],
      ["ne7", 1],
    ],
  },
  armo42: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["aar", 3],
      ["xlm", 3],
      ["xtu", 3],
      ["xng", 3],
      ["xrg", 3],
      ["xpk", 3],
      ["dr7", 1],
      ["pa7", 1],
    ],
  },
  armo45: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["xhl", 3],
      ["xcl", 3],
      ["xhn", 3],
      ["xit", 3],
      ["xmg", 3],
      ["xmb", 3],
      ["zmb", 3],
      ["ba8", 1],
      ["ne8", 1],
    ],
  },
  armo48: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["xsk", 3],
      ["xrs", 3],
      ["xsh", 3],
      ["dr8", 1],
      ["pa8", 1],
    ],
  },
  armo51: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["xhm", 3],
      ["xpl", 3],
      ["xow", 3],
      ["xtg", 3],
      ["xtb", 3],
      ["ztb", 3],
      ["xh9", 3],
      ["dr9", 1],
      ["ba9", 1],
      ["pa9", 1],
      ["ne9", 1],
    ],
  },
  armo54: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["xlt", 3],
      ["xhg", 3],
      ["xhb", 3],
      ["zhb", 3],
      ["ci1", 3],
      ["uhl", 3],
      ["baa", 1],
      ["nea", 1],
    ],
  },
  armo57: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["xrn", 3],
      ["xld", 3],
      ["xts", 3],
      ["ulg", 3],
      ["dra", 1],
      ["paa", 1],
    ],
  },
  armo6: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["skp", 3],
      ["hla", 3],
      ["sml", 3],
      ["dr1", 1],
      ["ba1", 1],
      ["pa1", 1],
      ["ne1", 1],
    ],
  },
  armo60: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["xth", 3],
      ["xtp", 3],
      ["uap", 3],
      ["uuc", 3],
      ["ulb", 3],
      ["bab", 1],
      ["neb", 1],
    ],
  },
  armo63: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["xul", 3],
      ["ukp", 3],
      ["uhn", 3],
      ["uml", 3],
      ["uvg", 3],
      ["ulc", 3],
      ["drb", 1],
      ["pab", 1],
    ],
  },
  armo66: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["xar", 3],
      ["uui", 3],
      ["urg", 3],
      ["uvb", 3],
      ["bac", 1],
      ["ned", 1],
    ],
  },
  armo69: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["ulm", 3],
      ["uea", 3],
      ["ula", 3],
      ["umg", 3],
      ["uvc", 3],
      ["upk", 3],
      ["drc", 1],
      ["neg", 1],
    ],
  },
  armo72: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["ci2", 3],
      ["utu", 3],
      ["ung", 3],
      ["uit", 3],
      ["umb", 3],
      ["pac", 1],
    ],
  },
  armo75: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["usk", 3],
      ["ucl", 3],
      ["urs", 3],
      ["umc", 3],
      ["bad", 1],
      ["pad", 1],
    ],
  },
  armo78: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["upl", 3],
      ["ult", 3],
      ["utg", 3],
      ["ush", 3],
      ["drd", 1],
    ],
  },
  armo81: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["uhm", 3],
      ["uld", 3],
      ["uow", 3],
      ["utb", 3],
      ["bae", 1],
      ["nee", 1],
    ],
  },
  armo84: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["uth", 3],
      ["uul", 3],
      ["utp", 3],
      ["uts", 3],
      ["utc", 3],
      ["uh9", 3],
      ["dre", 1],
      ["pae", 1],
    ],
  },
  armo87: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["ci3", 3],
      ["urn", 3],
      ["uar", 3],
      ["uhg", 3],
      ["uhb", 3],
      ["uhc", 3],
      ["drf", 1],
      ["baf", 1],
      ["paf", 1],
      ["nef", 1],
    ],
  },
  armo9: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["stu", 3],
      ["vgl", 3],
      ["vbt", 3],
      ["vbl", 3],
      ["dr2", 1],
      ["ba2", 1],
      ["pa2", 1],
      ["ne2", 1],
    ],
  },
  bow12: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["cbw", 1]],
  },
  bow18: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["sbb", 3],
      ["am1", 1],
    ],
  },
  bow24: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["lbb", 1]],
  },
  bow27: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["swb", 3],
      ["am2", 1],
    ],
  },
  bow3: { nodrop: 0, picks: 1, qualityRatios: [0, 0, 0, 0], tcs: [["sbw", 1]] },
  bow30: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["8sb", 1]],
  },
  bow33: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["lwb", 1],
      ["8hb", 1],
    ],
  },
  bow36: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["8lb", 1]],
  },
  bow39: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["8cb", 3],
      ["am6", 1],
    ],
  },
  bow45: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["8s8", 1]],
  },
  bow48: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["8l8", 3],
      ["am7", 1],
    ],
  },
  bow51: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["8sw", 1]],
  },
  bow54: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["8lw", 3],
      ["amb", 1],
    ],
  },
  bow57: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["6sb", 1]],
  },
  bow6: { nodrop: 0, picks: 1, qualityRatios: [0, 0, 0, 0], tcs: [["hbw", 1]] },
  bow60: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["6hb", 1]],
  },
  bow63: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["6lb", 1]],
  },
  bow69: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["6cb", 1]],
  },
  bow72: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["6s7", 1]],
  },
  bow78: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["6l7", 3],
      ["amc", 1],
    ],
  },
  bow81: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["6sw", 1]],
  },
  bow87: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [["6lw", 1]],
  },
  bow9: { nodrop: 0, picks: 1, qualityRatios: [0, 0, 0, 0], tcs: [["lbw", 1]] },
  mele12: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["bax", 3],
      ["ywn", 1],
      ["flc", 3],
      ["crs", 3],
      ["2hs", 3],
      ["pil", 3],
      ["vou", 3],
      ["cst", 1],
      ["axf", 2],
    ],
  },
  mele15: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["2ax", 3],
      ["gsc", 1],
      ["mst", 3],
      ["bsd", 3],
      ["bkf", 3],
      ["ssp", 3],
      ["scy", 3],
      ["ces", 2],
    ],
  },
  mele18: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["btx", 3],
      ["bwn", 1],
      ["clm", 3],
      ["kri", 3],
      ["bal", 3],
      ["brn", 3],
      ["bst", 1],
      ["clw", 2],
      ["am3", 1],
    ],
  },
  mele21: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["mpi", 3],
      ["wsp", 1],
      ["fla", 3],
      ["mau", 3],
      ["lsd", 3],
      ["gis", 3],
      ["spt", 3],
      ["pax", 3],
      ["btl", 2],
    ],
  },
  mele24: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["gax", 3],
      ["bsw", 3],
      ["bld", 3],
      ["glv", 3],
      ["pik", 3],
      ["wst", 1],
      ["skr", 2],
      ["am5", 1],
    ],
  },
  mele27: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["wax", 3],
      ["gix", 3],
      ["gwn", 1],
      ["whm", 3],
      ["wsd", 3],
      ["flb", 3],
      ["am4", 1],
    ],
  },
  mele3: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["hax", 3],
      ["wnd", 1],
      ["clb", 3],
      ["scp", 1],
      ["ssd", 3],
      ["dgr", 3],
      ["tkf", 3],
      ["jav", 3],
      ["sst", 1],
      ["ktr", 2],
    ],
  },
  mele30: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["tsp", 3],
      ["hal", 3],
      ["9cl", 3],
      ["9ss", 3],
      ["9ja", 3],
      ["8ss", 1],
      ["9ar", 2],
    ],
  },
  mele33: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["gma", 3],
      ["gsd", 3],
      ["9ha", 3],
      ["9wn", 1],
      ["9sc", 1],
      ["9sp", 3],
      ["9dg", 3],
      ["9tk", 3],
      ["9sr", 3],
      ["9b7", 3],
      ["9wb", 2],
    ],
  },
  mele36: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["wsc", 3],
      ["9ax", 3],
      ["9la", 3],
      ["9ma", 3],
      ["9sb", 3],
      ["9di", 3],
      ["9ta", 3],
      ["9tr", 3],
      ["9pa", 3],
      ["8ls", 1],
      ["9xf", 2],
      ["ama", 1],
    ],
  },
  mele39: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["92a", 3],
      ["9ba", 3],
      ["9yw", 1],
      ["9mt", 3],
      ["9fc", 3],
      ["9cr", 3],
      ["92h", 3],
      ["9bk", 3],
      ["9pi", 3],
      ["9vo", 3],
      ["8cs", 1],
    ],
  },
  mele42: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9bt", 3],
      ["9qs", 1],
      ["9bs", 3],
      ["9cm", 3],
      ["9kr", 3],
      ["9b8", 3],
      ["9s9", 3],
      ["9br", 3],
      ["9s8", 3],
      ["8bs", 1],
      ["9cs", 2],
    ],
  },
  mele45: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9mp", 3],
      ["9bw", 1],
      ["9ws", 1],
      ["9fl", 3],
      ["9m9", 3],
      ["9sm", 3],
      ["9ls", 3],
      ["9gs", 3],
      ["9st", 3],
      ["9lw", 2],
      ["am8", 1],
    ],
  },
  mele48: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9wa", 3],
      ["9ga", 3],
      ["9wh", 3],
      ["9b9", 3],
      ["9bl", 3],
      ["9gl", 3],
      ["9p9", 3],
      ["8ws", 1],
    ],
  },
  mele51: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9gi", 3],
      ["9gw", 1],
      ["9wd", 3],
      ["9fb", 3],
      ["9ts", 3],
      ["9h9", 3],
      ["9tw", 2],
      ["am9", 1],
    ],
  },
  mele54: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9gm", 1.5],
      ["9gd", 1.5],
      ["9qr", 1],
      ["7ha", 1.5],
      ["7cl", 1.5],
      ["7ja", 1.5],
    ],
  },
  mele57: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9wc", 3],
      ["7la", 3],
      ["7wn", 1],
      ["7sp", 3],
      ["7ss", 3],
      ["7ta", 3],
    ],
  },
  mele6: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["lax", 1],
      ["spc", 1],
      ["scm", 1],
      ["spr", 1],
      ["bar", 1],
    ],
  },
  mele60: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7ar", 2],
      ["72h", 3],
      ["7dg", 3],
      ["7sr", 3],
      ["7o7", 3],
      ["6ss", 1],
    ],
  },
  mele63: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7wb", 2],
      ["7ax", 3],
      ["7sc", 1],
      ["7ma", 3],
      ["7sm", 3],
      ["7sb", 3],
      ["7pi", 3],
      ["amd", 1],
    ],
  },
  mele66: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7ba", 3],
      ["7yw", 1],
      ["7cm", 3],
      ["7tk", 3],
      ["7tr", 3],
      ["7vo", 3],
      ["6ls", 1],
      ["amf", 1],
    ],
  },
  mele69: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7xf", 1],
      ["7m7", 1.5],
      ["7fc", 1.5],
    ],
  },
  mele72: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["72a", 1],
      ["7mt", 1],
      ["7gs", 1],
      ["7di", 1],
      ["7s7", 1],
      ["7s8", 1],
    ],
  },
  mele75: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7cs", 2],
      ["7bt", 3],
      ["7bw", 1],
      ["7cr", 3],
      ["7br", 3],
      ["6cs", 1],
    ],
  },
  mele78: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7lw", 2],
      ["7qs", 1],
      ["7fl", 3],
      ["7bs", 3],
      ["7b7", 3],
      ["7bk", 3],
    ],
  },
  mele81: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7tw", 2],
      ["7mp", 3],
      ["7fb", 3],
      ["7b8", 3],
      ["7gl", 3],
      ["7pa", 3],
      ["ame", 1],
    ],
  },
  mele84: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7ga", 3],
      ["7wh", 3],
      ["7ls", 3],
      ["7kr", 3],
      ["7st", 3],
      ["7h7", 3],
      ["6bs", 1],
    ],
  },
  mele87: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7qr", 2],
      ["7wa", 3],
      ["7gi", 3],
      ["7gw", 1],
      ["7ws", 1],
      ["7gm", 3],
      ["7wd", 3],
      ["7gd", 3],
      ["7bl", 3],
      ["7ts", 3],
      ["7p7", 3],
      ["7wc", 3],
      ["6ws", 1],
    ],
  },
  mele9: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["axe", 3],
      ["mac", 3],
      ["sbr", 3],
      ["dir", 3],
      ["tax", 3],
      ["tri", 3],
      ["lst", 1],
      ["wrb", 2],
    ],
  },
  weap12: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["bax", 3],
      ["ywn", 1],
      ["flc", 3],
      ["crs", 3],
      ["2hs", 3],
      ["pil", 3],
      ["vou", 3],
      ["cst", 1],
      ["cbw", 3],
      ["axf", 2],
      ["ob3", 1],
    ],
  },
  weap15: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["2ax", 3],
      ["gsc", 1],
      ["mst", 3],
      ["bsd", 3],
      ["bkf", 3],
      ["ssp", 3],
      ["scy", 3],
      ["mxb", 3],
      ["ces", 2],
    ],
  },
  weap18: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["btx", 3],
      ["bwn", 1],
      ["clm", 3],
      ["kri", 3],
      ["bal", 3],
      ["brn", 3],
      ["bst", 1],
      ["sbb", 3],
      ["clw", 2],
      ["ob4", 1],
      ["am1", 1],
      ["am3", 1],
    ],
  },
  weap21: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["mpi", 3],
      ["wsp", 1],
      ["fla", 3],
      ["mau", 3],
      ["lsd", 3],
      ["gis", 3],
      ["spt", 3],
      ["pax", 3],
      ["btl", 2],
    ],
  },
  weap24: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["gax", 3],
      ["bsw", 3],
      ["bld", 3],
      ["glv", 3],
      ["pik", 3],
      ["wst", 1],
      ["lbb", 3],
      ["hxb", 3],
      ["skr", 2],
      ["ob5", 1],
      ["am5", 1],
    ],
  },
  weap27: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["wax", 3],
      ["gix", 3],
      ["gwn", 1],
      ["whm", 3],
      ["wsd", 3],
      ["flb", 3],
      ["swb", 3],
      ["am2", 1],
      ["am4", 1],
    ],
  },
  weap3: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["hax", 3],
      ["wnd", 1],
      ["clb", 3],
      ["scp", 1],
      ["ssd", 3],
      ["dgr", 3],
      ["tkf", 3],
      ["jav", 3],
      ["sst", 1],
      ["sbw", 3],
      ["ktr", 2],
      ["ob1", 1],
    ],
  },
  weap30: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["tsp", 3],
      ["hal", 3],
      ["9cl", 3],
      ["9ss", 3],
      ["9ja", 3],
      ["8ss", 1],
      ["8sb", 3],
      ["9ar", 2],
    ],
  },
  weap33: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["gma", 3],
      ["gsd", 3],
      ["lwb", 3],
      ["rxb", 3],
      ["9ha", 3],
      ["9wn", 1],
      ["9sc", 1],
      ["9sp", 3],
      ["9dg", 3],
      ["9tk", 3],
      ["9sr", 3],
      ["9b7", 3],
      ["8hb", 3],
      ["9wb", 2],
      ["ob6", 1],
    ],
  },
  weap36: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["wsc", 3],
      ["9ax", 3],
      ["9la", 3],
      ["9ma", 3],
      ["9sb", 3],
      ["9di", 3],
      ["9ta", 3],
      ["9tr", 3],
      ["9pa", 3],
      ["8ls", 1],
      ["8lb", 3],
      ["8lx", 3],
      ["9xf", 2],
      ["ama", 1],
    ],
  },
  weap39: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["92a", 3],
      ["9ba", 3],
      ["9yw", 1],
      ["9mt", 3],
      ["9fc", 3],
      ["9cr", 3],
      ["92h", 3],
      ["9bk", 3],
      ["9pi", 3],
      ["9vo", 3],
      ["8cs", 1],
      ["8cb", 3],
      ["ob7", 1],
      ["am6", 1],
    ],
  },
  weap42: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9bt", 3],
      ["9qs", 1],
      ["9bs", 3],
      ["9cm", 3],
      ["9kr", 3],
      ["9b8", 3],
      ["9s9", 3],
      ["9br", 3],
      ["9s8", 3],
      ["8bs", 1],
      ["8mx", 3],
      ["9cs", 2],
      ["ob8", 1],
    ],
  },
  weap45: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9mp", 3],
      ["9bw", 1],
      ["9ws", 1],
      ["9fl", 3],
      ["9m9", 3],
      ["9sm", 3],
      ["9ls", 3],
      ["9gs", 3],
      ["9st", 3],
      ["8s8", 3],
      ["9lw", 2],
      ["am8", 1],
    ],
  },
  weap48: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9wa", 3],
      ["9ga", 3],
      ["9wh", 3],
      ["9b9", 3],
      ["9bl", 3],
      ["9gl", 3],
      ["9p9", 3],
      ["8ws", 1],
      ["8l8", 3],
      ["8hx", 3],
      ["ob9", 1],
      ["am7", 1],
    ],
  },
  weap51: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9gi", 3],
      ["9gw", 1],
      ["9wd", 3],
      ["9fb", 3],
      ["9ts", 3],
      ["9h9", 3],
      ["8sw", 3],
      ["9tw", 2],
      ["oba", 1],
      ["am9", 1],
    ],
  },
  weap54: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9gm", 3],
      ["9gd", 3],
      ["8lw", 3],
      ["8rx", 3],
      ["9qr", 2],
      ["7ha", 3],
      ["7cl", 3],
      ["7ja", 3],
      ["amb", 1],
    ],
  },
  weap57: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["9wc", 3],
      ["7la", 3],
      ["7wn", 1],
      ["7sp", 3],
      ["7ss", 3],
      ["7ta", 3],
      ["6sb", 3],
      ["6lx", 3],
    ],
  },
  weap6: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["lax", 1],
      ["spc", 1],
      ["scm", 1],
      ["spr", 1],
      ["bar", 1],
      ["hbw", 1],
      ["lxb", 1],
    ],
  },
  weap60: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7ar", 2],
      ["72h", 3],
      ["7dg", 3],
      ["7sr", 3],
      ["7o7", 3],
      ["6ss", 1],
      ["6hb", 3],
      ["obb", 1],
    ],
  },
  weap63: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7wb", 2],
      ["7ax", 3],
      ["7sc", 1],
      ["7ma", 3],
      ["7sm", 3],
      ["7sb", 3],
      ["7pi", 3],
      ["6lb", 3],
      ["amd", 1],
    ],
  },
  weap66: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7ba", 3],
      ["7yw", 1],
      ["7cm", 3],
      ["7tk", 3],
      ["7tr", 3],
      ["7vo", 3],
      ["6ls", 1],
      ["amf", 1],
    ],
  },
  weap69: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7xf", 2],
      ["7m7", 3],
      ["7fc", 3],
      ["6cb", 3],
      ["6mx", 3],
      ["obc", 1],
    ],
  },
  weap72: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["72a", 1],
      ["7mt", 1],
      ["7gs", 1],
      ["7di", 1],
      ["7s7", 1],
      ["7s8", 1],
      ["6s7", 1],
    ],
  },
  weap75: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7cs", 2],
      ["7bt", 3],
      ["7bw", 1],
      ["7cr", 3],
      ["7br", 3],
      ["6cs", 1],
      ["6hx", 3],
      ["obd", 1],
    ],
  },
  weap78: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7lw", 2],
      ["7qs", 1],
      ["7fl", 3],
      ["7bs", 3],
      ["7b7", 3],
      ["7bk", 3],
      ["6l7", 3],
      ["amc", 1],
    ],
  },
  weap81: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7tw", 2],
      ["7mp", 3],
      ["7fb", 3],
      ["7b8", 3],
      ["7gl", 3],
      ["7pa", 3],
      ["6sw", 3],
      ["ame", 1],
    ],
  },
  weap84: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7ga", 3],
      ["7wh", 3],
      ["7ls", 3],
      ["7kr", 3],
      ["7st", 3],
      ["7h7", 3],
      ["6bs", 1],
      ["6rx", 3],
      ["obe", 1],
    ],
  },
  weap87: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["7qr", 2],
      ["7wa", 3],
      ["7gi", 3],
      ["7gw", 1],
      ["7ws", 1],
      ["7gm", 3],
      ["7wd", 3],
      ["7gd", 3],
      ["7bl", 3],
      ["7ts", 3],
      ["7p7", 3],
      ["7wc", 3],
      ["6ws", 1],
      ["6lw", 3],
      ["obf", 1],
    ],
  },
  weap9: {
    nodrop: 0,
    picks: 1,
    qualityRatios: [0, 0, 0, 0],
    tcs: [
      ["axe", 3],
      ["mac", 3],
      ["sbr", 3],
      ["dir", 3],
      ["tax", 3],
      ["tri", 3],
      ["lst", 1],
      ["lbw", 3],
      ["wrb", 2],
      ["ob2", 1],
    ],
  },
};
