export type ItemObject = {
  name: string;
  type: string;
  code: string;
};

export type ItemDictType = {
  [key: string]: ItemObject;
};

export const ItemDict: ItemDictType = {
  hax: { name: "Hand Axe", type: "axe", code: "hax" },
  axe: { name: "Axe", type: "axe", code: "axe" },
  "2ax": { name: "Double Axe", type: "axe", code: "2ax" },
  mpi: { name: "Military Pick", type: "axe", code: "mpi" },
  wax: { name: "War Axe", type: "axe", code: "wax" },
  lax: { name: "Large Axe", type: "axe", code: "lax" },
  bax: { name: "Broad Axe", type: "axe", code: "bax" },
  btx: { name: "Battle Axe", type: "axe", code: "btx" },
  gax: { name: "Great Axe", type: "axe", code: "gax" },
  gix: { name: "Giant Axe", type: "axe", code: "gix" },
  wnd: { name: "Wand", type: "wand", code: "wnd" },
  ywn: { name: "Yew Wand", type: "wand", code: "ywn" },
  bwn: { name: "Bone Wand", type: "wand", code: "bwn" },
  gwn: { name: "Grim Wand", type: "wand", code: "gwn" },
  clb: { name: "Club", type: "club", code: "clb" },
  scp: { name: "Scepter", type: "scep", code: "scp" },
  gsc: { name: "Grand Scepter", type: "scep", code: "gsc" },
  wsp: { name: "War Scepter", type: "scep", code: "wsp" },
  spc: { name: "Spiked Club", type: "club", code: "spc" },
  mac: { name: "Mace", type: "mace", code: "mac" },
  mst: { name: "Morning Star", type: "mace", code: "mst" },
  fla: { name: "Flail", type: "mace", code: "fla" },
  whm: { name: "War Hammer", type: "hamm", code: "whm" },
  mau: { name: "Maul", type: "hamm", code: "mau" },
  gma: { name: "Great Maul", type: "hamm", code: "gma" },
  ssd: { name: "Short Sword", type: "swor", code: "ssd" },
  scm: { name: "Scimitar", type: "swor", code: "scm" },
  sbr: { name: "Saber", type: "swor", code: "sbr" },
  flc: { name: "Falchion", type: "swor", code: "flc" },
  crs: { name: "Crystal Sword", type: "swor", code: "crs" },
  bsd: { name: "Broad Sword", type: "swor", code: "bsd" },
  lsd: { name: "Long Sword", type: "swor", code: "lsd" },
  wsd: { name: "War Sword", type: "swor", code: "wsd" },
  "2hs": { name: "Two-Handed Sword", type: "swor", code: "2hs" },
  clm: { name: "Claymore", type: "swor", code: "clm" },
  gis: { name: "Giant Sword", type: "swor", code: "gis" },
  bsw: { name: "Bastard Sword", type: "swor", code: "bsw" },
  flb: { name: "Flamberge", type: "swor", code: "flb" },
  gsd: { name: "Great Sword", type: "swor", code: "gsd" },
  dgr: { name: "Dagger", type: "knif", code: "dgr" },
  dir: { name: "Dirk", type: "knif", code: "dir" },
  kri: { name: "Kriss", type: "knif", code: "kri" },
  bld: { name: "Blade", type: "knif", code: "bld" },
  tkf: { name: "Throwing Knife", type: "tkni", code: "tkf" },
  tax: { name: "Throwing Axe", type: "taxe", code: "tax" },
  bkf: { name: "Balanced Knife", type: "tkni", code: "bkf" },
  bal: { name: "Balanced Axe", type: "taxe", code: "bal" },
  jav: { name: "Javelin", type: "jave", code: "jav" },
  pil: { name: "Pilum", type: "jave", code: "pil" },
  ssp: { name: "Short Spear", type: "jave", code: "ssp" },
  glv: { name: "Glaive", type: "jave", code: "glv" },
  tsp: { name: "Throwing Spear", type: "jave", code: "tsp" },
  spr: { name: "Spear", type: "spea", code: "spr" },
  tri: { name: "Trident", type: "spea", code: "tri" },
  brn: { name: "Brandistock", type: "spea", code: "brn" },
  spt: { name: "Spetum", type: "spea", code: "spt" },
  pik: { name: "Pike", type: "spea", code: "pik" },
  bar: { name: "Bardiche", type: "pole", code: "bar" },
  vou: { name: "Voulge", type: "pole", code: "vou" },
  scy: { name: "Scythe", type: "pole", code: "scy" },
  pax: { name: "Poleaxe", type: "pole", code: "pax" },
  hal: { name: "Halberd", type: "pole", code: "hal" },
  wsc: { name: "War Scythe", type: "pole", code: "wsc" },
  sst: { name: "Short Staff", type: "staf", code: "sst" },
  lst: { name: "Long Staff", type: "staf", code: "lst" },
  cst: { name: "Gnarled Staff", type: "staf", code: "cst" },
  bst: { name: "Battle Staff", type: "staf", code: "bst" },
  wst: { name: "War Staff", type: "staf", code: "wst" },
  sbw: { name: "Short Bow", type: "bow", code: "sbw" },
  hbw: { name: "Hunter's Bow", type: "bow", code: "hbw" },
  lbw: { name: "Long Bow", type: "bow", code: "lbw" },
  cbw: { name: "Composite Bow", type: "bow", code: "cbw" },
  sbb: { name: "Short Battle Bow", type: "bow", code: "sbb" },
  lbb: { name: "Long Battle Bow", type: "bow", code: "lbb" },
  swb: { name: "Short War Bow", type: "bow", code: "swb" },
  lwb: { name: "Long War Bow", type: "bow", code: "lwb" },
  lxb: { name: "Light Crossbow", type: "xbow", code: "lxb" },
  mxb: { name: "Crossbow", type: "xbow", code: "mxb" },
  hxb: { name: "Heavy Crossbow", type: "xbow", code: "hxb" },
  rxb: { name: "Repeating Crossbow", type: "xbow", code: "rxb" },
  gps: { name: "Rancid Gas Potion", type: "tpot", code: "gps" },
  ops: { name: "Oil Potion", type: "tpot", code: "ops" },
  gpm: { name: "Choking Gas Potion", type: "tpot", code: "gpm" },
  opm: { name: "Exploding Potion", type: "tpot", code: "opm" },
  gpl: { name: "Strangling Gas Potion", type: "tpot", code: "gpl" },
  opl: { name: "Fulminating Potion", type: "tpot", code: "opl" },
  d33: { name: "Decoy Gidbinn", type: "knif", code: "d33" },
  g33: { name: "The Gidbinn", type: "knif", code: "g33" },
  leg: { name: "Wirt's Leg", type: "club", code: "leg" },
  hdm: { name: "Horadric Malus", type: "hamm", code: "hdm" },
  hfh: { name: "Hellforge Hammer", type: "hamm", code: "hfh" },
  hst: { name: "Horadric Staff", type: "staf", code: "hst" },
  msf: { name: "Staff of Kings", type: "staf", code: "msf" },
  "9ha": { name: "Hatchet", type: "axe", code: "9ha" },
  "9ax": { name: "Cleaver", type: "axe", code: "9ax" },
  "92a": { name: "Twin Axe", type: "axe", code: "92a" },
  "9mp": { name: "Crowbill", type: "axe", code: "9mp" },
  "9wa": { name: "Naga", type: "axe", code: "9wa" },
  "9la": { name: "Military Axe", type: "axe", code: "9la" },
  "9ba": { name: "Bearded Axe", type: "axe", code: "9ba" },
  "9bt": { name: "Tabar", type: "axe", code: "9bt" },
  "9ga": { name: "Gothic Axe", type: "axe", code: "9ga" },
  "9gi": { name: "Ancient Axe", type: "axe", code: "9gi" },
  "9wn": { name: "Burnt Wand", type: "wand", code: "9wn" },
  "9yw": { name: "Petrified Wand", type: "wand", code: "9yw" },
  "9bw": { name: "Tomb Wand", type: "wand", code: "9bw" },
  "9gw": { name: "Grave Wand", type: "wand", code: "9gw" },
  "9cl": { name: "Cudgel", type: "club", code: "9cl" },
  "9sc": { name: "Rune Scepter", type: "scep", code: "9sc" },
  "9qs": { name: "Holy Water Sprinkler", type: "scep", code: "9qs" },
  "9ws": { name: "Divine Scepter", type: "scep", code: "9ws" },
  "9sp": { name: "Barbed Club", type: "club", code: "9sp" },
  "9ma": { name: "Flanged Mace", type: "mace", code: "9ma" },
  "9mt": { name: "Jagged Star", type: "mace", code: "9mt" },
  "9fl": { name: "Knout", type: "mace", code: "9fl" },
  "9wh": { name: "Battle Hammer", type: "hamm", code: "9wh" },
  "9m9": { name: "War Club", type: "hamm", code: "9m9" },
  "9gm": { name: "Martel de Fer", type: "hamm", code: "9gm" },
  "9ss": { name: "Gladius", type: "swor", code: "9ss" },
  "9sm": { name: "Cutlass", type: "swor", code: "9sm" },
  "9sb": { name: "Shamshir", type: "swor", code: "9sb" },
  "9fc": { name: "Tulwar", type: "swor", code: "9fc" },
  "9cr": { name: "Dimensional Blade", type: "swor", code: "9cr" },
  "9bs": { name: "Battle Sword", type: "swor", code: "9bs" },
  "9ls": { name: "Rune Sword", type: "swor", code: "9ls" },
  "9wd": { name: "Ancient Sword", type: "swor", code: "9wd" },
  "92h": { name: "Espandon", type: "swor", code: "92h" },
  "9cm": { name: "Dacian Falx", type: "swor", code: "9cm" },
  "9gs": { name: "Tusk Sword", type: "swor", code: "9gs" },
  "9b9": { name: "Gothic Sword", type: "swor", code: "9b9" },
  "9fb": { name: "Zweihander", type: "swor", code: "9fb" },
  "9gd": { name: "Executioner Sword", type: "swor", code: "9gd" },
  "9dg": { name: "Poignard", type: "knif", code: "9dg" },
  "9di": { name: "Rondel", type: "knif", code: "9di" },
  "9kr": { name: "Cinquedeas", type: "knif", code: "9kr" },
  "9bl": { name: "Stilleto", type: "knif", code: "9bl" },
  "9tk": { name: "Battle Dart", type: "tkni", code: "9tk" },
  "9ta": { name: "Francisca", type: "taxe", code: "9ta" },
  "9bk": { name: "War Dart", type: "tkni", code: "9bk" },
  "9b8": { name: "Hurlbat", type: "taxe", code: "9b8" },
  "9ja": { name: "War Javelin", type: "jave", code: "9ja" },
  "9pi": { name: "Great Pilum", type: "jave", code: "9pi" },
  "9s9": { name: "Simbilan", type: "jave", code: "9s9" },
  "9gl": { name: "Spiculum", type: "jave", code: "9gl" },
  "9ts": { name: "Harpoon", type: "jave", code: "9ts" },
  "9sr": { name: "War Spear", type: "spea", code: "9sr" },
  "9tr": { name: "Fuscina", type: "spea", code: "9tr" },
  "9br": { name: "War Fork", type: "spea", code: "9br" },
  "9st": { name: "Yari", type: "spea", code: "9st" },
  "9p9": { name: "Lance", type: "spea", code: "9p9" },
  "9b7": { name: "Lochaber Axe", type: "pole", code: "9b7" },
  "9vo": { name: "Bill", type: "pole", code: "9vo" },
  "9s8": { name: "Battle Scythe", type: "pole", code: "9s8" },
  "9pa": { name: "Partizan", type: "pole", code: "9pa" },
  "9h9": { name: "Bec-de-Corbin", type: "pole", code: "9h9" },
  "9wc": { name: "Grim Scythe", type: "pole", code: "9wc" },
  "8ss": { name: "Jo Staff", type: "staf", code: "8ss" },
  "8ls": { name: "Quarterstaff", type: "staf", code: "8ls" },
  "8cs": { name: "Cedar Staff", type: "staf", code: "8cs" },
  "8bs": { name: "Gothic Staff", type: "staf", code: "8bs" },
  "8ws": { name: "Rune Staff", type: "staf", code: "8ws" },
  "8sb": { name: "Edge Bow", type: "bow", code: "8sb" },
  "8hb": { name: "Razor Bow", type: "bow", code: "8hb" },
  "8lb": { name: "Cedar Bow", type: "bow", code: "8lb" },
  "8cb": { name: "Double Bow", type: "bow", code: "8cb" },
  "8s8": { name: "Short Siege Bow", type: "bow", code: "8s8" },
  "8l8": { name: "Long Siege Bow", type: "bow", code: "8l8" },
  "8sw": { name: "Rune Bow", type: "bow", code: "8sw" },
  "8lw": { name: "Gothic Bow", type: "bow", code: "8lw" },
  "8lx": { name: "Arbalest", type: "xbow", code: "8lx" },
  "8mx": { name: "Siege Crossbow", type: "xbow", code: "8mx" },
  "8hx": { name: "Ballista", type: "xbow", code: "8hx" },
  "8rx": { name: "Chu-Ko-Nu", type: "xbow", code: "8rx" },
  qf1: { name: "Khalim's Flail", type: "mace", code: "qf1" },
  qf2: { name: "Khalim's Will", type: "mace", code: "qf2" },
  ktr: { name: "Katar", type: "h2h", code: "ktr" },
  wrb: { name: "Wrist Blade", type: "h2h", code: "wrb" },
  axf: { name: "Hatchet Hands", type: "h2h", code: "axf" },
  ces: { name: "Cestus", type: "h2h", code: "ces" },
  clw: { name: "Claws", type: "h2h", code: "clw" },
  btl: { name: "Blade Talons", type: "h2h", code: "btl" },
  skr: { name: "Scissors Katar", type: "h2h", code: "skr" },
  "9ar": { name: "Quhab", type: "h2h", code: "9ar" },
  "9wb": { name: "Wrist Spike", type: "h2h", code: "9wb" },
  "9xf": { name: "Fascia", type: "h2h", code: "9xf" },
  "9cs": { name: "Hand Scythe", type: "h2h2", code: "9cs" },
  "9lw": { name: "Greater Claws", type: "h2h2", code: "9lw" },
  "9tw": { name: "Greater Talons", type: "h2h2", code: "9tw" },
  "9qr": { name: "Scissors Quhab", type: "h2h2", code: "9qr" },
  "7ar": { name: "Suwayyah", type: "h2h2", code: "7ar" },
  "7wb": { name: "Wrist Sword", type: "h2h2", code: "7wb" },
  "7xf": { name: "War Fist", type: "h2h2", code: "7xf" },
  "7cs": { name: "Battle Cestus", type: "h2h2", code: "7cs" },
  "7lw": { name: "Feral Claws", type: "h2h2", code: "7lw" },
  "7tw": { name: "Runic Talons", type: "h2h2", code: "7tw" },
  "7qr": { name: "Scissors Suwayyah", type: "h2h2", code: "7qr" },
  "7ha": { name: "Tomahawk", type: "axe", code: "7ha" },
  "7ax": { name: "Small Crescent", type: "axe", code: "7ax" },
  "72a": { name: "Ettin Axe", type: "axe", code: "72a" },
  "7mp": { name: "War Spike", type: "axe", code: "7mp" },
  "7wa": { name: "Berserker Axe", type: "axe", code: "7wa" },
  "7la": { name: "Feral Axe", type: "axe", code: "7la" },
  "7ba": { name: "Silver-edged Axe", type: "axe", code: "7ba" },
  "7bt": { name: "Decapitator", type: "axe", code: "7bt" },
  "7ga": { name: "Champion Axe", type: "axe", code: "7ga" },
  "7gi": { name: "Glorious Axe", type: "axe", code: "7gi" },
  "7wn": { name: "Polished Wand", type: "wand", code: "7wn" },
  "7yw": { name: "Ghost Wand", type: "wand", code: "7yw" },
  "7bw": { name: "Lich Wand", type: "wand", code: "7bw" },
  "7gw": { name: "Unearthed Wand", type: "wand", code: "7gw" },
  "7cl": { name: "Truncheon", type: "club", code: "7cl" },
  "7sc": { name: "Mighty Scepter", type: "scep", code: "7sc" },
  "7qs": { name: "Seraph Rod", type: "scep", code: "7qs" },
  "7ws": { name: "Caduceus", type: "scep", code: "7ws" },
  "7sp": { name: "Tyrant Club", type: "club", code: "7sp" },
  "7ma": { name: "Reinforced Mace", type: "mace", code: "7ma" },
  "7mt": { name: "Devil Star", type: "mace", code: "7mt" },
  "7fl": { name: "Scourge", type: "mace", code: "7fl" },
  "7wh": { name: "Legendary Mallet", type: "hamm", code: "7wh" },
  "7m7": { name: "Ogre Maul", type: "hamm", code: "7m7" },
  "7gm": { name: "Thunder Maul", type: "hamm", code: "7gm" },
  "7ss": { name: "Falcata", type: "swor", code: "7ss" },
  "7sm": { name: "Ataghan", type: "swor", code: "7sm" },
  "7sb": { name: "Elegant Blade", type: "swor", code: "7sb" },
  "7fc": { name: "Hydra Edge", type: "swor", code: "7fc" },
  "7cr": { name: "Phase Blade", type: "swor", code: "7cr" },
  "7bs": { name: "Conquest Sword", type: "swor", code: "7bs" },
  "7ls": { name: "Cryptic Sword", type: "swor", code: "7ls" },
  "7wd": { name: "Mythical Sword", type: "swor", code: "7wd" },
  "72h": { name: "Legend Sword", type: "swor", code: "72h" },
  "7cm": { name: "Highland Blade", type: "swor", code: "7cm" },
  "7gs": { name: "Balrog Blade", type: "swor", code: "7gs" },
  "7b7": { name: "Champion Sword", type: "swor", code: "7b7" },
  "7fb": { name: "Colossal Sword", type: "swor", code: "7fb" },
  "7gd": { name: "Colossus Blade", type: "swor", code: "7gd" },
  "7dg": { name: "Bone Knife", type: "knif", code: "7dg" },
  "7di": { name: "Mithral Point", type: "knif", code: "7di" },
  "7kr": { name: "Fanged Knife", type: "knif", code: "7kr" },
  "7bl": { name: "Legend Spike", type: "knif", code: "7bl" },
  "7tk": { name: "Flying Knife", type: "tkni", code: "7tk" },
  "7ta": { name: "Flying Axe", type: "taxe", code: "7ta" },
  "7bk": { name: "Winged Knife", type: "tkni", code: "7bk" },
  "7b8": { name: "Winged Axe", type: "taxe", code: "7b8" },
  "7ja": { name: "Hyperion Javelin", type: "jave", code: "7ja" },
  "7pi": { name: "Stygian Pilum", type: "jave", code: "7pi" },
  "7s7": { name: "Balrog Spear", type: "jave", code: "7s7" },
  "7gl": { name: "Ghost Glaive", type: "jave", code: "7gl" },
  "7ts": { name: "Winged Harpoon", type: "jave", code: "7ts" },
  "7sr": { name: "Hyperion Spear", type: "spea", code: "7sr" },
  "7tr": { name: "Stygian Pike", type: "spea", code: "7tr" },
  "7br": { name: "Mancatcher", type: "spea", code: "7br" },
  "7st": { name: "Ghost Spear", type: "spea", code: "7st" },
  "7p7": { name: "War Pike", type: "spea", code: "7p7" },
  "7o7": { name: "Ogre Axe", type: "pole", code: "7o7" },
  "7vo": { name: "Colossus Voulge", type: "pole", code: "7vo" },
  "7s8": { name: "Thresher", type: "pole", code: "7s8" },
  "7pa": { name: "Cryptic Axe", type: "pole", code: "7pa" },
  "7h7": { name: "Great Poleaxe", type: "pole", code: "7h7" },
  "7wc": { name: "Giant Thresher", type: "pole", code: "7wc" },
  "6ss": { name: "Walking Stick", type: "staf", code: "6ss" },
  "6ls": { name: "Stalagmite", type: "staf", code: "6ls" },
  "6cs": { name: "Elder Staff", type: "staf", code: "6cs" },
  "6bs": { name: "Shillelagh", type: "staf", code: "6bs" },
  "6ws": { name: "Archon Staff", type: "staf", code: "6ws" },
  "6sb": { name: "Spider Bow", type: "bow", code: "6sb" },
  "6hb": { name: "Blade Bow", type: "bow", code: "6hb" },
  "6lb": { name: "Shadow Bow", type: "bow", code: "6lb" },
  "6cb": { name: "Great Bow", type: "bow", code: "6cb" },
  "6s7": { name: "Diamond Bow", type: "bow", code: "6s7" },
  "6l7": { name: "Crusader Bow", type: "bow", code: "6l7" },
  "6sw": { name: "Ward Bow", type: "bow", code: "6sw" },
  "6lw": { name: "Hydra Bow", type: "bow", code: "6lw" },
  "6lx": { name: "Pellet Bow", type: "xbow", code: "6lx" },
  "6mx": { name: "Gorgon Crossbow", type: "xbow", code: "6mx" },
  "6hx": { name: "Colossus Crossbow", type: "xbow", code: "6hx" },
  "6rx": { name: "Demon Crossbow", type: "xbow", code: "6rx" },
  ob1: { name: "Eagle Orb", type: "orb", code: "ob1" },
  ob2: { name: "Sacred Globe", type: "orb", code: "ob2" },
  ob3: { name: "Smoked Sphere", type: "orb", code: "ob3" },
  ob4: { name: "Clasped Orb", type: "orb", code: "ob4" },
  ob5: { name: "Jared's Stone", type: "orb", code: "ob5" },
  am1: { name: "Stag Bow", type: "abow", code: "am1" },
  am2: { name: "ReflexBow", type: "abow", code: "am2" },
  am3: { name: "Maiden Spear", type: "aspe", code: "am3" },
  am4: { name: "Maiden Pike", type: "aspe", code: "am4" },
  am5: { name: "Maiden Javelin", type: "ajav", code: "am5" },
  ob6: { name: "Glowing Orb", type: "orb", code: "ob6" },
  ob7: { name: "Crystalline Globe", type: "orb", code: "ob7" },
  ob8: { name: "Cloudy Sphere", type: "orb", code: "ob8" },
  ob9: { name: "Sparkling Ball", type: "orb", code: "ob9" },
  oba: { name: "Swirling Crystal", type: "orb", code: "oba" },
  am6: { name: "Ashwood Bow", type: "abow", code: "am6" },
  am7: { name: "Ceremonial Bow", type: "abow", code: "am7" },
  am8: { name: "Ceremonial Spear", type: "aspe", code: "am8" },
  am9: { name: "Ceremonial Pike", type: "aspe", code: "am9" },
  ama: { name: "Ceremonial Javelin", type: "ajav", code: "ama" },
  obb: { name: "Heavenly Stone", type: "orb", code: "obb" },
  obc: { name: "Eldritch Orb", type: "orb", code: "obc" },
  obd: { name: "Demon Heart", type: "orb", code: "obd" },
  obe: { name: "Vortex Orb", type: "orb", code: "obe" },
  obf: { name: "Dimensional Shard", type: "orb", code: "obf" },
  amb: { name: "Matriarchal Bow", type: "abow", code: "amb" },
  amc: { name: "Grand Matron Bow", type: "abow", code: "amc" },
  amd: { name: "Matriarchal Spear", type: "aspe", code: "amd" },
  ame: { name: "Matriarchal Pike", type: "aspe", code: "ame" },
  amf: { name: "Matriarchal Javelin", type: "ajav", code: "amf" },
  cap: { name: "Cap", type: "helm", code: "cap" },
  skp: { name: "Skull Cap", type: "helm", code: "skp" },
  hlm: { name: "Helm", type: "helm", code: "hlm" },
  fhl: { name: "Full Helm", type: "helm", code: "fhl" },
  ghm: { name: "Great Helm", type: "helm", code: "ghm" },
  crn: { name: "Crown", type: "helm", code: "crn" },
  msk: { name: "Mask", type: "helm", code: "msk" },
  qui: { name: "Quilted Armor", type: "tors", code: "qui" },
  lea: { name: "Leather Armor", type: "tors", code: "lea" },
  hla: { name: "Hard Leather Armor", type: "tors", code: "hla" },
  stu: { name: "Studded Leather", type: "tors", code: "stu" },
  rng: { name: "Ring Mail", type: "tors", code: "rng" },
  scl: { name: "Scale Mail", type: "tors", code: "scl" },
  chn: { name: "Chain Mail", type: "tors", code: "chn" },
  brs: { name: "Breast Plate", type: "tors", code: "brs" },
  spl: { name: "Splint Mail", type: "tors", code: "spl" },
  plt: { name: "Plate Mail", type: "tors", code: "plt" },
  fld: { name: "Field Plate", type: "tors", code: "fld" },
  gth: { name: "Gothic Plate", type: "tors", code: "gth" },
  ful: { name: "Full Plate Mail", type: "tors", code: "ful" },
  aar: { name: "Ancient Armor", type: "tors", code: "aar" },
  ltp: { name: "Light Plate", type: "tors", code: "ltp" },
  buc: { name: "Buckler", type: "shie", code: "buc" },
  sml: { name: "Small Shield", type: "shie", code: "sml" },
  lrg: { name: "Large Shield", type: "shie", code: "lrg" },
  kit: { name: "Kite Shield", type: "shie", code: "kit" },
  tow: { name: "Tower Shield", type: "shie", code: "tow" },
  gts: { name: "Gothic Shield", type: "shie", code: "gts" },
  lgl: { name: "Leather Gloves", type: "glov", code: "lgl" },
  vgl: { name: "Heavy Gloves", type: "glov", code: "vgl" },
  mgl: { name: "Chain Gloves", type: "glov", code: "mgl" },
  tgl: { name: "Light Gauntlets", type: "glov", code: "tgl" },
  hgl: { name: "Gauntlets", type: "glov", code: "hgl" },
  lbt: { name: "Boots", type: "boot", code: "lbt" },
  vbt: { name: "Heavy Boots", type: "boot", code: "vbt" },
  mbt: { name: "Chain Boots", type: "boot", code: "mbt" },
  tbt: { name: "Light Plated Boots", type: "boot", code: "tbt" },
  hbt: { name: "Greaves", type: "boot", code: "hbt" },
  lbl: { name: "Sash", type: "belt", code: "lbl" },
  vbl: { name: "Light Belt", type: "belt", code: "vbl" },
  mbl: { name: "Belt", type: "belt", code: "mbl" },
  tbl: { name: "Heavy Belt", type: "belt", code: "tbl" },
  hbl: { name: "Plated Belt", type: "belt", code: "hbl" },
  bhm: { name: "Bone Helm", type: "helm", code: "bhm" },
  bsh: { name: "Bone Shield", type: "shie", code: "bsh" },
  spk: { name: "Spiked Shield", type: "shie", code: "spk" },
  xap: { name: "War Hat", type: "helm", code: "xap" },
  xkp: { name: "Sallet", type: "helm", code: "xkp" },
  xlm: { name: "Casque", type: "helm", code: "xlm" },
  xhl: { name: "Basinet", type: "helm", code: "xhl" },
  xhm: { name: "Winged Helm", type: "helm", code: "xhm" },
  xrn: { name: "Grand Crown", type: "helm", code: "xrn" },
  xsk: { name: "Death Mask", type: "helm", code: "xsk" },
  xui: { name: "Ghost Armor", type: "tors", code: "xui" },
  xea: { name: "Serpentskin Armor", type: "tors", code: "xea" },
  xla: { name: "Demonhide Armor", type: "tors", code: "xla" },
  xtu: { name: "Trellised Armor", type: "tors", code: "xtu" },
  xng: { name: "Linked Mail", type: "tors", code: "xng" },
  xcl: { name: "Tigulated Mail", type: "tors", code: "xcl" },
  xhn: { name: "Mesh Armor", type: "tors", code: "xhn" },
  xrs: { name: "Cuirass", type: "tors", code: "xrs" },
  xpl: { name: "Russet Armor", type: "tors", code: "xpl" },
  xlt: { name: "Templar Coat", type: "tors", code: "xlt" },
  xld: { name: "Sharktooth Armor", type: "tors", code: "xld" },
  xth: { name: "Embossed Plate", type: "tors", code: "xth" },
  xul: { name: "Chaos Armor", type: "tors", code: "xul" },
  xar: { name: "Ornate Armor", type: "tors", code: "xar" },
  xtp: { name: "Mage Plate", type: "tors", code: "xtp" },
  xuc: { name: "Defender", type: "shie", code: "xuc" },
  xml: { name: "Round Shield", type: "shie", code: "xml" },
  xrg: { name: "Scutum", type: "shie", code: "xrg" },
  xit: { name: "Dragon Shield", type: "shie", code: "xit" },
  xow: { name: "Pavise", type: "shie", code: "xow" },
  xts: { name: "Ancient Shield", type: "shie", code: "xts" },
  xlg: { name: "Demonhide Gloves", type: "glov", code: "xlg" },
  xvg: { name: "Sharkskin Gloves", type: "glov", code: "xvg" },
  xmg: { name: "Heavy Bracers", type: "glov", code: "xmg" },
  xtg: { name: "Battle Gauntlets", type: "glov", code: "xtg" },
  xhg: { name: "War Gauntlets", type: "glov", code: "xhg" },
  xlb: { name: "Demonhide Boots", type: "boot", code: "xlb" },
  xvb: { name: "Sharkskin Boots", type: "boot", code: "xvb" },
  xmb: { name: "Mesh Boots", type: "boot", code: "xmb" },
  xtb: { name: "Battle Boots", type: "boot", code: "xtb" },
  xhb: { name: "War Boots", type: "boot", code: "xhb" },
  zlb: { name: "Demonhide Sash", type: "belt", code: "zlb" },
  zvb: { name: "Sharkskin Belt", type: "belt", code: "zvb" },
  zmb: { name: "Mesh Belt", type: "belt", code: "zmb" },
  ztb: { name: "Battle Belt", type: "belt", code: "ztb" },
  zhb: { name: "War Belt", type: "belt", code: "zhb" },
  xh9: { name: "Grim Helm", type: "helm", code: "xh9" },
  xsh: { name: "Grim Shield", type: "shie", code: "xsh" },
  xpk: { name: "Barbed Shield", type: "shie", code: "xpk" },
  dr1: { name: "Wolf Head", type: "pelt", code: "dr1" },
  dr2: { name: "Hawk Helm", type: "pelt", code: "dr2" },
  dr3: { name: "Antlers", type: "pelt", code: "dr3" },
  dr4: { name: "Falcon Mask", type: "pelt", code: "dr4" },
  dr5: { name: "Spirit Mask", type: "pelt", code: "dr5" },
  ba1: { name: "Jawbone Cap", type: "phlm", code: "ba1" },
  ba2: { name: "Fanged Helm", type: "phlm", code: "ba2" },
  ba3: { name: "Horned Helm", type: "phlm", code: "ba3" },
  ba4: { name: "Assault Helmet", type: "phlm", code: "ba4" },
  ba5: { name: "Avenger Guard", type: "phlm", code: "ba5" },
  pa1: { name: "Targe", type: "ashd", code: "pa1" },
  pa2: { name: "Rondache", type: "ashd", code: "pa2" },
  pa3: { name: "Heraldic Shield", type: "ashd", code: "pa3" },
  pa4: { name: "Aerin Shield", type: "ashd", code: "pa4" },
  pa5: { name: "Crown Shield", type: "ashd", code: "pa5" },
  ne1: { name: "Preserved Head", type: "head", code: "ne1" },
  ne2: { name: "Zombie Head", type: "head", code: "ne2" },
  ne3: { name: "Unraveller Head", type: "head", code: "ne3" },
  ne4: { name: "Gargoyle Head", type: "head", code: "ne4" },
  ne5: { name: "Demon Head", type: "head", code: "ne5" },
  ci0: { name: "Circlet", type: "circ", code: "ci0" },
  ci1: { name: "Coronet", type: "circ", code: "ci1" },
  ci2: { name: "Tiara", type: "circ", code: "ci2" },
  ci3: { name: "Diadem", type: "circ", code: "ci3" },
  uap: { name: "Shako", type: "helm", code: "uap" },
  ukp: { name: "Hydraskull", type: "helm", code: "ukp" },
  ulm: { name: "Armet", type: "helm", code: "ulm" },
  uhl: { name: "Giant Conch", type: "helm", code: "uhl" },
  uhm: { name: "Spired Helm", type: "helm", code: "uhm" },
  urn: { name: "Corona", type: "helm", code: "urn" },
  usk: { name: "Demonhead", type: "helm", code: "usk" },
  uui: { name: "Dusk Shroud", type: "tors", code: "uui" },
  uea: { name: "Wyrmhide", type: "tors", code: "uea" },
  ula: { name: "Scarab Husk", type: "tors", code: "ula" },
  utu: { name: "Wire Fleece", type: "tors", code: "utu" },
  ung: { name: "Diamond Mail", type: "tors", code: "ung" },
  ucl: { name: "Loricated Mail", type: "tors", code: "ucl" },
  uhn: { name: "Boneweave", type: "tors", code: "uhn" },
  urs: { name: "Great Hauberk", type: "tors", code: "urs" },
  upl: { name: "Balrog Skin", type: "tors", code: "upl" },
  ult: { name: "Hellforge Plate", type: "tors", code: "ult" },
  uld: { name: "Kraken Shell", type: "tors", code: "uld" },
  uth: { name: "Lacquered Plate", type: "tors", code: "uth" },
  uul: { name: "Shadow Plate", type: "tors", code: "uul" },
  uar: { name: "Sacred Armor", type: "tors", code: "uar" },
  utp: { name: "Archon Plate", type: "tors", code: "utp" },
  uuc: { name: "Heater", type: "shie", code: "uuc" },
  uml: { name: "Luna", type: "shie", code: "uml" },
  urg: { name: "Hyperion", type: "shie", code: "urg" },
  uit: { name: "Monarch", type: "shie", code: "uit" },
  uow: { name: "Aegis", type: "shie", code: "uow" },
  uts: { name: "Ward", type: "shie", code: "uts" },
  ulg: { name: "Bramble Mitts", type: "glov", code: "ulg" },
  uvg: { name: "Vampirebone Gloves", type: "glov", code: "uvg" },
  umg: { name: "Vambraces", type: "glov", code: "umg" },
  utg: { name: "Crusader Gauntlets", type: "glov", code: "utg" },
  uhg: { name: "Ogre Gauntlets", type: "glov", code: "uhg" },
  ulb: { name: "Wyrmhide Boots", type: "boot", code: "ulb" },
  uvb: { name: "Scarabshell Boots", type: "boot", code: "uvb" },
  umb: { name: "Boneweave Boots", type: "boot", code: "umb" },
  utb: { name: "Mirrored Boots", type: "boot", code: "utb" },
  uhb: { name: "Myrmidon Greaves", type: "boot", code: "uhb" },
  ulc: { name: "Spiderweb Sash", type: "belt", code: "ulc" },
  uvc: { name: "Vampirefang Belt", type: "belt", code: "uvc" },
  umc: { name: "Mithril Coil", type: "belt", code: "umc" },
  utc: { name: "Troll Belt", type: "belt", code: "utc" },
  uhc: { name: "Colossus Girdle", type: "belt", code: "uhc" },
  uh9: { name: "Bone Visage", type: "helm", code: "uh9" },
  ush: { name: "Troll Nest", type: "shie", code: "ush" },
  upk: { name: "Blade Barrier", type: "shie", code: "upk" },
  dr6: { name: "Alpha Helm", type: "pelt", code: "dr6" },
  dr7: { name: "Griffon Headress", type: "pelt", code: "dr7" },
  dr8: { name: "Hunter's Guise", type: "pelt", code: "dr8" },
  dr9: { name: "Sacred Feathers", type: "pelt", code: "dr9" },
  dra: { name: "Totemic Mask", type: "pelt", code: "dra" },
  ba6: { name: "Jawbone Visor", type: "phlm", code: "ba6" },
  ba7: { name: "Lion Helm", type: "phlm", code: "ba7" },
  ba8: { name: "Rage Mask", type: "phlm", code: "ba8" },
  ba9: { name: "Savage Helmet", type: "phlm", code: "ba9" },
  baa: { name: "Slayer Guard", type: "phlm", code: "baa" },
  pa6: { name: "Akaran Targe", type: "ashd", code: "pa6" },
  pa7: { name: "Akaran Rondache", type: "ashd", code: "pa7" },
  pa8: { name: "Protector Shield", type: "ashd", code: "pa8" },
  pa9: { name: "Gilded Shield", type: "ashd", code: "pa9" },
  paa: { name: "RoyalShield", type: "ashd", code: "paa" },
  ne6: { name: "Mummified Trophy", type: "head", code: "ne6" },
  ne7: { name: "Fetish Trophy", type: "head", code: "ne7" },
  ne8: { name: "Sexton Trophy", type: "head", code: "ne8" },
  ne9: { name: "Cantor Trophy", type: "head", code: "ne9" },
  nea: { name: "Heirophant Trophy", type: "head", code: "nea" },
  drb: { name: "Blood Spirit", type: "pelt", code: "drb" },
  drc: { name: "Sun Spirit", type: "pelt", code: "drc" },
  drd: { name: "Earth Spirit", type: "pelt", code: "drd" },
  dre: { name: "Sky Spirit", type: "pelt", code: "dre" },
  drf: { name: "Dream Spirit", type: "pelt", code: "drf" },
  bab: { name: "Carnage Helm", type: "phlm", code: "bab" },
  bac: { name: "Fury Visor", type: "phlm", code: "bac" },
  bad: { name: "Destroyer Helm", type: "phlm", code: "bad" },
  bae: { name: "Conqueror Crown", type: "phlm", code: "bae" },
  baf: { name: "Guardian Crown", type: "phlm", code: "baf" },
  pab: { name: "Sacred Targe", type: "ashd", code: "pab" },
  pac: { name: "Sacred Rondache", type: "ashd", code: "pac" },
  pad: { name: "Ancient Shield", type: "ashd", code: "pad" },
  pae: { name: "Zakarum Shield", type: "ashd", code: "pae" },
  paf: { name: "Vortex Shield", type: "ashd", code: "paf" },
  neb: { name: "Minion Skull", type: "head", code: "neb" },
  neg: { name: "Hellspawn Skull", type: "head", code: "neg" },
  ned: { name: "Overseer Skull", type: "head", code: "ned" },
  nee: { name: "Succubus Skull", type: "head", code: "nee" },
  nef: { name: "Bloodlord Skull", type: "head", code: "nef" },
  elx: { name: "Elixir", type: "elix", code: "elx" },
  hpo: { name: "Healing Potion", type: "hpot", code: "hpo" },
  mpo: { name: "Mana Potion", type: "mpot", code: "mpo" },
  hpf: { name: "Full Healing Potion", type: "hpot", code: "hpf" },
  mpf: { name: "Full Mana Potion", type: "mpot", code: "mpf" },
  vps: { name: "Stamina Potion", type: "spot", code: "vps" },
  yps: { name: "Antidote Potion", type: "apot", code: "yps" },
  rvs: { name: "Rejuvenation Potion", type: "rpot", code: "rvs" },
  rvl: { name: "Full Rejuvenation Potion", type: "rpot", code: "rvl" },
  wms: { name: "Thawing Potion", type: "wpot", code: "wms" },
  tbk: { name: "Tome of Town Portal", type: "book", code: "tbk" },
  ibk: { name: "Tome of Identify", type: "book", code: "ibk" },
  amu: { name: "Amulet", type: "amul", code: "amu" },
  vip: { name: "Amulet of the Viper", type: "amul", code: "vip" },
  rin: { name: "Ring", type: "ring", code: "rin" },
  gld: { name: "Gold", type: "gold", code: "gld" },
  bks: { name: "Scroll of Inifuss", type: "ques", code: "bks" },
  bkd: { name: "Key to the Cairn Stones", type: "ques", code: "bkd" },
  aqv: { name: "Arrows", type: "bowq", code: "aqv" },
  tch: { name: "Torch", type: "torc", code: "tch" },
  cqv: { name: "Bolts", type: "xboq", code: "cqv" },
  tsc: { name: "Scroll of Town Portal", type: "scro", code: "tsc" },
  isc: { name: "Scroll of Identify", type: "scro", code: "isc" },
  hrt: { name: "Heart", type: "body", code: "hrt" },
  brz: { name: "Brain", type: "body", code: "brz" },
  jaw: { name: "Jawbone", type: "body", code: "jaw" },
  eyz: { name: "Eye", type: "body", code: "eyz" },
  hrn: { name: "Horn", type: "body", code: "hrn" },
  tal: { name: "Tail", type: "body", code: "tal" },
  flg: { name: "Flag", type: "body", code: "flg" },
  fng: { name: "Fang", type: "body", code: "fng" },
  qll: { name: "Quill", type: "body", code: "qll" },
  sol: { name: "Soul", type: "body", code: "sol" },
  scz: { name: "Scalp", type: "body", code: "scz" },
  spe: { name: "Spleen", type: "body", code: "spe" },
  key: { name: "Key", type: "key", code: "key" },
  luv: { name: "The Black Tower Key", type: "key", code: "luv" },
  xyz: { name: "Potion of Life", type: "ques", code: "xyz" },
  j34: { name: "A Jade Figurine", type: "ques", code: "j34" },
  g34: { name: "The Golden Bird", type: "ques", code: "g34" },
  bbb: { name: "Lam Esen's Tome", type: "ques", code: "bbb" },
  box: { name: "Horadric Cube", type: "ques", code: "box" },
  tr1: { name: "Horadric Scroll", type: "ques", code: "tr1" },
  mss: { name: "Mephisto's Soulstone", type: "ques", code: "mss" },
  ass: { name: "Book of Skill", type: "ques", code: "ass" },
  qey: { name: "Khalim's Eye", type: "ques", code: "qey" },
  qhr: { name: "Khalim's Heart", type: "ques", code: "qhr" },
  qbr: { name: "Khalim's Brain", type: "ques", code: "qbr" },
  ear: { name: "Ear", type: "play", code: "ear" },
  gcv: { name: "Chipped Amethyst", type: "gema", code: "gcv" },
  gfv: { name: "Flawed Amethyst", type: "gema", code: "gfv" },
  gsv: { name: "Amethyst", type: "gema", code: "gsv" },
  gzv: { name: "Flawless Amethyst", type: "gema", code: "gzv" },
  gpv: { name: "Perfect Amethyst", type: "gema", code: "gpv" },
  gcy: { name: "Chipped Topaz", type: "gemt", code: "gcy" },
  gfy: { name: "Flawed Topaz", type: "gemt", code: "gfy" },
  gsy: { name: "Topaz", type: "gemt", code: "gsy" },
  gly: { name: "Flawless Topaz", type: "gemt", code: "gly" },
  gpy: { name: "Perfect Topaz", type: "gemt", code: "gpy" },
  gcb: { name: "Chipped Sapphire", type: "gems", code: "gcb" },
  gfb: { name: "Flawed Sapphire", type: "gems", code: "gfb" },
  gsb: { name: "Sapphire", type: "gems", code: "gsb" },
  glb: { name: "Flawless Sapphire", type: "gems", code: "glb" },
  gpb: { name: "Perfect Sapphire", type: "gems", code: "gpb" },
  gcg: { name: "Chipped Emerald", type: "geme", code: "gcg" },
  gfg: { name: "Flawed Emerald", type: "geme", code: "gfg" },
  gsg: { name: "Emerald", type: "geme", code: "gsg" },
  glg: { name: "Flawless Emerald", type: "geme", code: "glg" },
  gpg: { name: "Perfect Emerald", type: "geme", code: "gpg" },
  gcr: { name: "Chipped Ruby", type: "gemr", code: "gcr" },
  gfr: { name: "Flawed Ruby", type: "gemr", code: "gfr" },
  gsr: { name: "Ruby", type: "gemr", code: "gsr" },
  glr: { name: "Flawless Ruby", type: "gemr", code: "glr" },
  gpr: { name: "Perfect Ruby", type: "gemr", code: "gpr" },
  gcw: { name: "Chipped Diamond", type: "gemd", code: "gcw" },
  gfw: { name: "Flawed Diamond", type: "gemd", code: "gfw" },
  gsw: { name: "Diamond", type: "gemd", code: "gsw" },
  glw: { name: "Flawless Diamond", type: "gemd", code: "glw" },
  gpw: { name: "Perfect Diamond", type: "gemd", code: "gpw" },
  hp1: { name: "Minor Healing Potion", type: "hpot", code: "hp1" },
  hp2: { name: "Light Healing Potion", type: "hpot", code: "hp2" },
  hp3: { name: "Healing Potion", type: "hpot", code: "hp3" },
  hp4: { name: "Greater Healing Potion", type: "hpot", code: "hp4" },
  hp5: { name: "Super Healing Potion", type: "hpot", code: "hp5" },
  mp1: { name: "Minor Mana Potion", type: "mpot", code: "mp1" },
  mp2: { name: "Light Mana Potion", type: "mpot", code: "mp2" },
  mp3: { name: "Mana Potion", type: "mpot", code: "mp3" },
  mp4: { name: "Greater Mana Potion", type: "mpot", code: "mp4" },
  mp5: { name: "Super Mana Potion", type: "mpot", code: "mp5" },
  skc: { name: "Chipped Skull", type: "gemz", code: "skc" },
  skf: { name: "Flawed Skull", type: "gemz", code: "skf" },
  sku: { name: "Skull", type: "gemz", code: "sku" },
  skl: { name: "Flawless Skull", type: "gemz", code: "skl" },
  skz: { name: "Perfect Skull", type: "gemz", code: "skz" },
  hrb: { name: "Herb", type: "herb", code: "hrb" },
  cm1: { name: "Small Charm", type: "scha", code: "cm1" },
  cm2: { name: "Large Charm", type: "mcha", code: "cm2" },
  cm3: { name: "Grand Charm", type: "lcha", code: "cm3" },
  rps: { name: "Small Red Potion", type: "hpot", code: "rps" },
  rpl: { name: "Large RedPotion", type: "hpot", code: "rpl" },
  bps: { name: "Small Blue Potion", type: "mpot", code: "bps" },
  bpl: { name: "Large Blue Potion", type: "mpot", code: "bpl" },
  r01: { name: "El Rune", type: "rune", code: "r01" },
  r02: { name: "Eld Rune", type: "rune", code: "r02" },
  r03: { name: "Tir Rune", type: "rune", code: "r03" },
  r04: { name: "Nef Rune", type: "rune", code: "r04" },
  r05: { name: "Eth Rune", type: "rune", code: "r05" },
  r06: { name: "Ith Rune", type: "rune", code: "r06" },
  r07: { name: "Tal Rune", type: "rune", code: "r07" },
  r08: { name: "Ral Rune", type: "rune", code: "r08" },
  r09: { name: "Ort Rune", type: "rune", code: "r09" },
  r10: { name: "Thul Rune", type: "rune", code: "r10" },
  r11: { name: "Amn Rune", type: "rune", code: "r11" },
  r12: { name: "Sol Rune", type: "rune", code: "r12" },
  r13: { name: "Shael Rune", type: "rune", code: "r13" },
  r14: { name: "Dol Rune", type: "rune", code: "r14" },
  r15: { name: "Hel Rune", type: "rune", code: "r15" },
  r16: { name: "Io Rune", type: "rune", code: "r16" },
  r17: { name: "Lum Rune", type: "rune", code: "r17" },
  r18: { name: "Ko Rune", type: "rune", code: "r18" },
  r19: { name: "Fal Rune", type: "rune", code: "r19" },
  r20: { name: "Lem Rune", type: "rune", code: "r20" },
  r21: { name: "Pul Rune", type: "rune", code: "r21" },
  r22: { name: "Um Rune", type: "rune", code: "r22" },
  r23: { name: "Mal Rune", type: "rune", code: "r23" },
  r24: { name: "Ist Rune", type: "rune", code: "r24" },
  r25: { name: "Gul Rune", type: "rune", code: "r25" },
  r26: { name: "Vex Rune", type: "rune", code: "r26" },
  r27: { name: "Ohm Rune", type: "rune", code: "r27" },
  r28: { name: "Lo Rune", type: "rune", code: "r28" },
  r29: { name: "Sur Rune", type: "rune", code: "r29" },
  r30: { name: "Ber Rune", type: "rune", code: "r30" },
  r31: { name: "Jah Rune", type: "rune", code: "r31" },
  r32: { name: "Cham Rune", type: "rune", code: "r32" },
  r33: { name: "Zod Rune", type: "rune", code: "r33" },
  jew: { name: "Jewel", type: "jewl", code: "jew" },
  ice: { name: "Malah's Potion", type: "ques", code: "ice" },
  "0sc": { name: "Scroll of Knowledge", type: "scro", code: "0sc" },
  tr2: { name: "Scroll of Resistance", type: "ques", code: "tr2" },
  pk1: { name: "Key of Terror", type: "ques", code: "pk1" },
  pk2: { name: "Key of Hate", type: "ques", code: "pk2" },
  pk3: { name: "Key of Destruction", type: "ques", code: "pk3" },
  dhn: { name: "Diablo's Horn", type: "ques", code: "dhn" },
  bey: { name: "Baal's Eye", type: "ques", code: "bey" },
  mbr: { name: "Mephisto's Brain", type: "ques", code: "mbr" },
  toa: { name: "Token of Absolution", type: "ques", code: "toa" },
  tes: { name: "Twisted Essence of Suffering", type: "ques", code: "tes" },
  ceh: { name: "Charged Essense of Hatred", type: "ques", code: "ceh" },
  bet: { name: "Burning Essence of Terror", type: "ques", code: "bet" },
  fed: { name: "Festering Essence of Destruction", type: "ques", code: "fed" },
  std: { name: "Standard of Heroes", type: "ques", code: "std" },
};
