export type ItemObject = {
  name: string;
  type: string;
  code: string;
  level: number;
};

export type ItemDictType = {
  [key: string]: ItemObject;
};

export const ItemDict: ItemDictType = {
  hax: { name: "Hand Axe", type: "axe", code: "hax", level: 3 },
  axe: { name: "Axe", type: "axe", code: "axe", level: 7 },
  "2ax": { name: "Double Axe", type: "axe", code: "2ax", level: 13 },
  mpi: { name: "Military Pick", type: "axe", code: "mpi", level: 19 },
  wax: { name: "War Axe", type: "axe", code: "wax", level: 25 },
  lax: { name: "Large Axe", type: "axe", code: "lax", level: 6 },
  bax: { name: "Broad Axe", type: "axe", code: "bax", level: 12 },
  btx: { name: "Battle Axe", type: "axe", code: "btx", level: 17 },
  gax: { name: "Great Axe", type: "axe", code: "gax", level: 23 },
  gix: { name: "Giant Axe", type: "axe", code: "gix", level: 27 },
  wnd: { name: "Wand", type: "wand", code: "wnd", level: 2 },
  ywn: { name: "Yew Wand", type: "wand", code: "ywn", level: 12 },
  bwn: { name: "Bone Wand", type: "wand", code: "bwn", level: 18 },
  gwn: { name: "Grim Wand", type: "wand", code: "gwn", level: 26 },
  clb: { name: "Club", type: "club", code: "clb", level: 1 },
  scp: { name: "Scepter", type: "scep", code: "scp", level: 3 },
  gsc: { name: "Grand Scepter", type: "scep", code: "gsc", level: 15 },
  wsp: { name: "War Scepter", type: "scep", code: "wsp", level: 21 },
  spc: { name: "Spiked Club", type: "club", code: "spc", level: 4 },
  mac: { name: "Mace", type: "mace", code: "mac", level: 8 },
  mst: { name: "Morning Star", type: "mace", code: "mst", level: 13 },
  fla: { name: "Flail", type: "mace", code: "fla", level: 19 },
  whm: { name: "War Hammer", type: "hamm", code: "whm", level: 25 },
  mau: { name: "Maul", type: "hamm", code: "mau", level: 21 },
  gma: { name: "Great Maul", type: "hamm", code: "gma", level: 32 },
  ssd: { name: "Short Sword", type: "swor", code: "ssd", level: 1 },
  scm: { name: "Scimitar", type: "swor", code: "scm", level: 5 },
  sbr: { name: "Saber", type: "swor", code: "sbr", level: 8 },
  flc: { name: "Falchion", type: "swor", code: "flc", level: 11 },
  crs: { name: "Crystal Sword", type: "swor", code: "crs", level: 11 },
  bsd: { name: "Broad Sword", type: "swor", code: "bsd", level: 15 },
  lsd: { name: "Long Sword", type: "swor", code: "lsd", level: 20 },
  wsd: { name: "War Sword", type: "swor", code: "wsd", level: 27 },
  "2hs": { name: "Two-Handed Sword", type: "swor", code: "2hs", level: 10 },
  clm: { name: "Claymore", type: "swor", code: "clm", level: 17 },
  gis: { name: "Giant Sword", type: "swor", code: "gis", level: 21 },
  bsw: { name: "Bastard Sword", type: "swor", code: "bsw", level: 24 },
  flb: { name: "Flamberge", type: "swor", code: "flb", level: 27 },
  gsd: { name: "Great Sword", type: "swor", code: "gsd", level: 33 },
  dgr: { name: "Dagger", type: "knif", code: "dgr", level: 3 },
  dir: { name: "Dirk", type: "knif", code: "dir", level: 9 },
  kri: { name: "Kriss", type: "knif", code: "kri", level: 17 },
  bld: { name: "Blade", type: "knif", code: "bld", level: 23 },
  tkf: { name: "Throwing Knife", type: "tkni", code: "tkf", level: 2 },
  tax: { name: "Throwing Axe", type: "taxe", code: "tax", level: 7 },
  bkf: { name: "Balanced Knife", type: "tkni", code: "bkf", level: 13 },
  bal: { name: "Balanced Axe", type: "taxe", code: "bal", level: 16 },
  jav: { name: "Javelin", type: "jave", code: "jav", level: 1 },
  pil: { name: "Pilum", type: "jave", code: "pil", level: 10 },
  ssp: { name: "Short Spear", type: "jave", code: "ssp", level: 15 },
  glv: { name: "Glaive", type: "jave", code: "glv", level: 23 },
  tsp: { name: "Throwing Spear", type: "jave", code: "tsp", level: 29 },
  spr: { name: "Spear", type: "spea", code: "spr", level: 5 },
  tri: { name: "Trident", type: "spea", code: "tri", level: 9 },
  brn: { name: "Brandistock", type: "spea", code: "brn", level: 16 },
  spt: { name: "Spetum", type: "spea", code: "spt", level: 20 },
  pik: { name: "Pike", type: "spea", code: "pik", level: 24 },
  bar: { name: "Bardiche", type: "pole", code: "bar", level: 5 },
  vou: { name: "Voulge", type: "pole", code: "vou", level: 11 },
  scy: { name: "Scythe", type: "pole", code: "scy", level: 15 },
  pax: { name: "Poleaxe", type: "pole", code: "pax", level: 21 },
  hal: { name: "Halberd", type: "pole", code: "hal", level: 29 },
  wsc: { name: "War Scythe", type: "pole", code: "wsc", level: 34 },
  sst: { name: "Short Staff", type: "staf", code: "sst", level: 1 },
  lst: { name: "Long Staff", type: "staf", code: "lst", level: 8 },
  cst: { name: "Gnarled Staff", type: "staf", code: "cst", level: 12 },
  bst: { name: "Battle Staff", type: "staf", code: "bst", level: 17 },
  wst: { name: "War Staff", type: "staf", code: "wst", level: 24 },
  sbw: { name: "Short Bow", type: "bow", code: "sbw", level: 1 },
  hbw: { name: "Hunter's Bow", type: "bow", code: "hbw", level: 5 },
  lbw: { name: "Long Bow", type: "bow", code: "lbw", level: 8 },
  cbw: { name: "Composite Bow", type: "bow", code: "cbw", level: 12 },
  sbb: { name: "Short Battle Bow", type: "bow", code: "sbb", level: 18 },
  lbb: { name: "Long Battle Bow", type: "bow", code: "lbb", level: 23 },
  swb: { name: "Short War Bow", type: "bow", code: "swb", level: 27 },
  lwb: { name: "Long War Bow", type: "bow", code: "lwb", level: 31 },
  lxb: { name: "Light Crossbow", type: "xbow", code: "lxb", level: 6 },
  mxb: { name: "Crossbow", type: "xbow", code: "mxb", level: 15 },
  hxb: { name: "Heavy Crossbow", type: "xbow", code: "hxb", level: 24 },
  rxb: { name: "Repeating Crossbow", type: "xbow", code: "rxb", level: 33 },
  gps: { name: "Rancid Gas Potion", type: "tpot", code: "gps", level: 32 },
  ops: { name: "Oil Potion", type: "tpot", code: "ops", level: 28 },
  gpm: { name: "Choking Gas Potion", type: "tpot", code: "gpm", level: 20 },
  opm: { name: "Exploding Potion", type: "tpot", code: "opm", level: 16 },
  gpl: { name: "Strangling Gas Potion", type: "tpot", code: "gpl", level: 8 },
  opl: { name: "Fulminating Potion", type: "tpot", code: "opl", level: 4 },
  d33: { name: "Decoy Gidbinn", type: "knif", code: "d33", level: 0 },
  g33: { name: "The Gidbinn", type: "knif", code: "g33", level: 0 },
  leg: { name: "Wirt's Leg", type: "club", code: "leg", level: 0 },
  hdm: { name: "HoradricMalus", type: "hamm", code: "hdm", level: 0 },
  hfh: { name: "Hellforge Hammer", type: "hamm", code: "hfh", level: 0 },
  hst: { name: "Horadric Staff", type: "staf", code: "hst", level: 0 },
  msf: { name: "Staff of Kings", type: "staf", code: "msf", level: 0 },
  "9ha": { name: "Hatchet", type: "axe", code: "9ha", level: 31 },
  "9ax": { name: "Cleaver", type: "axe", code: "9ax", level: 34 },
  "92a": { name: "Twin Axe", type: "axe", code: "92a", level: 39 },
  "9mp": { name: "Crowbill", type: "axe", code: "9mp", level: 43 },
  "9wa": { name: "Naga", type: "axe", code: "9wa", level: 48 },
  "9la": { name: "Military Axe", type: "axe", code: "9la", level: 34 },
  "9ba": { name: "Bearded Axe", type: "axe", code: "9ba", level: 38 },
  "9bt": { name: "Tabar", type: "axe", code: "9bt", level: 42 },
  "9ga": { name: "Gothic Axe", type: "axe", code: "9ga", level: 46 },
  "9gi": { name: "Ancient Axe", type: "axe", code: "9gi", level: 51 },
  "9wn": { name: "Burnt Wand", type: "wand", code: "9wn", level: 31 },
  "9yw": { name: "Petrified Wand", type: "wand", code: "9yw", level: 38 },
  "9bw": { name: "Tomb Wand", type: "wand", code: "9bw", level: 43 },
  "9gw": { name: "Grave Wand", type: "wand", code: "9gw", level: 49 },
  "9cl": { name: "Cudgel", type: "club", code: "9cl", level: 30 },
  "9sc": { name: "Rune Scepter", type: "scep", code: "9sc", level: 31 },
  "9qs": { name: "Holy Water Sprinkler", type: "scep", code: "9qs", level: 40 },
  "9ws": { name: "Divine Scepter", type: "scep", code: "9ws", level: 45 },
  "9sp": { name: "Barbed Club", type: "club", code: "9sp", level: 32 },
  "9ma": { name: "Flanged Mace", type: "mace", code: "9ma", level: 35 },
  "9mt": { name: "Jagged Star", type: "mace", code: "9mt", level: 39 },
  "9fl": { name: "Knout", type: "mace", code: "9fl", level: 43 },
  "9wh": { name: "Battle Hammer", type: "hamm", code: "9wh", level: 48 },
  "9m9": { name: "War Club", type: "hamm", code: "9m9", level: 45 },
  "9gm": { name: "Martel de Fer", type: "hamm", code: "9gm", level: 53 },
  "9ss": { name: "Gladius", type: "swor", code: "9ss", level: 30 },
  "9sm": { name: "Cutlass", type: "swor", code: "9sm", level: 43 },
  "9sb": { name: "Shamshir", type: "swor", code: "9sb", level: 35 },
  "9fc": { name: "Tulwar", type: "swor", code: "9fc", level: 37 },
  "9cr": { name: "Dimensional Blade", type: "swor", code: "9cr", level: 37 },
  "9bs": { name: "Battle Sword", type: "swor", code: "9bs", level: 40 },
  "9ls": { name: "Rune Sword", type: "swor", code: "9ls", level: 44 },
  "9wd": { name: "Ancient Sword", type: "swor", code: "9wd", level: 49 },
  "92h": { name: "Espandon", type: "swor", code: "92h", level: 37 },
  "9cm": { name: "Dacian Falx", type: "swor", code: "9cm", level: 42 },
  "9gs": { name: "Tusk Sword", type: "swor", code: "9gs", level: 45 },
  "9b9": { name: "Gothic Sword", type: "swor", code: "9b9", level: 48 },
  "9fb": { name: "Zweihander", type: "swor", code: "9fb", level: 49 },
  "9gd": { name: "Executioner Sword", type: "swor", code: "9gd", level: 54 },
  "9dg": { name: "Poignard", type: "knif", code: "9dg", level: 31 },
  "9di": { name: "Rondel", type: "knif", code: "9di", level: 36 },
  "9kr": { name: "Cinquedeas", type: "knif", code: "9kr", level: 42 },
  "9bl": { name: "Stilleto", type: "knif", code: "9bl", level: 46 },
  "9tk": { name: "Battle Dart", type: "tkni", code: "9tk", level: 31 },
  "9ta": { name: "Francisca", type: "taxe", code: "9ta", level: 34 },
  "9bk": { name: "War Dart", type: "tkni", code: "9bk", level: 39 },
  "9b8": { name: "Hurlbat", type: "taxe", code: "9b8", level: 41 },
  "9ja": { name: "War Javelin", type: "jave", code: "9ja", level: 30 },
  "9pi": { name: "Great Pilum", type: "jave", code: "9pi", level: 37 },
  "9s9": { name: "Simbilan", type: "jave", code: "9s9", level: 40 },
  "9gl": { name: "Spiculum", type: "jave", code: "9gl", level: 46 },
  "9ts": { name: "Harpoon", type: "jave", code: "9ts", level: 51 },
  "9sr": { name: "War Spear", type: "spea", code: "9sr", level: 33 },
  "9tr": { name: "Fuscina", type: "spea", code: "9tr", level: 36 },
  "9br": { name: "War Fork", type: "spea", code: "9br", level: 41 },
  "9st": { name: "Yari", type: "spea", code: "9st", level: 44 },
  "9p9": { name: "Lance", type: "spea", code: "9p9", level: 47 },
  "9b7": { name: "Lochaber Axe", type: "pole", code: "9b7", level: 33 },
  "9vo": { name: "Bill", type: "pole", code: "9vo", level: 37 },
  "9s8": { name: "Battle Scythe", type: "pole", code: "9s8", level: 40 },
  "9pa": { name: "Partizan", type: "pole", code: "9pa", level: 35 },
  "9h9": { name: "Bec-de-Corbin", type: "pole", code: "9h9", level: 51 },
  "9wc": { name: "Grim Scythe", type: "pole", code: "9wc", level: 55 },
  "8ss": { name: "Jo Staff", type: "staf", code: "8ss", level: 30 },
  "8ls": { name: "Quarterstaff", type: "staf", code: "8ls", level: 35 },
  "8cs": { name: "Cedar Staff", type: "staf", code: "8cs", level: 38 },
  "8bs": { name: "Gothic Staff", type: "staf", code: "8bs", level: 42 },
  "8ws": { name: "Rune Staff", type: "staf", code: "8ws", level: 47 },
  "8sb": { name: "Edge Bow", type: "bow", code: "8sb", level: 30 },
  "8hb": { name: "Razor Bow", type: "bow", code: "8hb", level: 33 },
  "8lb": { name: "Cedar Bow", type: "bow", code: "8lb", level: 35 },
  "8cb": { name: "Double Bow", type: "bow", code: "8cb", level: 39 },
  "8s8": { name: "Short Siege Bow", type: "bow", code: "8s8", level: 43 },
  "8l8": { name: "Long Siege Bow", type: "bow", code: "8l8", level: 46 },
  "8sw": { name: "Rune Bow", type: "bow", code: "8sw", level: 49 },
  "8lw": { name: "Gothic Bow", type: "bow", code: "8lw", level: 52 },
  "8lx": { name: "Arbalest", type: "xbow", code: "8lx", level: 34 },
  "8mx": { name: "Siege Crossbow", type: "xbow", code: "8mx", level: 40 },
  "8hx": { name: "Ballista", type: "xbow", code: "8hx", level: 47 },
  "8rx": { name: "Chu-Ko-Nu", type: "xbow", code: "8rx", level: 54 },
  qf1: { name: "Khalim's Flail", type: "mace", code: "qf1", level: 0 },
  qf2: { name: "Khalim's Will", type: "mace", code: "qf2", level: 0 },
  ktr: { name: "Katar", type: "h2h", code: "ktr", level: 1 },
  wrb: { name: "Wrist Blade", type: "h2h", code: "wrb", level: 9 },
  axf: { name: "Hatchet Hands", type: "h2h", code: "axf", level: 12 },
  ces: { name: "Cestus", type: "h2h", code: "ces", level: 15 },
  clw: { name: "Claws", type: "h2h", code: "clw", level: 18 },
  btl: { name: "Blade Talons", type: "h2h", code: "btl", level: 21 },
  skr: { name: "Scissors Katar", type: "h2h", code: "skr", level: 24 },
  "9ar": { name: "Quhab", type: "h2h", code: "9ar", level: 28 },
  "9wb": { name: "Wrist Spike", type: "h2h", code: "9wb", level: 32 },
  "9xf": { name: "Fascia", type: "h2h", code: "9xf", level: 36 },
  "9cs": { name: "Hand Scythe", type: "h2h2", code: "9cs", level: 41 },
  "9lw": { name: "Greater Claws", type: "h2h2", code: "9lw", level: 45 },
  "9tw": { name: "Greater Talons", type: "h2h2", code: "9tw", level: 50 },
  "9qr": { name: "Scissors Quhab", type: "h2h2", code: "9qr", level: 54 },
  "7ar": { name: "Suwayyah", type: "h2h2", code: "7ar", level: 59 },
  "7wb": { name: "Wrist Sword", type: "h2h2", code: "7wb", level: 62 },
  "7xf": { name: "War Fist", type: "h2h2", code: "7xf", level: 68 },
  "7cs": { name: "Battle Cestus", type: "h2h2", code: "7cs", level: 73 },
  "7lw": { name: "Feral Claws", type: "h2h2", code: "7lw", level: 78 },
  "7tw": { name: "Runic Talons", type: "h2h2", code: "7tw", level: 81 },
  "7qr": { name: "Scissors Suwayyah", type: "h2h2", code: "7qr", level: 85 },
  "7ha": { name: "Tomahawk", type: "axe", code: "7ha", level: 54 },
  "7ax": { name: "Small Crescent", type: "axe", code: "7ax", level: 61 },
  "72a": { name: "Ettin Axe", type: "axe", code: "72a", level: 70 },
  "7mp": { name: "War Spike", type: "axe", code: "7mp", level: 79 },
  "7wa": { name: "Berserker Axe", type: "axe", code: "7wa", level: 85 },
  "7la": { name: "Feral Axe", type: "axe", code: "7la", level: 57 },
  "7ba": { name: "Silver-edged Axe", type: "axe", code: "7ba", level: 65 },
  "7bt": { name: "Decapitator", type: "axe", code: "7bt", level: 73 },
  "7ga": { name: "Champion Axe", type: "axe", code: "7ga", level: 82 },
  "7gi": { name: "Glorious Axe", type: "axe", code: "7gi", level: 85 },
  "7wn": { name: "Polished Wand", type: "wand", code: "7wn", level: 55 },
  "7yw": { name: "Ghost Wand", type: "wand", code: "7yw", level: 65 },
  "7bw": { name: "Lich Wand", type: "wand", code: "7bw", level: 75 },
  "7gw": { name: "Unearthed Wand", type: "wand", code: "7gw", level: 86 },
  "7cl": { name: "Truncheon", type: "club", code: "7cl", level: 52 },
  "7sc": { name: "Mighty Scepter", type: "scep", code: "7sc", level: 62 },
  "7qs": { name: "Seraph Rod", type: "scep", code: "7qs", level: 76 },
  "7ws": { name: "Caduceus", type: "scep", code: "7ws", level: 85 },
  "7sp": { name: "Tyrant Club", type: "club", code: "7sp", level: 57 },
  "7ma": { name: "Reinforced Mace", type: "mace", code: "7ma", level: 63 },
  "7mt": { name: "Devil Star", type: "mace", code: "7mt", level: 70 },
  "7fl": { name: "Scourge", type: "mace", code: "7fl", level: 76 },
  "7wh": { name: "Legendary Mallet", type: "hamm", code: "7wh", level: 82 },
  "7m7": { name: "Ogre Maul", type: "hamm", code: "7m7", level: 69 },
  "7gm": { name: "Thunder Maul", type: "hamm", code: "7gm", level: 85 },
  "7ss": { name: "Falcata", type: "swor", code: "7ss", level: 56 },
  "7sm": { name: "Ataghan", type: "swor", code: "7sm", level: 61 },
  "7sb": { name: "Elegant Blade", type: "swor", code: "7sb", level: 63 },
  "7fc": { name: "Hydra Edge", type: "swor", code: "7fc", level: 69 },
  "7cr": { name: "Phase Blade", type: "swor", code: "7cr", level: 73 },
  "7bs": { name: "Conquest Sword", type: "swor", code: "7bs", level: 78 },
  "7ls": { name: "Cryptic Sword", type: "swor", code: "7ls", level: 82 },
  "7wd": { name: "Mythical Sword", type: "swor", code: "7wd", level: 85 },
  "72h": { name: "Legend Sword", type: "swor", code: "72h", level: 59 },
  "7cm": { name: "Highland Blade", type: "swor", code: "7cm", level: 66 },
  "7gs": { name: "Balrog Blade", type: "swor", code: "7gs", level: 71 },
  "7b7": { name: "Champion Sword", type: "swor", code: "7b7", level: 77 },
  "7fb": { name: "Colossal Sword", type: "swor", code: "7fb", level: 80 },
  "7gd": { name: "Colossus Blade", type: "swor", code: "7gd", level: 85 },
  "7dg": { name: "Bone Knife", type: "knif", code: "7dg", level: 58 },
  "7di": { name: "Mithral Point", type: "knif", code: "7di", level: 70 },
  "7kr": { name: "Fanged Knife", type: "knif", code: "7kr", level: 83 },
  "7bl": { name: "Legend Spike", type: "knif", code: "7bl", level: 85 },
  "7tk": { name: "Flying Knife", type: "tkni", code: "7tk", level: 64 },
  "7ta": { name: "Flying Axe", type: "taxe", code: "7ta", level: 56 },
  "7bk": { name: "Winged Knife", type: "tkni", code: "7bk", level: 77 },
  "7b8": { name: "Winged Axe", type: "taxe", code: "7b8", level: 80 },
  "7ja": { name: "Hyperion Javelin", type: "jave", code: "7ja", level: 54 },
  "7pi": { name: "Stygian Pilum", type: "jave", code: "7pi", level: 62 },
  "7s7": { name: "Balrog Spear", type: "jave", code: "7s7", level: 71 },
  "7gl": { name: "Ghost Glaive", type: "jave", code: "7gl", level: 79 },
  "7ts": { name: "Winged Harpoon", type: "jave", code: "7ts", level: 85 },
  "7sr": { name: "Hyperion Spear", type: "spea", code: "7sr", level: 58 },
  "7tr": { name: "Stygian Pike", type: "spea", code: "7tr", level: 66 },
  "7br": { name: "Mancatcher", type: "spea", code: "7br", level: 74 },
  "7st": { name: "Ghost Spear", type: "spea", code: "7st", level: 83 },
  "7p7": { name: "War Pike", type: "spea", code: "7p7", level: 85 },
  "7o7": { name: "Ogre Axe", type: "pole", code: "7o7", level: 60 },
  "7vo": { name: "Colossus Voulge", type: "pole", code: "7vo", level: 64 },
  "7s8": { name: "Thresher", type: "pole", code: "7s8", level: 71 },
  "7pa": { name: "Cryptic Axe", type: "pole", code: "7pa", level: 79 },
  "7h7": { name: "Great Poleaxe", type: "pole", code: "7h7", level: 84 },
  "7wc": { name: "Giant Thresher", type: "pole", code: "7wc", level: 85 },
  "6ss": { name: "Walking Stick", type: "staf", code: "6ss", level: 58 },
  "6ls": { name: "Stalagmite", type: "staf", code: "6ls", level: 66 },
  "6cs": { name: "Elder Staff", type: "staf", code: "6cs", level: 74 },
  "6bs": { name: "Shillelagh", type: "staf", code: "6bs", level: 83 },
  "6ws": { name: "Archon Staff", type: "staf", code: "6ws", level: 85 },
  "6sb": { name: "Spider Bow", type: "bow", code: "6sb", level: 55 },
  "6hb": { name: "Blade Bow", type: "bow", code: "6hb", level: 60 },
  "6lb": { name: "Shadow Bow", type: "bow", code: "6lb", level: 63 },
  "6cb": { name: "Great Bow", type: "bow", code: "6cb", level: 68 },
  "6s7": { name: "Diamond Bow", type: "bow", code: "6s7", level: 72 },
  "6l7": { name: "Crusader Bow", type: "bow", code: "6l7", level: 77 },
  "6sw": { name: "Ward Bow", type: "bow", code: "6sw", level: 80 },
  "6lw": { name: "Hydra Bow", type: "bow", code: "6lw", level: 85 },
  "6lx": { name: "Pellet Bow", type: "xbow", code: "6lx", level: 57 },
  "6mx": { name: "Gorgon Crossbow", type: "xbow", code: "6mx", level: 67 },
  "6hx": { name: "Colossus Crossbow", type: "xbow", code: "6hx", level: 75 },
  "6rx": { name: "Demon Crossbow", type: "xbow", code: "6rx", level: 84 },
  ob1: { name: "Eagle Orb", type: "orb", code: "ob1", level: 1 },
  ob2: { name: "Sacred Globe", type: "orb", code: "ob2", level: 8 },
  ob3: { name: "Smoked Sphere", type: "orb", code: "ob3", level: 12 },
  ob4: { name: "Clasped Orb", type: "orb", code: "ob4", level: 17 },
  ob5: { name: "Jared's Stone", type: "orb", code: "ob5", level: 24 },
  am1: { name: "Stag Bow", type: "abow", code: "am1", level: 18 },
  am2: { name: "Reflex Bow", type: "abow", code: "am2", level: 27 },
  am3: { name: "Maiden Spear", type: "aspe", code: "am3", level: 18 },
  am4: { name: "Maiden Pike", type: "aspe", code: "am4", level: 27 },
  am5: { name: "Maiden Javelin", type: "ajav", code: "am5", level: 23 },
  ob6: { name: "Glowing Orb", type: "orb", code: "ob6", level: 32 },
  ob7: { name: "Crystalline Globe", type: "orb", code: "ob7", level: 37 },
  ob8: { name: "Cloudy Sphere", type: "orb", code: "ob8", level: 41 },
  ob9: { name: "Sparkling Ball", type: "orb", code: "ob9", level: 46 },
  oba: { name: "Swirling Crystal", type: "orb", code: "oba", level: 50 },
  am6: { name: "Ashwood Bow", type: "abow", code: "am6", level: 39 },
  am7: { name: "Ceremonial Bow", type: "abow", code: "am7", level: 47 },
  am8: { name: "Ceremonial Spear", type: "aspe", code: "am8", level: 43 },
  am9: { name: "Ceremonial Pike", type: "aspe", code: "am9", level: 51 },
  ama: { name: "Ceremonial Javelin", type: "ajav", code: "ama", level: 35 },
  obb: { name: "Heavenly Stone", type: "orb", code: "obb", level: 59 },
  obc: { name: "Eldritch Orb", type: "orb", code: "obc", level: 67 },
  obd: { name: "Demon Heart", type: "orb", code: "obd", level: 75 },
  obe: { name: "Vortex Orb", type: "orb", code: "obe", level: 84 },
  obf: { name: "Dimensional Shard", type: "orb", code: "obf", level: 85 },
  amb: { name: "Matriarchal Bow", type: "abow", code: "amb", level: 53 },
  amc: { name: "Grand Matron Bow", type: "abow", code: "amc", level: 78 },
  amd: { name: "Matriarchal Spear", type: "aspe", code: "amd", level: 61 },
  ame: { name: "Matriarchal Pike", type: "aspe", code: "ame", level: 81 },
  amf: { name: "Matriarchal Javelin", type: "ajav", code: "amf", level: 65 },
  cap: { name: "Cap", type: "helm", code: "cap", level: 1 },
  skp: { name: "Skull Cap", type: "helm", code: "skp", level: 5 },
  hlm: { name: "Helm", type: "helm", code: "hlm", level: 11 },
  fhl: { name: "Full Helm", type: "helm", code: "fhl", level: 15 },
  ghm: { name: "Great Helm", type: "helm", code: "ghm", level: 23 },
  crn: { name: "Crown", type: "helm", code: "crn", level: 29 },
  msk: { name: "Mask", type: "helm", code: "msk", level: 19 },
  qui: { name: "Quilted Armor", type: "tors", code: "qui", level: 1 },
  lea: { name: "Leather Armor", type: "tors", code: "lea", level: 3 },
  hla: { name: "Hard Leather Armor", type: "tors", code: "hla", level: 5 },
  stu: { name: "Studded Leather", type: "tors", code: "stu", level: 8 },
  rng: { name: "Ring Mail", type: "tors", code: "rng", level: 11 },
  scl: { name: "Scale Mail", type: "tors", code: "scl", level: 13 },
  chn: { name: "Chain Mail", type: "tors", code: "chn", level: 15 },
  brs: { name: "Breast Plate", type: "tors", code: "brs", level: 18 },
  spl: { name: "Splint Mail", type: "tors", code: "spl", level: 20 },
  plt: { name: "Plate Mail", type: "tors", code: "plt", level: 24 },
  fld: { name: "Field Plate", type: "tors", code: "fld", level: 28 },
  gth: { name: "Gothic Plate", type: "tors", code: "gth", level: 32 },
  ful: { name: "Full Plate Mail", type: "tors", code: "ful", level: 37 },
  aar: { name: "Ancient Armor", type: "tors", code: "aar", level: 40 },
  ltp: { name: "Light Plate", type: "tors", code: "ltp", level: 35 },
  buc: { name: "Buckler", type: "shie", code: "buc", level: 1 },
  sml: { name: "Small Shield", type: "shie", code: "sml", level: 5 },
  lrg: { name: "Large Shield", type: "shie", code: "lrg", level: 11 },
  kit: { name: "Kite Shield", type: "shie", code: "kit", level: 15 },
  tow: { name: "Tower Shield", type: "shie", code: "tow", level: 22 },
  gts: { name: "Gothic Shield", type: "shie", code: "gts", level: 30 },
  lgl: { name: "Leather Gloves", type: "glov", code: "lgl", level: 3 },
  vgl: { name: "Heavy Gloves", type: "glov", code: "vgl", level: 7 },
  mgl: { name: "Chain Gloves", type: "glov", code: "mgl", level: 12 },
  tgl: { name: "Light Gauntlets", type: "glov", code: "tgl", level: 20 },
  hgl: { name: "Gauntlets", type: "glov", code: "hgl", level: 27 },
  lbt: { name: "Boots", type: "boot", code: "lbt", level: 3 },
  vbt: { name: "Heavy Boots", type: "boot", code: "vbt", level: 7 },
  mbt: { name: "Chain Boots", type: "boot", code: "mbt", level: 12 },
  tbt: { name: "Light Plated Boots", type: "boot", code: "tbt", level: 20 },
  hbt: { name: "Greaves", type: "boot", code: "hbt", level: 27 },
  lbl: { name: "Sash", type: "belt", code: "lbl", level: 3 },
  vbl: { name: "Light Belt", type: "belt", code: "vbl", level: 7 },
  mbl: { name: "Belt", type: "belt", code: "mbl", level: 12 },
  tbl: { name: "Heavy Belt", type: "belt", code: "tbl", level: 20 },
  hbl: { name: "Plated Belt", type: "belt", code: "hbl", level: 27 },
  bhm: { name: "Bone Helm", type: "helm", code: "bhm", level: 22 },
  bsh: { name: "Bone Shield", type: "shie", code: "bsh", level: 19 },
  spk: { name: "Spiked Shield", type: "shie", code: "spk", level: 11 },
  xap: { name: "War Hat", type: "helm", code: "xap", level: 34 },
  xkp: { name: "Sallet", type: "helm", code: "xkp", level: 37 },
  xlm: { name: "Casque", type: "helm", code: "xlm", level: 42 },
  xhl: { name: "Basinet", type: "helm", code: "xhl", level: 45 },
  xhm: { name: "Winged Helm", type: "helm", code: "xhm", level: 51 },
  xrn: { name: "Grand Crown", type: "helm", code: "xrn", level: 55 },
  xsk: { name: "Death Mask", type: "helm", code: "xsk", level: 48 },
  xui: { name: "Ghost Armor", type: "tors", code: "xui", level: 34 },
  xea: { name: "Serpentskin Armor", type: "tors", code: "xea", level: 36 },
  xla: { name: "Demonhide Armor", type: "tors", code: "xla", level: 37 },
  xtu: { name: "Trellised Armor", type: "tors", code: "xtu", level: 40 },
  xng: { name: "Linked Mail", type: "tors", code: "xng", level: 42 },
  xcl: { name: "Tigulated Mail", type: "tors", code: "xcl", level: 43 },
  xhn: { name: "Mesh Armor", type: "tors", code: "xhn", level: 45 },
  xrs: { name: "Cuirass", type: "tors", code: "xrs", level: 47 },
  xpl: { name: "Russet Armor", type: "tors", code: "xpl", level: 49 },
  xlt: { name: "Templar Coat", type: "tors", code: "xlt", level: 52 },
  xld: { name: "Sharktooth Armor", type: "tors", code: "xld", level: 55 },
  xth: { name: "Embossed Plate", type: "tors", code: "xth", level: 58 },
  xul: { name: "Chaos Armor", type: "tors", code: "xul", level: 61 },
  xar: { name: "Ornate Armor", type: "tors", code: "xar", level: 64 },
  xtp: { name: "Mage Plate", type: "tors", code: "xtp", level: 60 },
  xuc: { name: "Defender", type: "shie", code: "xuc", level: 34 },
  xml: { name: "Round Shield", type: "shie", code: "xml", level: 37 },
  xrg: { name: "Scutum", type: "shie", code: "xrg", level: 42 },
  xit: { name: "Dragon Shield", type: "shie", code: "xit", level: 45 },
  xow: { name: "Pavise", type: "shie", code: "xow", level: 50 },
  xts: { name: "Ancient Shield", type: "shie", code: "xts", level: 56 },
  xlg: { name: "Demonhide Gloves", type: "glov", code: "xlg", level: 33 },
  xvg: { name: "Sharkskin Gloves", type: "glov", code: "xvg", level: 39 },
  xmg: { name: "Heavy Bracers", type: "glov", code: "xmg", level: 43 },
  xtg: { name: "Battle Gauntlets", type: "glov", code: "xtg", level: 49 },
  xhg: { name: "War Gauntlets", type: "glov", code: "xhg", level: 54 },
  xlb: { name: "Demonhide Boots", type: "boot", code: "xlb", level: 36 },
  xvb: { name: "Sharkskin Boots", type: "boot", code: "xvb", level: 39 },
  xmb: { name: "Mesh Boots", type: "boot", code: "xmb", level: 43 },
  xtb: { name: "Battle Boots", type: "boot", code: "xtb", level: 49 },
  xhb: { name: "War Boots", type: "boot", code: "xhb", level: 54 },
  zlb: { name: "Demonhide Sash", type: "belt", code: "zlb", level: 36 },
  zvb: { name: "Sharkskin Belt", type: "belt", code: "zvb", level: 39 },
  zmb: { name: "Mesh Belt", type: "belt", code: "zmb", level: 43 },
  ztb: { name: "Battle Belt", type: "belt", code: "ztb", level: 49 },
  zhb: { name: "War Belt", type: "belt", code: "zhb", level: 54 },
  xh9: { name: "Grim Helm", type: "helm", code: "xh9", level: 50 },
  xsh: { name: "Grim Shield", type: "shie", code: "xsh", level: 48 },
  xpk: { name: "Barbed Shield", type: "shie", code: "xpk", level: 42 },
  dr1: { name: "Wolf Head", type: "pelt", code: "dr1", level: 4 },
  dr2: { name: "Hawk Helm", type: "pelt", code: "dr2", level: 8 },
  dr3: { name: "Antlers", type: "pelt", code: "dr3", level: 16 },
  dr4: { name: "Falcon Mask", type: "pelt", code: "dr4", level: 20 },
  dr5: { name: "Spirit Mask", type: "pelt", code: "dr5", level: 24 },
  ba1: { name: "Jawbone Cap", type: "phlm", code: "ba1", level: 4 },
  ba2: { name: "Fanged Helm", type: "phlm", code: "ba2", level: 8 },
  ba3: { name: "Horned Helm", type: "phlm", code: "ba3", level: 16 },
  ba4: { name: "Assault Helmet", type: "phlm", code: "ba4", level: 20 },
  ba5: { name: "Avenger Guard", type: "phlm", code: "ba5", level: 24 },
  pa1: { name: "Targe", type: "ashd", code: "pa1", level: 4 },
  pa2: { name: "Rondache", type: "ashd", code: "pa2", level: 8 },
  pa3: { name: "Heraldic Shield", type: "ashd", code: "pa3", level: 16 },
  pa4: { name: "Aerin Shield", type: "ashd", code: "pa4", level: 20 },
  pa5: { name: "Crown Shield", type: "ashd", code: "pa5", level: 24 },
  ne1: { name: "Preserved Head", type: "head", code: "ne1", level: 4 },
  ne2: { name: "Zombie Head", type: "head", code: "ne2", level: 8 },
  ne3: { name: "Unraveller Head", type: "head", code: "ne3", level: 16 },
  ne4: { name: "Gargoyle Head", type: "head", code: "ne4", level: 20 },
  ne5: { name: "Demon Head", type: "head", code: "ne5", level: 24 },
  ci0: { name: "Circlet", type: "circ", code: "ci0", level: 24 },
  ci1: { name: "Coronet", type: "circ", code: "ci1", level: 52 },
  ci2: { name: "Tiara", type: "circ", code: "ci2", level: 70 },
  ci3: { name: "Diadem", type: "circ", code: "ci3", level: 85 },
  uap: { name: "Shako", type: "helm", code: "uap", level: 58 },
  ukp: { name: "Hydraskull", type: "helm", code: "ukp", level: 63 },
  ulm: { name: "Armet", type: "helm", code: "ulm", level: 68 },
  uhl: { name: "Giant Conch", type: "helm", code: "uhl", level: 54 },
  uhm: { name: "Spired Helm", type: "helm", code: "uhm", level: 79 },
  urn: { name: "Corona", type: "helm", code: "urn", level: 85 },
  usk: { name: "Demonhead", type: "helm", code: "usk", level: 74 },
  uui: { name: "Dusk Shroud", type: "tors", code: "uui", level: 65 },
  uea: { name: "Wyrmhide", type: "tors", code: "uea", level: 67 },
  ula: { name: "Scarab Husk", type: "tors", code: "ula", level: 68 },
  utu: { name: "Wire Fleece", type: "tors", code: "utu", level: 70 },
  ung: { name: "Diamond Mail", type: "tors", code: "ung", level: 72 },
  ucl: { name: "Loricated Mail", type: "tors", code: "ucl", level: 73 },
  uhn: { name: "Boneweave", type: "tors", code: "uhn", level: 62 },
  urs: { name: "Great Hauberk", type: "tors", code: "urs", level: 75 },
  upl: { name: "Balrog Skin", type: "tors", code: "upl", level: 76 },
  ult: { name: "Hellforge Plate", type: "tors", code: "ult", level: 78 },
  uld: { name: "Kraken Shell", type: "tors", code: "uld", level: 81 },
  uth: { name: "Lacquered Plate", type: "tors", code: "uth", level: 82 },
  uul: { name: "Shadow Plate", type: "tors", code: "uul", level: 83 },
  uar: { name: "Sacred Armor", type: "tors", code: "uar", level: 85 },
  utp: { name: "Archon Plate", type: "tors", code: "utp", level: 84 },
  uuc: { name: "Heater", type: "shie", code: "uuc", level: 58 },
  uml: { name: "Luna", type: "shie", code: "uml", level: 61 },
  urg: { name: "Hyperion", type: "shie", code: "urg", level: 64 },
  uit: { name: "Monarch", type: "shie", code: "uit", level: 72 },
  uow: { name: "Aegis", type: "shie", code: "uow", level: 79 },
  uts: { name: "Ward", type: "shie", code: "uts", level: 84 },
  ulg: { name: "Bramble Mitts", type: "glov", code: "ulg", level: 57 },
  uvg: { name: "Vampirebone Gloves", type: "glov", code: "uvg", level: 63 },
  umg: { name: "Vambraces", type: "glov", code: "umg", level: 69 },
  utg: { name: "Crusader Gauntlets", type: "glov", code: "utg", level: 76 },
  uhg: { name: "Ogre Gauntlets", type: "glov", code: "uhg", level: 85 },
  ulb: { name: "Wyrmhide Boots", type: "boot", code: "ulb", level: 60 },
  uvb: { name: "Scarabshell Boots", type: "boot", code: "uvb", level: 66 },
  umb: { name: "Boneweave Boots", type: "boot", code: "umb", level: 72 },
  utb: { name: "Mirrored Boots", type: "boot", code: "utb", level: 81 },
  uhb: { name: "Myrmidon Greaves", type: "boot", code: "uhb", level: 85 },
  ulc: { name: "Spiderweb Sash", type: "belt", code: "ulc", level: 61 },
  uvc: { name: "Vampirefang Belt", type: "belt", code: "uvc", level: 68 },
  umc: { name: "Mithril Coil", type: "belt", code: "umc", level: 75 },
  utc: { name: "Troll Belt", type: "belt", code: "utc", level: 82 },
  uhc: { name: "Colossus Girdle", type: "belt", code: "uhc", level: 85 },
  uh9: { name: "Bone Visage", type: "helm", code: "uh9", level: 84 },
  ush: { name: "Troll Nest", type: "shie", code: "ush", level: 76 },
  upk: { name: "Blade Barrier", type: "shie", code: "upk", level: 68 },
  dr6: { name: "Alpha Helm", type: "pelt", code: "dr6", level: 35 },
  dr7: { name: "Griffon Headress", type: "pelt", code: "dr7", level: 40 },
  dr8: { name: "Hunter's Guise", type: "pelt", code: "dr8", level: 46 },
  dr9: { name: "Sacred Feathers", type: "pelt", code: "dr9", level: 50 },
  dra: { name: "Totemic Mask", type: "pelt", code: "dra", level: 55 },
  ba6: { name: "Jawbone Visor", type: "phlm", code: "ba6", level: 33 },
  ba7: { name: "Lion Helm", type: "phlm", code: "ba7", level: 38 },
  ba8: { name: "Rage Mask", type: "phlm", code: "ba8", level: 44 },
  ba9: { name: "Savage Helmet", type: "phlm", code: "ba9", level: 49 },
  baa: { name: "Slayer Guard", type: "phlm", code: "baa", level: 54 },
  pa6: { name: "Akaran Targe", type: "ashd", code: "pa6", level: 35 },
  pa7: { name: "Akaran Rondache", type: "ashd", code: "pa7", level: 40 },
  pa8: { name: "Protector Shield", type: "ashd", code: "pa8", level: 46 },
  pa9: { name: "Gilded Shield", type: "ashd", code: "pa9", level: 51 },
  paa: { name: "Royal Shield", type: "ashd", code: "paa", level: 55 },
  ne6: { name: "Mummified Trophy", type: "head", code: "ne6", level: 33 },
  ne7: { name: "Fetish Trophy", type: "head", code: "ne7", level: 39 },
  ne8: { name: "Sexton Trophy", type: "head", code: "ne8", level: 45 },
  ne9: { name: "Cantor Trophy", type: "head", code: "ne9", level: 49 },
  nea: { name: "Heirophant Trophy", type: "head", code: "nea", level: 54 },
  drb: { name: "Blood Spirit", type: "pelt", code: "drb", level: 62 },
  drc: { name: "Sun Spirit", type: "pelt", code: "drc", level: 69 },
  drd: { name: "Earth Spirit", type: "pelt", code: "drd", level: 76 },
  dre: { name: "Sky Spirit", type: "pelt", code: "dre", level: 83 },
  drf: { name: "Dream Spirit", type: "pelt", code: "drf", level: 85 },
  bab: { name: "Carnage Helm", type: "phlm", code: "bab", level: 60 },
  bac: { name: "Fury Visor", type: "phlm", code: "bac", level: 66 },
  bad: { name: "Destroyer Helm", type: "phlm", code: "bad", level: 73 },
  bae: { name: "Conqueror Crown", type: "phlm", code: "bae", level: 80 },
  baf: { name: "Guardian Crown", type: "phlm", code: "baf", level: 85 },
  pab: { name: "Sacred Targe", type: "ashd", code: "pab", level: 63 },
  pac: { name: "Sacred Rondache", type: "ashd", code: "pac", level: 70 },
  pad: { name: "Ancient Shield", type: "ashd", code: "pad", level: 74 },
  pae: { name: "Zakarum Shield", type: "ashd", code: "pae", level: 82 },
  paf: { name: "Vortex Shield", type: "ashd", code: "paf", level: 85 },
  neb: { name: "Minion Skull", type: "head", code: "neb", level: 59 },
  neg: { name: "Hellspawn Skull", type: "head", code: "neg", level: 67 },
  ned: { name: "Overseer Skull", type: "head", code: "ned", level: 66 },
  nee: { name: "Succubus Skull", type: "head", code: "nee", level: 81 },
  nef: { name: "Bloodlord Skull", type: "head", code: "nef", level: 85 },
  elx: { name: "Elixir", type: "elix", code: "elx", level: 21 },
  hpo: { name: "Healing Potion", type: "hpot", code: "hpo", level: 0 },
  mpo: { name: "Mana Potion", type: "mpot", code: "mpo", level: 0 },
  hpf: { name: "Full Healing Potion", type: "hpot", code: "hpf", level: 0 },
  mpf: { name: "Full Mana Potion", type: "mpot", code: "mpf", level: 0 },
  vps: { name: "Stamina Potion", type: "spot", code: "vps", level: 0 },
  yps: { name: "Antidote Potion", type: "apot", code: "yps", level: 0 },
  rvs: { name: "Rejuvenation Potion", type: "rpot", code: "rvs", level: 0 },
  rvl: {
    name: "Full Rejuvenation Potion",
    type: "rpot",
    code: "rvl",
    level: 0,
  },
  wms: { name: "Thawing Potion", type: "wpot", code: "wms", level: 0 },
  tbk: { name: "Tome of Town Portal", type: "book", code: "tbk", level: 0 },
  ibk: { name: "Tome of Identify", type: "book", code: "ibk", level: 0 },
  amu: { name: "Amulet", type: "amul", code: "amu", level: 1 },
  vip: { name: "Amulet of the Viper", type: "amul", code: "vip", level: 15 },
  rin: { name: "Ring", type: "ring", code: "rin", level: 1 },
  gld: { name: "Gold", type: "gold", code: "gld", level: 0 },
  bks: { name: "Scroll of Inifuss", type: "ques", code: "bks", level: 0 },
  bkd: { name: "Key to the Cairn Stones", type: "ques", code: "bkd", level: 0 },
  aqv: { name: "Arrows", type: "bowq", code: "aqv", level: 0 },
  tch: { name: "Torch", type: "torc", code: "tch", level: 0 },
  cqv: { name: "Bolts", type: "xboq", code: "cqv", level: 0 },
  tsc: { name: "Scroll of Town Portal", type: "scro", code: "tsc", level: 0 },
  isc: { name: "Scroll of Identify", type: "scro", code: "isc", level: 0 },
  hrt: { name: "Heart", type: "body", code: "hrt", level: 0 },
  brz: { name: "Brain", type: "body", code: "brz", level: 0 },
  jaw: { name: "Jawbone", type: "body", code: "jaw", level: 0 },
  eyz: { name: "Eye", type: "body", code: "eyz", level: 0 },
  hrn: { name: "Horn", type: "body", code: "hrn", level: 0 },
  tal: { name: "Tail", type: "body", code: "tal", level: 0 },
  flg: { name: "Flag", type: "body", code: "flg", level: 0 },
  fng: { name: "Fang", type: "body", code: "fng", level: 0 },
  qll: { name: "Quill", type: "body", code: "qll", level: 0 },
  sol: { name: "Soul", type: "body", code: "sol", level: 0 },
  scz: { name: "Scalp", type: "body", code: "scz", level: 0 },
  spe: { name: "Spleen", type: "body", code: "spe", level: 0 },
  key: { name: "Key", type: "key", code: "key", level: 0 },
  luv: { name: "The Black Tower Key", type: "key", code: "luv", level: 0 },
  xyz: { name: "Potion of Life", type: "ques", code: "xyz", level: 0 },
  j34: { name: "A Jade Figurine", type: "ques", code: "j34", level: 0 },
  g34: { name: "The Golden Bird", type: "ques", code: "g34", level: 0 },
  bbb: { name: "Lam Esen's Tome", type: "ques", code: "bbb", level: 0 },
  box: { name: "Horadric Cube", type: "ques", code: "box", level: 0 },
  tr1: { name: "Horadric Scroll", type: "ques", code: "tr1", level: 0 },
  mss: { name: "Mephisto's Soulstone", type: "ques", code: "mss", level: 0 },
  ass: { name: "Book of Skill", type: "ques", code: "ass", level: 0 },
  qey: { name: "Khalim's Eye", type: "ques", code: "qey", level: 0 },
  qhr: { name: "Khalim's Heart", type: "ques", code: "qhr", level: 0 },
  qbr: { name: "Khalim's Brain", type: "ques", code: "qbr", level: 0 },
  ear: { name: "Ear", type: "play", code: "ear", level: 0 },
  gcv: { name: "Chipped Amethyst", type: "gema", code: "gcv", level: 0 },
  gfv: { name: "Flawed Amethyst", type: "gema", code: "gfv", level: 0 },
  gsv: { name: "Amethyst", type: "gema", code: "gsv", level: 0 },
  gzv: { name: "Flawless Amethyst", type: "gema", code: "gzv", level: 0 },
  gpv: { name: "Perfect Amethyst", type: "gema", code: "gpv", level: 0 },
  gcy: { name: "Chipped Topaz", type: "gemt", code: "gcy", level: 0 },
  gfy: { name: "Flawed Topaz", type: "gemt", code: "gfy", level: 0 },
  gsy: { name: "Topaz", type: "gemt", code: "gsy", level: 0 },
  gly: { name: "Flawless Topaz", type: "gemt", code: "gly", level: 0 },
  gpy: { name: "Perfect Topaz", type: "gemt", code: "gpy", level: 0 },
  gcb: { name: "Chipped Sapphire", type: "gems", code: "gcb", level: 0 },
  gfb: { name: "Flawed Sapphire", type: "gems", code: "gfb", level: 0 },
  gsb: { name: "Sapphire", type: "gems", code: "gsb", level: 0 },
  glb: { name: "Flawless Sapphire", type: "gems", code: "glb", level: 0 },
  gpb: { name: "Perfect Sapphire", type: "gems", code: "gpb", level: 0 },
  gcg: { name: "Chipped Emerald", type: "geme", code: "gcg", level: 0 },
  gfg: { name: "Flawed Emerald", type: "geme", code: "gfg", level: 0 },
  gsg: { name: "Emerald", type: "geme", code: "gsg", level: 0 },
  glg: { name: "Flawless Emerald", type: "geme", code: "glg", level: 0 },
  gpg: { name: "Perfect Emerald", type: "geme", code: "gpg", level: 0 },
  gcr: { name: "Chipped Ruby", type: "gemr", code: "gcr", level: 0 },
  gfr: { name: "Flawed Ruby", type: "gemr", code: "gfr", level: 0 },
  gsr: { name: "Ruby", type: "gemr", code: "gsr", level: 0 },
  glr: { name: "Flawless Ruby", type: "gemr", code: "glr", level: 0 },
  gpr: { name: "Perfect Ruby", type: "gemr", code: "gpr", level: 0 },
  gcw: { name: "Chipped Diamond", type: "gemd", code: "gcw", level: 0 },
  gfw: { name: "Flawed Diamond", type: "gemd", code: "gfw", level: 0 },
  gsw: { name: "Diamond", type: "gemd", code: "gsw", level: 0 },
  glw: { name: "Flawless Diamond", type: "gemd", code: "glw", level: 0 },
  gpw: { name: "Perfect Diamond", type: "gemd", code: "gpw", level: 0 },
  hp1: { name: "Minor Healing Potion", type: "hpot", code: "hp1", level: 0 },
  hp2: { name: "Light Healing Potion", type: "hpot", code: "hp2", level: 0 },
  hp3: { name: "Healing Potion", type: "hpot", code: "hp3", level: 0 },
  hp4: { name: "Greater Healing Potion", type: "hpot", code: "hp4", level: 0 },
  hp5: { name: "Super Healing Potion", type: "hpot", code: "hp5", level: 0 },
  mp1: { name: "Minor Mana Potion", type: "mpot", code: "mp1", level: 0 },
  mp2: { name: "Light Mana Potion", type: "mpot", code: "mp2", level: 0 },
  mp3: { name: "Mana Potion", type: "mpot", code: "mp3", level: 0 },
  mp4: { name: "Greater Mana Potion", type: "mpot", code: "mp4", level: 0 },
  mp5: { name: "Super Mana Potion", type: "mpot", code: "mp5", level: 0 },
  skc: { name: "Chipped Skull", type: "gemz", code: "skc", level: 0 },
  skf: { name: "Flawed Skull", type: "gemz", code: "skf", level: 0 },
  sku: { name: "Skull", type: "gemz", code: "sku", level: 0 },
  skl: { name: "Flawless Skull", type: "gemz", code: "skl", level: 0 },
  skz: { name: "Perfect Skull", type: "gemz", code: "skz", level: 0 },
  hrb: { name: "Herb", type: "herb", code: "hrb", level: 3 },
  cm1: { name: "Small Charm", type: "scha", code: "cm1", level: 28 },
  cm2: { name: "Large Charm", type: "mcha", code: "cm2", level: 14 },
  cm3: { name: "Grand Charm", type: "lcha", code: "cm3", level: 1 },
  rps: { name: "Small Red Potion", type: "hpot", code: "rps", level: 0 },
  rpl: { name: "Large Red Potion", type: "hpot", code: "rpl", level: 0 },
  bps: { name: "Small Blue Potion", type: "mpot", code: "bps", level: 0 },
  bpl: { name: "Large Blue Potion", type: "mpot", code: "bpl", level: 0 },
  r01: { name: "El Rune", type: "rune", code: "r01", level: 11 },
  r02: { name: "Eld Rune", type: "rune", code: "r02", level: 11 },
  r03: { name: "Tir Rune", type: "rune", code: "r03", level: 13 },
  r04: { name: "Nef Rune", type: "rune", code: "r04", level: 13 },
  r05: { name: "Eth Rune", type: "rune", code: "r05", level: 15 },
  r06: { name: "Ith Rune", type: "rune", code: "r06", level: 15 },
  r07: { name: "Tal Rune", type: "rune", code: "r07", level: 17 },
  r08: { name: "Ral Rune", type: "rune", code: "r08", level: 19 },
  r09: { name: "Ort Rune", type: "rune", code: "r09", level: 21 },
  r10: { name: "Thul Rune", type: "rune", code: "r10", level: 23 },
  r11: { name: "Amn Rune", type: "rune", code: "r11", level: 25 },
  r12: { name: "Sol Rune", type: "rune", code: "r12", level: 27 },
  r13: { name: "Shael Rune", type: "rune", code: "r13", level: 29 },
  r14: { name: "Dol Rune", type: "rune", code: "r14", level: 31 },
  r15: { name: "Hel Rune", type: "rune", code: "r15", level: 33 },
  r16: { name: "Io Rune", type: "rune", code: "r16", level: 35 },
  r17: { name: "Lum Rune", type: "rune", code: "r17", level: 37 },
  r18: { name: "Ko Rune", type: "rune", code: "r18", level: 39 },
  r19: { name: "Fal Rune", type: "rune", code: "r19", level: 41 },
  r20: { name: "Lem Rune", type: "rune", code: "r20", level: 43 },
  r21: { name: "Pul Rune", type: "rune", code: "r21", level: 45 },
  r22: { name: "Um Rune", type: "rune", code: "r22", level: 47 },
  r23: { name: "Mal Rune", type: "rune", code: "r23", level: 49 },
  r24: { name: "Ist Rune", type: "rune", code: "r24", level: 51 },
  r25: { name: "Gul Rune", type: "rune", code: "r25", level: 53 },
  r26: { name: "Vex Rune", type: "rune", code: "r26", level: 55 },
  r27: { name: "Ohm Rune", type: "rune", code: "r27", level: 57 },
  r28: { name: "Lo Rune", type: "rune", code: "r28", level: 59 },
  r29: { name: "Sur Rune", type: "rune", code: "r29", level: 61 },
  r30: { name: "Ber Rune", type: "rune", code: "r30", level: 63 },
  r31: { name: "Jah Rune", type: "rune", code: "r31", level: 65 },
  r32: { name: "Cham Rune", type: "rune", code: "r32", level: 67 },
  r33: { name: "Zod Rune", type: "rune", code: "r33", level: 69 },
  jew: { name: "Jewel", type: "jewl", code: "jew", level: 1 },
  ice: { name: "Malah's Potion", type: "ques", code: "ice", level: 0 },
  "0sc": { name: "Scroll of Knowledge", type: "scro", code: "0sc", level: 0 },
  tr2: { name: "Scroll of Resistance", type: "ques", code: "tr2", level: 0 },
  pk1: { name: "Key of Terror", type: "ques", code: "pk1", level: 0 },
  pk2: { name: "Key of Hate", type: "ques", code: "pk2", level: 0 },
  pk3: { name: "Key of Destruction", type: "ques", code: "pk3", level: 0 },
  dhn: { name: "Diablo's Horn", type: "ques", code: "dhn", level: 0 },
  bey: { name: "Baal's Eye", type: "ques", code: "bey", level: 0 },
  mbr: { name: "Mephisto's Brain", type: "ques", code: "mbr", level: 0 },
  toa: { name: "Token of Absolution", type: "ques", code: "toa", level: 0 },
  tes: {
    name: "Twisted Essence of Suffering",
    type: "ques",
    code: "tes",
    level: 0,
  },
  ceh: {
    name: "Charged Essense of Hatred",
    type: "ques",
    code: "ceh",
    level: 0,
  },
  bet: {
    name: "Burning Essence of Terror",
    type: "ques",
    code: "bet",
    level: 0,
  },
  fed: {
    name: "Festering Essence of Destruction",
    type: "ques",
    code: "fed",
    level: 0,
  },
  std: { name: "Standard of Heroes", type: "ques", code: "std", level: 90 },
};
