export type WeaponArmorDictEntryType = {
  name: string;
  code: string;
  level: number;
  tier: 0 | 1 | 2;
};

export type WeaponArmorDictType = {
  [key: string]: WeaponArmorDictEntryType;
};

export const WeaponsDict: WeaponArmorDictType = {
  "2ax": { name: "Double Axe", code: "2ax", level: 13, tier: 0 },
  "2hs": { name: "Two-Handed Sword", code: "2hs", level: 10, tier: 0 },
  "6bs": { name: "Shillelagh", code: "6bs", level: 83, tier: 2 },
  "6cb": { name: "Great Bow", code: "6cb", level: 68, tier: 2 },
  "6cs": { name: "Elder Staff", code: "6cs", level: 74, tier: 2 },
  "6hb": { name: "Blade Bow", code: "6hb", level: 60, tier: 2 },
  "6hx": { name: "Colossus Crossbow", code: "6hx", level: 75, tier: 2 },
  "6l7": { name: "Crusader Bow", code: "6l7", level: 77, tier: 2 },
  "6lb": { name: "Shadow Bow", code: "6lb", level: 63, tier: 2 },
  "6ls": { name: "Stalagmite", code: "6ls", level: 66, tier: 2 },
  "6lw": { name: "Hydra Bow", code: "6lw", level: 85, tier: 2 },
  "6lx": { name: "Pellet Bow", code: "6lx", level: 57, tier: 2 },
  "6mx": { name: "Gorgon Crossbow", code: "6mx", level: 67, tier: 2 },
  "6rx": { name: "Demon Crossbow", code: "6rx", level: 84, tier: 2 },
  "6s7": { name: "Diamond Bow", code: "6s7", level: 72, tier: 2 },
  "6sb": { name: "Spider Bow", code: "6sb", level: 55, tier: 2 },
  "6ss": { name: "Walking Stick", code: "6ss", level: 58, tier: 2 },
  "6sw": { name: "Ward Bow", code: "6sw", level: 80, tier: 2 },
  "6ws": { name: "Archon Staff", code: "6ws", level: 85, tier: 2 },
  "72a": { name: "Ettin Axe", code: "72a", level: 70, tier: 2 },
  "72h": { name: "Legend Sword", code: "72h", level: 59, tier: 2 },
  "7ar": { name: "Suwayyah", code: "7ar", level: 59, tier: 2 },
  "7ax": { name: "Small Crescent", code: "7ax", level: 61, tier: 2 },
  "7b7": { name: "Champion Sword", code: "7b7", level: 77, tier: 2 },
  "7b8": { name: "Winged Axe", code: "7b8", level: 80, tier: 2 },
  "7ba": { name: "Silver-edged Axe", code: "7ba", level: 65, tier: 2 },
  "7bk": { name: "Winged Knife", code: "7bk", level: 77, tier: 2 },
  "7bl": { name: "Legend Spike", code: "7bl", level: 85, tier: 2 },
  "7br": { name: "Mancatcher", code: "7br", level: 74, tier: 2 },
  "7bs": { name: "Conquest Sword", code: "7bs", level: 78, tier: 2 },
  "7bt": { name: "Decapitator", code: "7bt", level: 73, tier: 2 },
  "7bw": { name: "Lich Wand", code: "7bw", level: 75, tier: 2 },
  "7cl": { name: "Truncheon", code: "7cl", level: 52, tier: 2 },
  "7cm": { name: "Highland Blade", code: "7cm", level: 66, tier: 2 },
  "7cr": { name: "Phase Blade", code: "7cr", level: 73, tier: 2 },
  "7cs": { name: "Battle Cestus", code: "7cs", level: 73, tier: 2 },
  "7dg": { name: "Bone Knife", code: "7dg", level: 58, tier: 2 },
  "7di": { name: "Mithral Point", code: "7di", level: 70, tier: 2 },
  "7fb": { name: "Colossal Sword", code: "7fb", level: 80, tier: 2 },
  "7fc": { name: "Hydra Edge", code: "7fc", level: 69, tier: 2 },
  "7fl": { name: "Scourge", code: "7fl", level: 76, tier: 2 },
  "7ga": { name: "Champion Axe", code: "7ga", level: 82, tier: 2 },
  "7gd": { name: "Colossus Blade", code: "7gd", level: 85, tier: 2 },
  "7gi": { name: "Glorious Axe", code: "7gi", level: 85, tier: 2 },
  "7gl": { name: "Ghost Glaive", code: "7gl", level: 79, tier: 2 },
  "7gm": { name: "Thunder Maul", code: "7gm", level: 85, tier: 2 },
  "7gs": { name: "BalrogBlade", code: "7gs", level: 71, tier: 2 },
  "7gw": { name: "Unearthed Wand", code: "7gw", level: 86, tier: 2 },
  "7h7": { name: "Great Poleaxe", code: "7h7", level: 84, tier: 2 },
  "7ha": { name: "Tomahawk", code: "7ha", level: 54, tier: 2 },
  "7ja": { name: "Hyperion Javelin", code: "7ja", level: 54, tier: 2 },
  "7kr": { name: "Fanged Knife", code: "7kr", level: 83, tier: 2 },
  "7la": { name: "Feral Axe", code: "7la", level: 57, tier: 2 },
  "7ls": { name: "Cryptic Sword", code: "7ls", level: 82, tier: 2 },
  "7lw": { name: "Feral Claws", code: "7lw", level: 78, tier: 2 },
  "7m7": { name: "Ogre Maul", code: "7m7", level: 69, tier: 2 },
  "7ma": { name: "Reinforced Mace", code: "7ma", level: 63, tier: 2 },
  "7mp": { name: "War Spike", code: "7mp", level: 79, tier: 2 },
  "7mt": { name: "Devil Star", code: "7mt", level: 70, tier: 2 },
  "7o7": { name: "Ogre Axe", code: "7o7", level: 60, tier: 2 },
  "7p7": { name: "War Pike", code: "7p7", level: 85, tier: 2 },
  "7pa": { name: "Cryptic Axe", code: "7pa", level: 79, tier: 2 },
  "7pi": { name: "Stygian Pilum", code: "7pi", level: 62, tier: 2 },
  "7qr": { name: "Scissors Suwayyah", code: "7qr", level: 85, tier: 2 },
  "7qs": { name: "Seraph Rod", code: "7qs", level: 76, tier: 2 },
  "7s7": { name: "Balrog Spear", code: "7s7", level: 71, tier: 2 },
  "7s8": { name: "Thresher", code: "7s8", level: 71, tier: 2 },
  "7sb": { name: "Elegant Blade", code: "7sb", level: 63, tier: 2 },
  "7sc": { name: "Mighty Scepter", code: "7sc", level: 62, tier: 2 },
  "7sm": { name: "Ataghan", code: "7sm", level: 61, tier: 2 },
  "7sp": { name: "Tyrant Club", code: "7sp", level: 57, tier: 2 },
  "7sr": { name: "Hyperion Spear", code: "7sr", level: 58, tier: 2 },
  "7ss": { name: "Falcata", code: "7ss", level: 56, tier: 2 },
  "7st": { name: "Ghost Spear", code: "7st", level: 83, tier: 2 },
  "7ta": { name: "Flying Axe", code: "7ta", level: 56, tier: 2 },
  "7tk": { name: "Flying Knife", code: "7tk", level: 64, tier: 2 },
  "7tr": { name: "Stygian Pike", code: "7tr", level: 66, tier: 2 },
  "7ts": { name: "Winged Harpoon", code: "7ts", level: 85, tier: 2 },
  "7tw": { name: "Runic Talons", code: "7tw", level: 81, tier: 2 },
  "7vo": { name: "Colossus Voulge", code: "7vo", level: 64, tier: 2 },
  "7wa": { name: "Berserker Axe", code: "7wa", level: 85, tier: 2 },
  "7wb": { name: "Wrist Sword", code: "7wb", level: 62, tier: 2 },
  "7wc": { name: "Giant Thresher", code: "7wc", level: 85, tier: 2 },
  "7wd": { name: "Mythical Sword", code: "7wd", level: 85, tier: 2 },
  "7wh": { name: "Legendary Mallet", code: "7wh", level: 82, tier: 2 },
  "7wn": { name: "Polished Wand", code: "7wn", level: 55, tier: 2 },
  "7ws": { name: "Caduceus", code: "7ws", level: 85, tier: 2 },
  "7xf": { name: "War Fist", code: "7xf", level: 68, tier: 2 },
  "7yw": { name: "Ghost Wand", code: "7yw", level: 65, tier: 2 },
  "8bs": { name: "Gothic Staff", code: "8bs", level: 42, tier: 1 },
  "8cb": { name: "Double Bow", code: "8cb", level: 39, tier: 1 },
  "8cs": { name: "Cedar Staff", code: "8cs", level: 38, tier: 1 },
  "8hb": { name: "Razor Bow", code: "8hb", level: 33, tier: 1 },
  "8hx": { name: "Ballista", code: "8hx", level: 47, tier: 1 },
  "8l8": {
    name: "Long Siege Bow",
    code: "8l8",
    level: 46,
    tier: 1,
  },
  "8lb": { name: "Cedar Bow", code: "8lb", level: 35, tier: 1 },
  "8ls": { name: "Quarterstaff", code: "8ls", level: 35, tier: 1 },
  "8lw": { name: "Gothic Bow", code: "8lw", level: 52, tier: 1 },
  "8lx": { name: "Arbalest", code: "8lx", level: 34, tier: 1 },
  "8mx": {
    name: "Siege Crossbow",
    code: "8mx",
    level: 40,
    tier: 1,
  },
  "8rx": { name: "Chu-Ko-Nu", code: "8rx", level: 54, tier: 1 },
  "8s8": {
    name: "Short Siege Bow",
    code: "8s8",
    level: 43,
    tier: 1,
  },
  "8sb": { name: "Edge Bow", code: "8sb", level: 30, tier: 1 },
  "8ss": { name: "Jo Staff", code: "8ss", level: 30, tier: 1 },
  "8sw": { name: "Rune Bow", code: "8sw", level: 49, tier: 1 },
  "8ws": { name: "Rune Staff", code: "8ws", level: 47, tier: 1 },
  "92a": { name: "Twin Axe", code: "92a", level: 39, tier: 1 },
  "92h": { name: "Espandon", code: "92h", level: 37, tier: 1 },
  "9ar": { name: "Quhab", code: "9ar", level: 28, tier: 1 },
  "9ax": { name: "Cleaver", code: "9ax", level: 34, tier: 1 },
  "9b7": { name: "Lochaber Axe", code: "9b7", level: 33, tier: 1 },
  "9b8": { name: "Hurlbat", code: "9b8", level: 41, tier: 1 },
  "9b9": { name: "Gothic Sword", code: "9b9", level: 48, tier: 1 },
  "9ba": { name: "Bearded Axe", code: "9ba", level: 38, tier: 1 },
  "9bk": { name: "War Dart", code: "9bk", level: 39, tier: 1 },
  "9bl": { name: "Stilleto", code: "9bl", level: 46, tier: 1 },
  "9br": { name: "War Fork", code: "9br", level: 41, tier: 1 },
  "9bs": { name: "Battle Sword", code: "9bs", level: 40, tier: 1 },
  "9bt": { name: "Tabar", code: "9bt", level: 42, tier: 1 },
  "9bw": { name: "Tomb Wand", code: "9bw", level: 43, tier: 1 },
  "9cl": { name: "Cudgel", code: "9cl", level: 30, tier: 1 },
  "9cm": { name: "Dacian Falx", code: "9cm", level: 42, tier: 1 },
  "9cr": {
    name: "DimensionalBlade",
    code: "9cr",
    level: 37,
    tier: 1,
  },
  "9cs": { name: "Hand Scythe", code: "9cs", level: 41, tier: 1 },
  "9dg": { name: "Poignard", code: "9dg", level: 31, tier: 1 },
  "9di": { name: "Rondel", code: "9di", level: 36, tier: 1 },
  "9fb": { name: "Zweihander", code: "9fb", level: 49, tier: 1 },
  "9fc": { name: "Tulwar", code: "9fc", level: 37, tier: 1 },
  "9fl": { name: "Knout", code: "9fl", level: 43, tier: 1 },
  "9ga": { name: "Gothic Axe", code: "9ga", level: 46, tier: 1 },
  "9gd": {
    name: "Executioner Sword",
    code: "9gd",
    level: 54,
    tier: 1,
  },
  "9gi": { name: "Ancient Axe", code: "9gi", level: 51, tier: 1 },
  "9gl": { name: "Spiculum", code: "9gl", level: 46, tier: 1 },
  "9gm": { name: "Martel de Fer", code: "9gm", level: 53, tier: 1 },
  "9gs": { name: "Tusk Sword", code: "9gs", level: 45, tier: 1 },
  "9gw": { name: "Grave Wand", code: "9gw", level: 49, tier: 1 },
  "9h9": { name: "Bec-de-Corbin", code: "9h9", level: 51, tier: 1 },
  "9ha": { name: "Hatchet", code: "9ha", level: 31, tier: 1 },
  "9ja": { name: "War Javelin", code: "9ja", level: 30, tier: 1 },
  "9kr": { name: "Cinquedeas", code: "9kr", level: 42, tier: 1 },
  "9la": { name: "Military Axe", code: "9la", level: 34, tier: 1 },
  "9ls": { name: "Rune Sword", code: "9ls", level: 44, tier: 1 },
  "9lw": { name: "Greater Claws", code: "9lw", level: 45, tier: 1 },
  "9m9": { name: "War Club", code: "9m9", level: 45, tier: 1 },
  "9ma": { name: "Flanged Mace", code: "9ma", level: 35, tier: 1 },
  "9mp": { name: "Crowbill", code: "9mp", level: 43, tier: 1 },
  "9mt": { name: "Jagged Star", code: "9mt", level: 39, tier: 1 },
  "9p9": { name: "Lance", code: "9p9", level: 47, tier: 1 },
  "9pa": { name: "Partizan", code: "9pa", level: 35, tier: 1 },
  "9pi": { name: "Great Pilum", code: "9pi", level: 37, tier: 1 },
  "9qr": {
    name: "Scissors Quhab",
    code: "9qr",
    level: 54,
    tier: 1,
  },
  "9qs": {
    name: "Holy Water Sprinkler",
    code: "9qs",
    level: 40,
    tier: 1,
  },
  "9s8": { name: "Battle Scythe", code: "9s8", level: 40, tier: 1 },
  "9s9": { name: "Simbilan", code: "9s9", level: 40, tier: 1 },
  "9sb": { name: "Shamshir", code: "9sb", level: 35, tier: 1 },
  "9sc": { name: "Rune Scepter", code: "9sc", level: 31, tier: 1 },
  "9sm": { name: "Cutlass", code: "9sm", level: 43, tier: 1 },
  "9sp": { name: "Barbed Club", code: "9sp", level: 32, tier: 1 },
  "9sr": { name: "War Spear", code: "9sr", level: 33, tier: 1 },
  "9ss": { name: "Gladius", code: "9ss", level: 30, tier: 1 },
  "9st": { name: "Yari", code: "9st", level: 44, tier: 1 },
  "9ta": { name: "Francisca", code: "9ta", level: 34, tier: 1 },
  "9tk": { name: "Battle Dart", code: "9tk", level: 31, tier: 1 },
  "9tr": { name: "Fuscina", code: "9tr", level: 36, tier: 1 },
  "9ts": { name: "Harpoon", code: "9ts", level: 51, tier: 1 },
  "9tw": {
    name: "Greater Talons",
    code: "9tw",
    level: 50,
    tier: 1,
  },
  "9vo": { name: "Bill", code: "9vo", level: 37, tier: 1 },
  "9wa": { name: "Naga", code: "9wa", level: 48, tier: 1 },
  "9wb": { name: "Wrist Spike", code: "9wb", level: 32, tier: 1 },
  "9wc": { name: "Grim Scythe", code: "9wc", level: 55, tier: 1 },
  "9wd": { name: "Ancient Sword", code: "9wd", level: 49, tier: 1 },
  "9wh": { name: "Battle Hammer", code: "9wh", level: 48, tier: 1 },
  "9wn": { name: "Burnt Wand", code: "9wn", level: 31, tier: 1 },
  "9ws": {
    name: "Divine Scepter",
    code: "9ws",
    level: 45,
    tier: 1,
  },
  "9xf": { name: "Fascia", code: "9xf", level: 36, tier: 1 },
  "9yw": {
    name: "Petrified Wand",
    code: "9yw",
    level: 38,
    tier: 1,
  },
  am1: { name: "Stag Bow", code: "am1", level: 18, tier: 0 },
  am2: { name: "Reflex Bow", code: "am2", level: 27, tier: 0 },
  am3: { name: "Maiden Spear", code: "am3", level: 18, tier: 0 },
  am4: { name: "Maiden Pike", code: "am4", level: 27, tier: 0 },
  am5: { name: "Maiden Javelin", code: "am5", level: 23, tier: 0 },
  am6: { name: "Ashwood Bow", code: "am6", level: 39, tier: 1 },
  am7: { name: "Ceremonial Bow", code: "am7", level: 47, tier: 1 },
  am8: {
    name: "Ceremonial Spear",
    code: "am8",
    level: 43,
    tier: 1,
  },
  am9: { name: "Ceremonial Pike", code: "am9", level: 51, tier: 1 },
  ama: {
    name: "Ceremonial Javelin",
    code: "ama",
    level: 35,
    tier: 1,
  },
  amb: { name: "Matriarchal Bow", code: "amb", level: 53, tier: 2 },
  amc: { name: "Grand Matron Bow", code: "amc", level: 78, tier: 2 },
  amd: { name: "Matriarchal Spear", code: "amd", level: 61, tier: 2 },
  ame: { name: "Matriarchal Pike", code: "ame", level: 81, tier: 2 },
  amf: { name: "Matriarchal Javelin", code: "amf", level: 65, tier: 2 },
  axe: { name: "Axe", code: "axe", level: 7, tier: 0 },
  axf: { name: "Hatchet Hands", code: "axf", level: 12, tier: 0 },
  bal: { name: "Balanced Axe", code: "bal", level: 16, tier: 0 },
  bar: { name: "Bardiche", code: "bar", level: 5, tier: 0 },
  bax: { name: "Broad Axe", code: "bax", level: 12, tier: 0 },
  bkf: { name: "Balanced Knife", code: "bkf", level: 13, tier: 0 },
  bld: { name: "Blade", code: "bld", level: 23, tier: 0 },
  brn: { name: "Brandistock", code: "brn", level: 16, tier: 0 },
  bsd: { name: "Broad Sword", code: "bsd", level: 15, tier: 0 },
  bst: { name: "Battle Staff", code: "bst", level: 17, tier: 0 },
  bsw: { name: "Bastard Sword", code: "bsw", level: 24, tier: 0 },
  btl: { name: "Blade Talons", code: "btl", level: 21, tier: 0 },
  btx: { name: "Battle Axe", code: "btx", level: 17, tier: 0 },
  bwn: { name: "Bone Wand", code: "bwn", level: 18, tier: 0 },
  cbw: { name: "Composite Bow", code: "cbw", level: 12, tier: 0 },
  ces: { name: "Cestus", code: "ces", level: 15, tier: 0 },
  clb: { name: "Club", code: "clb", level: 1, tier: 0 },
  clm: { name: "Claymore", code: "clm", level: 17, tier: 0 },
  clw: { name: "Claws", code: "clw", level: 18, tier: 0 },
  crs: { name: "Crystal Sword", code: "crs", level: 11, tier: 0 },
  cst: { name: "Gnarled Staff", code: "cst", level: 12, tier: 0 },
  d33: { name: "Decoy Gidbinn", code: "d33", level: 0, tier: 0 },
  dgr: { name: "Dagger", code: "dgr", level: 3, tier: 0 },
  dir: { name: "Dirk", code: "dir", level: 9, tier: 0 },
  fla: { name: "Flail", code: "fla", level: 19, tier: 0 },
  flb: { name: "Flamberge", code: "flb", level: 27, tier: 0 },
  flc: { name: "Falchion", code: "flc", level: 11, tier: 0 },
  g33: { name: "The Gidbinn", code: "g33", level: 0, tier: 0 },
  gax: { name: "Great Axe", code: "gax", level: 23, tier: 0 },
  gis: { name: "Giant Sword", code: "gis", level: 21, tier: 0 },
  gix: { name: "Giant Axe", code: "gix", level: 27, tier: 0 },
  glv: { name: "Glaive", code: "glv", level: 23, tier: 0 },
  gma: { name: "Great Maul", code: "gma", level: 32, tier: 0 },
  gpl: { name: "StranglingGas Potion", code: "gpl", level: 8, tier: 0 },
  gpm: { name: "Choking Gas Potion", code: "gpm", level: 20, tier: 0 },
  gps: { name: "Rancid Gas Potion", code: "gps", level: 32, tier: 0 },
  gsc: { name: "Grand Scepter", code: "gsc", level: 15, tier: 0 },
  gsd: { name: "Great Sword", code: "gsd", level: 33, tier: 0 },
  gwn: { name: "Grim Wand", code: "gwn", level: 26, tier: 0 },
  hal: { name: "Halberd", code: "hal", level: 29, tier: 0 },
  hax: { name: "Hand Axe", code: "hax", level: 3, tier: 0 },
  hbw: { name: "Hunter's Bow", code: "hbw", level: 5, tier: 0 },
  hdm: { name: "Horadric Malus", code: "hdm", level: 0, tier: 0 },
  hfh: { name: "Hellforge Hammer", code: "hfh", level: 0, tier: 0 },
  hst: { name: "Horadric Staff", code: "hst", level: 0, tier: 0 },
  hxb: { name: "Heavy Crossbow", code: "hxb", level: 24, tier: 0 },
  jav: { name: "Javelin", code: "jav", level: 1, tier: 0 },
  kri: { name: "Kriss", code: "kri", level: 17, tier: 0 },
  ktr: { name: "Katar", code: "ktr", level: 1, tier: 0 },
  lax: { name: "Large Axe", code: "lax", level: 6, tier: 0 },
  lbb: { name: "Long Battle Bow", code: "lbb", level: 23, tier: 0 },
  lbw: { name: "Long Bow", code: "lbw", level: 8, tier: 0 },
  leg: { name: "Wirt's Leg", code: "leg", level: 0, tier: 0 },
  lsd: { name: "LongSword", code: "lsd", level: 20, tier: 0 },
  lst: { name: "Long Staff", code: "lst", level: 8, tier: 0 },
  lwb: { name: "Long War Bow", code: "lwb", level: 31, tier: 0 },
  lxb: { name: "Light Crossbow", code: "lxb", level: 6, tier: 0 },
  mac: { name: "Mace", code: "mac", level: 8, tier: 0 },
  mau: { name: "Maul", code: "mau", level: 21, tier: 0 },
  mpi: { name: "Military Pick", code: "mpi", level: 19, tier: 0 },
  msf: { name: "Staff of Kings", code: "msf", level: 0, tier: 0 },
  mst: { name: "Morning Star", code: "mst", level: 13, tier: 0 },
  mxb: { name: "Crossbow", code: "mxb", level: 15, tier: 0 },
  ob1: { name: "Eagle Orb", code: "ob1", level: 1, tier: 0 },
  ob2: { name: "Sacred Globe", code: "ob2", level: 8, tier: 0 },
  ob3: { name: "Smoked Sphere", code: "ob3", level: 12, tier: 0 },
  ob4: { name: "Clasped Orb", code: "ob4", level: 17, tier: 0 },
  ob5: { name: "Jared's Stone", code: "ob5", level: 24, tier: 0 },
  ob6: { name: "Glowing Orb", code: "ob6", level: 32, tier: 1 },
  ob7: {
    name: "Crystalline Globe",
    code: "ob7",
    level: 37,
    tier: 1,
  },
  ob8: { name: "Cloudy Sphere", code: "ob8", level: 41, tier: 1 },
  ob9: { name: "Sparkling Ball", code: "ob9", level: 46, tier: 1 },
  oba: {
    name: "Swirling Crystal",
    code: "oba",
    level: 50,
    tier: 1,
  },
  obb: { name: "Heavenly Stone", code: "obb", level: 59, tier: 2 },
  obc: { name: "Eldritch Orb", code: "obc", level: 67, tier: 2 },
  obd: { name: "Demon Heart", code: "obd", level: 75, tier: 2 },
  obe: { name: "Vortex Orb", code: "obe", level: 84, tier: 2 },
  obf: { name: "Dimensional Shard", code: "obf", level: 85, tier: 2 },
  opl: { name: "Fulminating Potion", code: "opl", level: 4, tier: 0 },
  opm: { name: "Exploding Potion", code: "opm", level: 16, tier: 0 },
  ops: { name: "Oil Potion", code: "ops", level: 28, tier: 0 },
  pax: { name: "Poleaxe", code: "pax", level: 21, tier: 0 },
  pik: { name: "Pike", code: "pik", level: 24, tier: 0 },
  pil: { name: "Pilum", code: "pil", level: 10, tier: 0 },
  rxb: { name: "Repeating Crossbow", code: "rxb", level: 33, tier: 0 },
  sbb: { name: "Short Battle Bow", code: "sbb", level: 18, tier: 0 },
  sbr: { name: "Saber", code: "sbr", level: 8, tier: 0 },
  sbw: { name: "Short Bow", code: "sbw", level: 1, tier: 0 },
  scm: { name: "Scimitar", code: "scm", level: 5, tier: 0 },
  scp: { name: "Scepter", code: "scp", level: 3, tier: 0 },
  scy: { name: "Scythe", code: "scy", level: 15, tier: 0 },
  skr: { name: "Scissors Katar", code: "skr", level: 24, tier: 0 },
  spc: { name: "Spiked Club", code: "spc", level: 4, tier: 0 },
  spr: { name: "Spear", code: "spr", level: 5, tier: 0 },
  spt: { name: "Spetum", code: "spt", level: 20, tier: 0 },
  ssd: { name: "ShortSword", code: "ssd", level: 1, tier: 0 },
  ssp: { name: "Short Spear", code: "ssp", level: 15, tier: 0 },
  sst: { name: "Short Staff", code: "sst", level: 1, tier: 0 },
  swb: { name: "Short War Bow", code: "swb", level: 27, tier: 0 },
  tax: { name: "Throwing Axe", code: "tax", level: 7, tier: 0 },
  tkf: { name: "Throwing Knife", code: "tkf", level: 2, tier: 0 },
  tri: { name: "Trident", code: "tri", level: 9, tier: 0 },
  tsp: { name: "Throwing Spear", code: "tsp", level: 29, tier: 0 },
  vou: { name: "Voulge", code: "vou", level: 11, tier: 0 },
  wax: { name: "War Axe", code: "wax", level: 25, tier: 0 },
  whm: { name: "War Hammer", code: "whm", level: 25, tier: 0 },
  wnd: { name: "Wand", code: "wnd", level: 2, tier: 0 },
  wrb: { name: "Wrist Blade", code: "wrb", level: 9, tier: 0 },
  wsc: { name: "War Scythe", code: "wsc", level: 34, tier: 0 },
  wsd: { name: "War Sword", code: "wsd", level: 27, tier: 0 },
  wsp: { name: "War Scepter", code: "wsp", level: 21, tier: 0 },
  wst: { name: "War Staff", code: "wst", level: 24, tier: 0 },
  ywn: { name: "Yew Wand", code: "ywn", level: 12, tier: 0 },
};

export const ArmorDict: WeaponArmorDictType = {
  aar: { name: "Ancient Armor", code: "aar", level: 40, tier: 0 },
  ba1: { name: "Jawbone Cap", code: "ba1", level: 4, tier: 0 },
  ba2: { name: "Fanged Helm", code: "ba2", level: 8, tier: 0 },
  ba3: { name: "Horned Helm", code: "ba3", level: 16, tier: 0 },
  ba4: { name: "Assault Helmet", code: "ba4", level: 20, tier: 0 },
  ba5: { name: "Avenger Guard", code: "ba5", level: 24, tier: 0 },
  ba6: { name: "Jawbone Visor", code: "ba6", level: 33, tier: 1 },
  ba7: { name: "Lion Helm", code: "ba7", level: 38, tier: 1 },
  ba8: { name: "Rage Mask", code: "ba8", level: 44, tier: 1 },
  ba9: { name: "Savage Helmet", code: "ba9", level: 49, tier: 1 },
  baa: { name: "Slayer Guard", code: "baa", level: 54, tier: 1 },
  bab: { name: "Carnage Helm", code: "bab", level: 60, tier: 2 },
  bac: { name: "Fury Visor", code: "bac", level: 66, tier: 2 },
  bad: { name: "Destroyer Helm", code: "bad", level: 73, tier: 2 },
  bae: { name: "Conqueror Crown", code: "bae", level: 80, tier: 2 },
  baf: { name: "Guardian Crown", code: "baf", level: 85, tier: 2 },
  bhm: { name: "Bone Helm", code: "bhm", level: 22, tier: 0 },
  brs: { name: "Breast Plate", code: "brs", level: 18, tier: 0 },
  bsh: { name: "Bone Shield", code: "bsh", level: 19, tier: 0 },
  buc: { name: "Buckler", code: "buc", level: 1, tier: 0 },
  cap: { name: "Cap", code: "cap", level: 1, tier: 0 },
  chn: { name: "Chain Mail", code: "chn", level: 15, tier: 0 },
  ci0: { name: "Circlet", code: "ci0", level: 24, tier: 0 },
  ci1: { name: "Coronet", code: "ci1", level: 52, tier: 0 },
  ci2: { name: "Tiara", code: "ci2", level: 70, tier: 1 },
  ci3: { name: "Diadem", code: "ci3", level: 85, tier: 2 },
  crn: { name: "Crown", code: "crn", level: 29, tier: 0 },
  dr1: { name: "Wolf Head", code: "dr1", level: 4, tier: 0 },
  dr2: { name: "Hawk Helm", code: "dr2", level: 8, tier: 0 },
  dr3: { name: "Antlers", code: "dr3", level: 16, tier: 0 },
  dr4: { name: "Falcon Mask", code: "dr4", level: 20, tier: 0 },
  dr5: { name: "Spirit Mask", code: "dr5", level: 24, tier: 0 },
  dr6: { name: "Alpha Helm", code: "dr6", level: 35, tier: 1 },
  dr7: {
    name: "Griffon Headress",
    code: "dr7",
    level: 40,
    tier: 1,
  },
  dr8: { name: "Hunter's Guise", code: "dr8", level: 46, tier: 1 },
  dr9: { name: "Sacred Feathers", code: "dr9", level: 50, tier: 1 },
  dra: { name: "Totemic Mask", code: "dra", level: 55, tier: 1 },
  drb: { name: "Blood Spirit", code: "drb", level: 62, tier: 2 },
  drc: { name: "Sun Spirit", code: "drc", level: 69, tier: 2 },
  drd: { name: "Earth Spirit", code: "drd", level: 76, tier: 2 },
  dre: { name: "Sky Spirit", code: "dre", level: 83, tier: 2 },
  drf: { name: "Dream Spirit", code: "drf", level: 85, tier: 2 },
  fhl: { name: "Full Helm", code: "fhl", level: 15, tier: 0 },
  fld: { name: "Field Plate", code: "fld", level: 28, tier: 0 },
  ful: { name: "Full Plate Mail", code: "ful", level: 37, tier: 0 },
  ghm: { name: "Great Helm", code: "ghm", level: 23, tier: 0 },
  gth: { name: "Gothic Plate", code: "gth", level: 32, tier: 0 },
  gts: { name: "Gothic Shield", code: "gts", level: 30, tier: 0 },
  hbl: { name: "Plated Belt", code: "hbl", level: 27, tier: 0 },
  hbt: { name: "Greaves", code: "hbt", level: 27, tier: 0 },
  hgl: { name: "Gauntlets", code: "hgl", level: 27, tier: 0 },
  hla: { name: "Hard Leather Armor", code: "hla", level: 5, tier: 0 },
  hlm: { name: "Helm", code: "hlm", level: 11, tier: 0 },
  kit: { name: "Kite Shield", code: "kit", level: 15, tier: 0 },
  lbl: { name: "Sash", code: "lbl", level: 3, tier: 0 },
  lbt: { name: "Boots", code: "lbt", level: 3, tier: 0 },
  lea: { name: "Leather Armor", code: "lea", level: 3, tier: 0 },
  lgl: { name: "Leather Gloves", code: "lgl", level: 3, tier: 0 },
  lrg: { name: "Large Shield", code: "lrg", level: 11, tier: 0 },
  ltp: { name: "Light Plate", code: "ltp", level: 35, tier: 0 },
  mbl: { name: "Belt", code: "mbl", level: 12, tier: 0 },
  mbt: { name: "Chain Boots", code: "mbt", level: 12, tier: 0 },
  mgl: { name: "Chain Gloves", code: "mgl", level: 12, tier: 0 },
  msk: { name: "Mask", code: "msk", level: 19, tier: 0 },
  ne1: { name: "Preserved Head", code: "ne1", level: 4, tier: 0 },
  ne2: { name: "Zombie Head", code: "ne2", level: 8, tier: 0 },
  ne3: { name: "Unraveller Head", code: "ne3", level: 16, tier: 0 },
  ne4: { name: "Gargoyle Head", code: "ne4", level: 20, tier: 0 },
  ne5: { name: "Demon Head", code: "ne5", level: 24, tier: 0 },
  ne6: {
    name: "Mummified Trophy",
    code: "ne6",
    level: 33,
    tier: 1,
  },
  ne7: { name: "Fetish Trophy", code: "ne7", level: 39, tier: 1 },
  ne8: { name: "Sexton Trophy", code: "ne8", level: 45, tier: 1 },
  ne9: { name: "Cantor Trophy", code: "ne9", level: 49, tier: 1 },
  nea: {
    name: "Heirophant Trophy",
    code: "nea",
    level: 54,
    tier: 1,
  },
  neb: { name: "Minion Skull", code: "neb", level: 59, tier: 2 },
  ned: { name: "Overseer Skull", code: "ned", level: 66, tier: 2 },
  nee: { name: "Succubus Skull", code: "nee", level: 81, tier: 2 },
  nef: { name: "Bloodlord Skull", code: "nef", level: 85, tier: 2 },
  neg: { name: "Hellspawn Skull", code: "neg", level: 67, tier: 2 },
  pa1: { name: "Targe", code: "pa1", level: 4, tier: 0 },
  pa2: { name: "Rondache", code: "pa2", level: 8, tier: 0 },
  pa3: { name: "Heraldic Shield", code: "pa3", level: 16, tier: 0 },
  pa4: { name: "Aerin Shield", code: "pa4", level: 20, tier: 0 },
  pa5: { name: "Crown Shield", code: "pa5", level: 24, tier: 0 },
  pa6: { name: "Akaran Targe", code: "pa6", level: 35, tier: 1 },
  pa7: { name: "Akaran Rondache", code: "pa7", level: 40, tier: 1 },
  pa8: {
    name: "Protector Shield",
    code: "pa8",
    level: 46,
    tier: 1,
  },
  pa9: { name: "Gilded Shield", code: "pa9", level: 51, tier: 1 },
  paa: { name: "Royal Shield", code: "paa", level: 55, tier: 1 },
  pab: { name: "Sacred Targe", code: "pab", level: 63, tier: 2 },
  pac: { name: "Sacred Rondache", code: "pac", level: 70, tier: 2 },
  pad: { name: "Ancient Shield", code: "pad", level: 74, tier: 2 },
  pae: { name: "Zakarum Shield", code: "pae", level: 82, tier: 2 },
  paf: { name: "Vortex Shield", code: "paf", level: 85, tier: 2 },
  plt: { name: "Plate Mail", code: "plt", level: 24, tier: 0 },
  qui: { name: "Quilted Armor", code: "qui", level: 1, tier: 0 },
  rng: { name: "Ring Mail", code: "rng", level: 11, tier: 0 },
  scl: { name: "Scale Mail", code: "scl", level: 13, tier: 0 },
  skp: { name: "Skull Cap", code: "skp", level: 5, tier: 0 },
  sml: { name: "Small Shield", code: "sml", level: 5, tier: 0 },
  spk: { name: "Spiked Shield", code: "spk", level: 11, tier: 0 },
  spl: { name: "Splint Mail", code: "spl", level: 20, tier: 0 },
  stu: { name: "Studded Leather", code: "stu", level: 8, tier: 0 },
  tbl: { name: "Heavy Belt", code: "tbl", level: 20, tier: 0 },
  tbt: { name: "Light Plated Boots", code: "tbt", level: 20, tier: 0 },
  tgl: { name: "Light Gauntlets", code: "tgl", level: 20, tier: 0 },
  tow: { name: "Tower Shield", code: "tow", level: 22, tier: 0 },
  uap: { name: "Shako", code: "uap", level: 58, tier: 2 },
  uar: { name: "Sacred Armor", code: "uar", level: 85, tier: 2 },
  ucl: { name: "Loricated Mail", code: "ucl", level: 73, tier: 2 },
  uea: { name: "Wyrmhide", code: "uea", level: 67, tier: 2 },
  uh9: { name: "Bone Visage", code: "uh9", level: 84, tier: 2 },
  uhb: { name: "Myrmidon Greaves", code: "uhb", level: 85, tier: 2 },
  uhc: { name: "Colossus Girdle", code: "uhc", level: 85, tier: 2 },
  uhg: { name: "Ogre Gauntlets", code: "uhg", level: 85, tier: 2 },
  uhl: { name: "Giant Conch", code: "uhl", level: 54, tier: 2 },
  uhm: { name: "Spired Helm", code: "uhm", level: 79, tier: 2 },
  uhn: { name: "Boneweave", code: "uhn", level: 62, tier: 2 },
  uit: { name: "Monarch", code: "uit", level: 72, tier: 2 },
  ukp: { name: "Hydraskull", code: "ukp", level: 63, tier: 2 },
  ula: { name: "Scarab Husk", code: "ula", level: 68, tier: 2 },
  ulb: { name: "Wyrmhide Boots", code: "ulb", level: 60, tier: 2 },
  ulc: { name: "Spiderweb Sash", code: "ulc", level: 61, tier: 2 },
  uld: { name: "Kraken Shell", code: "uld", level: 81, tier: 2 },
  ulg: { name: "Bramble Mitts", code: "ulg", level: 57, tier: 2 },
  ulm: { name: "Armet", code: "ulm", level: 68, tier: 2 },
  ult: { name: "Hellforge Plate", code: "ult", level: 78, tier: 2 },
  umb: { name: "Boneweave Boots", code: "umb", level: 72, tier: 2 },
  umc: { name: "Mithril Coil", code: "umc", level: 75, tier: 2 },
  umg: { name: "Vambraces", code: "umg", level: 69, tier: 2 },
  uml: { name: "Luna", code: "uml", level: 61, tier: 2 },
  ung: { name: "Diamond Mail", code: "ung", level: 72, tier: 2 },
  uow: { name: "Aegis", code: "uow", level: 79, tier: 2 },
  upk: { name: "Blade Barrier", code: "upk", level: 68, tier: 2 },
  upl: { name: "Balrog Skin", code: "upl", level: 76, tier: 2 },
  urg: { name: "Hyperion", code: "urg", level: 64, tier: 2 },
  urn: { name: "Corona", code: "urn", level: 85, tier: 2 },
  urs: { name: "Great Hauberk", code: "urs", level: 75, tier: 2 },
  ush: { name: "Troll Nest", code: "ush", level: 76, tier: 2 },
  usk: { name: "Demonhead", code: "usk", level: 74, tier: 2 },
  utb: { name: "Mirrored Boots", code: "utb", level: 81, tier: 2 },
  utc: { name: "Troll Belt", code: "utc", level: 82, tier: 2 },
  utg: { name: "Crusader Gauntlets", code: "utg", level: 76, tier: 2 },
  uth: { name: "Lacquered Plate", code: "uth", level: 82, tier: 2 },
  utp: { name: "Archon Plate", code: "utp", level: 84, tier: 2 },
  uts: { name: "Ward", code: "uts", level: 84, tier: 2 },
  utu: { name: "Wire Fleece", code: "utu", level: 70, tier: 2 },
  uuc: { name: "Heater", code: "uuc", level: 58, tier: 2 },
  uui: { name: "Dusk Shroud", code: "uui", level: 65, tier: 2 },
  uul: { name: "Shadow Plate", code: "uul", level: 83, tier: 2 },
  uvb: { name: "Scarabshell Boots", code: "uvb", level: 66, tier: 2 },
  uvc: { name: "Vampirefang Belt", code: "uvc", level: 68, tier: 2 },
  uvg: { name: "Vampirebone Gloves", code: "uvg", level: 63, tier: 2 },
  vbl: { name: "Light Belt", code: "vbl", level: 7, tier: 0 },
  vbt: { name: "Heavy Boots", code: "vbt", level: 7, tier: 0 },
  vgl: { name: "Heavy Gloves", code: "vgl", level: 7, tier: 0 },
  xap: { name: "War Hat", code: "xap", level: 34, tier: 1 },
  xar: { name: "Ornate Armor", code: "xar", level: 64, tier: 1 },
  xcl: { name: "Tigulated Mail", code: "xcl", level: 43, tier: 1 },
  xea: {
    name: "Serpentskin Armor",
    code: "xea",
    level: 36,
    tier: 1,
  },
  xh9: { name: "Grim Helm", code: "xh9", level: 50, tier: 1 },
  xhb: { name: "War Boots", code: "xhb", level: 54, tier: 1 },
  xhg: { name: "War Gauntlets", code: "xhg", level: 54, tier: 1 },
  xhl: { name: "Basinet", code: "xhl", level: 45, tier: 1 },
  xhm: { name: "Winged Helm", code: "xhm", level: 51, tier: 1 },
  xhn: { name: "Mesh Armor", code: "xhn", level: 45, tier: 1 },
  xit: { name: "Dragon Shield", code: "xit", level: 45, tier: 1 },
  xkp: { name: "Sallet", code: "xkp", level: 37, tier: 1 },
  xla: { name: "Demonhide Armor", code: "xla", level: 37, tier: 1 },
  xlb: { name: "Demonhide Boots", code: "xlb", level: 36, tier: 1 },
  xld: {
    name: "Sharktooth Armor",
    code: "xld",
    level: 55,
    tier: 1,
  },
  xlg: {
    name: "Demonhide Gloves",
    code: "xlg",
    level: 33,
    tier: 1,
  },
  xlm: { name: "Casque", code: "xlm", level: 42, tier: 1 },
  xlt: { name: "Templar Coat", code: "xlt", level: 52, tier: 1 },
  xmb: { name: "Mesh Boots", code: "xmb", level: 43, tier: 1 },
  xmg: { name: "Heavy Bracers", code: "xmg", level: 43, tier: 1 },
  xml: { name: "Round Shield", code: "xml", level: 37, tier: 1 },
  xng: { name: "Linked Mail", code: "xng", level: 42, tier: 1 },
  xow: { name: "Pavise", code: "xow", level: 50, tier: 1 },
  xpk: { name: "Barbed Shield", code: "xpk", level: 42, tier: 1 },
  xpl: { name: "Russet Armor", code: "xpl", level: 49, tier: 1 },
  xrg: { name: "Scutum", code: "xrg", level: 42, tier: 1 },
  xrn: { name: "Grand Crown", code: "xrn", level: 55, tier: 1 },
  xrs: { name: "Cuirass", code: "xrs", level: 47, tier: 1 },
  xsh: { name: "Grim Shield", code: "xsh", level: 48, tier: 1 },
  xsk: { name: "Death Mask", code: "xsk", level: 48, tier: 1 },
  xtb: { name: "Battle Boots", code: "xtb", level: 49, tier: 1 },
  xtg: {
    name: "Battle Gauntlets",
    code: "xtg",
    level: 49,
    tier: 1,
  },
  xth: { name: "Embossed Plate", code: "xth", level: 58, tier: 1 },
  xtp: { name: "Mage Plate", code: "xtp", level: 60, tier: 1 },
  xts: { name: "Ancient Shield", code: "xts", level: 56, tier: 1 },
  xtu: { name: "Trellised Armor", code: "xtu", level: 40, tier: 1 },
  xuc: { name: "Defender", code: "xuc", level: 34, tier: 1 },
  xui: { name: "Ghost Armor", code: "xui", level: 34, tier: 1 },
  xul: { name: "Chaos Armor", code: "xul", level: 61, tier: 1 },
  xvb: { name: "Sharkskin Boots", code: "xvb", level: 39, tier: 1 },
  xvg: {
    name: "Sharkskin Gloves",
    code: "xvg",
    level: 39,
    tier: 1,
  },
  zhb: { name: "War Belt", code: "zhb", level: 54, tier: 1 },
  zlb: { name: "Demonhide Sash", code: "zlb", level: 36, tier: 1 },
  zmb: { name: "Mesh Belt", code: "zmb", level: 43, tier: 1 },
  ztb: { name: "Battle Belt", code: "ztb", level: 49, tier: 1 },
  zvb: { name: "Sharkskin Belt", code: "zvb", level: 39, tier: 1 },
};
